# Import

In [ ]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (4.4.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (1.16.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)

In [ ]:
!pip install scikit-learn==1.1.3

Collecting scikit-learn==1.1.3
  Using cached scikit_learn-1.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (2.0.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (1.15.3)
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (3.6.0)
Using cached scikit_learn-1.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32.0 MB)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.7.0
    Uninstalling scikit-learn-1.7.0:
      Successfully uninstalled scikit-learn-1.7.0
WARNING: Ignoring invalid distribution ~cikit-learn (/usr/local/lib/python3.11/dist-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikeras 0.13.0 requires scikit-learn>=1.4.2, but you have scikit-learn 1.1.3 which is incompatible.
imbalanced-learn 0.13.0 requires scikit-learn<2,>=1.3.2, but you have scikit-learn 1.1.3 which is incompatible.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, but you have scikit-learn 1.1.3 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.1.3 which is incompatible.
Successfully installed scikit-learn

In [ ]:
!pip install scikeras

WARNING: Ignoring invalid distribution ~cikit-learn (/usr/local/lib/python3.11/dist-packages)
WARNING: Ignoring invalid distribution ~cikit-learn (/usr/local/lib/python3.11/dist-packages)
Requirement already satisfied: scikeras in /usr/local/lib/python3.11/dist-packages (0.13.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Collecting scikit-learn>=1.4.2 (from scikeras)
  Using cached scikit_learn-1.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (17 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.16.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Using cached scikit_learn-1.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
WARNING: Ignoring invalid distribution ~cikit-learn (/usr/local/lib/python3.11/dist-packages)
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.0 which is incompatible.
Successfully installed scikit-learn-1.7.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input, LayerNormalization, Bidirectional, LSTM
from tensorflow.keras.losses import mse
from tensorflow.keras.metrics import RootMeanSquaredError, MeanSquaredError
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping
from sklearn.metrics import make_scorer, mean_squared_error
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler

# 원본 데이터 전처리

In [ ]:
# 3개년 데이터 로드 (인덱스 자동추가 제외)
origin_2021 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_subway21.csv', index_col=0)
origin_2022 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_subway22.csv', index_col=0)
origin_2023 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_subway23.csv', index_col=0)

In [ ]:
# 칼럼명 변경
origin_2021 = origin_2021.rename(columns={
    'train_subway21.tm': 'time',
    'train_subway21.line': 'line',
    'train_subway21.station_number': 'station_number',
    'train_subway21.station_name': 'station_name',
    'train_subway21.direction': 'direction',
    'train_subway21.stn': 'AWS_num',
    'train_subway21.ta': 'temp',
    'train_subway21.wd': 'wind_direction',
    'train_subway21.ws': 'wind_speed',
    'train_subway21.rn_day': 'rn_day',
    'train_subway21.rn_hr1': 'rn_hr',
    'train_subway21.hm': 'humidity',
    'train_subway21.si': 'solar',
    'train_subway21.ta_chi': 'feel_temp',
    'train_subway21.congestion': 'congestion'
})

origin_2022 = origin_2022.rename(columns={
    'train_subway22.tm': 'time',
    'train_subway22.line': 'line',
    'train_subway22.station_number': 'station_number',
    'train_subway22.station_name': 'station_name',
    'train_subway22.direction': 'direction',
    'train_subway22.stn': 'AWS_num',
    'train_subway22.ta': 'temp',
    'train_subway22.wd': 'wind_direction',
    'train_subway22.ws': 'wind_speed',
    'train_subway22.rn_day': 'rn_day',
    'train_subway22.rn_hr1': 'rn_hr',
    'train_subway22.hm': 'humidity',
    'train_subway22.si': 'solar',
    'train_subway22.ta_chi': 'feel_temp',
    'train_subway22.congestion': 'congestion'
})

origin_2023 = origin_2023.rename(columns={
    'train_subway23.tm': 'time',
    'train_subway23.line': 'line',
    'train_subway23.station_number': 'station_number',
    'train_subway23.station_name': 'station_name',
    'train_subway23.direction': 'direction',
    'train_subway23.stn': 'AWS_num',
    'train_subway23.ta': 'temp',
    'train_subway23.wd': 'wind_direction',
    'train_subway23.ws': 'wind_speed',
    'train_subway23.rn_day': 'rn_day',
    'train_subway23.rn_hr1': 'rn_hr',
    'train_subway23.hm': 'humidity',
    'train_subway23.si': 'solar',
    'train_subway23.ta_chi': 'feel_temp',
    'train_subway23.congestion': 'congestion'
})

In [ ]:
# origin dataframe 통합
origin_all = pd.concat([origin_2021, origin_2022, origin_2023], ignore_index=True)
origin_all

,time,line,station_number,station_name,direction,AWS_num,temp,wind_direction,wind_speed,rn_day,rn_hr,humidity,solar,feel_temp,congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,-99.0,-99.0,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,-99.0,-99.0,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,-99.0,-99.0,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,-99.0,-99.0,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,-99.0,-99.0,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,7.0,0.0,83.1,-99.0,0.0,18
16369320,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,7.0,0.0,84.7,-99.0,-0.6,17
16369321,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,7.0,0.0,85.1,-99.0,-1.1,21
16369322,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,7.0,0.0,85.6,-99.0,-1.3,18
16369323,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,7.0,0.0,85.6,-99.0,-1.9,22

In [ ]:
# 결측값 → NaN
sentinels = [-99, -99.9, -999.0]
origin_all = origin_all.replace(sentinels, np.nan)

In [ ]:
#이상치 처
def find_iqr_outliers(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return (series < lower) | (series > upper)

num_cols = ['temp', 'wind_direction', 'wind_speed', 'rn_day', 'rn_hr', 'humidity', 'solar', 'feel_temp']

for col in num_cols:
    outlier_mask = find_iqr_outliers(origin_all[col])
    origin_all.loc[outlier_mask, col] = np.nan  # 이상치만 NaN 처리

In [ ]:
# 결측치 확인
print('결측치 처리 전 결측치 개수')
print(origin_all.isnull().sum())

결측치 처리 전 결측치 개수
time                    0
line                    0
station_number          0
station_name            0
direction               0
AWS_num                 0
temp               216672
wind_direction     230786
wind_speed         714650
rn_day            3241523
rn_hr             1293576
humidity           844594
solar             6064242
feel_temp            1076
congestion              0
dtype: int64

In [ ]:
df=origin_all.copy()

In [ ]:
df['time'] = pd.to_datetime(df['time'], format='%Y%m%d%H')
df['month'] = df['time'].dt.month
df['hour'] = df['time'].dt.hour

# 2. 겨울/여름 마스크 (벡터화)
winter_mask = df['month'].isin([12, 1, 2])
summer_mask = df['month'].isin([6, 7, 8])
remain = df['month'].isin([3,4,5, 9, 10, 11])
# 3. 밤시간 (벡터화)
df['is_night'] = (
    (winter_mask & ((df['hour'] >= 20) | (df['hour'] < 5))) |
    (summer_mask & ((df['hour'] >= 22) | (df['hour'] < 5))) |
    (remain & ((df['hour'] >= 21) | (df['hour'] < 5)))
)
df.loc[df['is_night'] & df['solar'].isnull(), 'solar'] = int(0)

# 임시 컬럼 제거
df.drop(['month', 'hour', 'is_night'], axis=1, inplace=True)

In [ ]:
df = df.sort_values(['AWS_num', 'time']).reset_index(drop=True)

In [ ]:
target_cols = ['temp', 'wind_direction', 'wind_speed', 'rn_day', 'rn_hr', 'humidity', 'solar', 'feel_temp']
specific_cols = ['wind_direction', 'rn_day', 'rn_hr']
linear_cols = ['temp', 'wind_speed','humidity', 'solar', 'feel_temp']
# 0단계: 동일 관측소그룹별 specific_cols을 시간순으로 bfill/ffill
print('0단계 시작')
for col in specific_cols:
    df[col] = (
        df.groupby('AWS_num')[col]
        .apply(lambda x: x.bfill().ffill())  # 각 그룹에서만 보간
        .reset_index(drop=True)
    )
print(df.isnull().sum())
print('----------------------------------')

#1단계 :동일 관측소그룹별 linear_cols을 시간순으로 선형보간
print('1단계 시작')
for col in linear_cols:
    df[col] = (
        df
        .sort_values(['AWS_num', 'time'])  # 그룹 내 정렬!
        .groupby('AWS_num')[col]
        .apply(lambda x: x.interpolate(method='linear'))  # 각 그룹에서만 보간
        .reset_index(drop=True)
    )
print(df.isnull().sum())
print('----------------------------------')

print('2단계 시작')
for col in linear_cols:
    # 1) 그룹 내 중앙값으로 채우기
    df[col] = (
        df.groupby('AWS_num')[col]
        .apply(lambda x: x.fillna(x.median()))
        .reset_index(drop=True)
    )
    # 2) 그래도 남으면 전체 중앙값
    df[col] = df[col].fillna(df[col].median())
print(df.isnull().sum())
print('----------------------------------')

0단계 시작
time                    0
line                    0
station_number          0
station_name            0
direction               0
AWS_num                 0
temp               216672
wind_direction          0
wind_speed         714650
rn_day                  0
rn_hr                   0
humidity           844594
solar             2220357
feel_temp            1076
congestion              0
dtype: int64
----------------------------------
1단계 시작
time                   0
line                   0
station_number         0
station_name           0
direction              0
AWS_num                0
temp                4634
wind_direction         0
wind_speed          4636
rn_day                 0
rn_hr                  0
humidity          633392
solar                  0
feel_temp              0
congestion             0
dtype: int64
----------------------------------
2단계 시작
time              0
line              0
station_number    0
station_name      0
direction         0
AWS_num           0
temp              0
wind_direction    0
wind_speed        0
rn_day            0
rn_hr             0
humidity          0
solar             0
feel_temp         0
congestion        0
dtype: int64
----------------------------------

In [ ]:
# 상/하행 레이블 정의
direction_map = {'상선': 0, '하선': 1, '내선': 2, '외선':3}

# 체감온도 구간 레이블 정의
bins = [-float('inf'), -10, 5, 20, 28, float('inf')]
labels = ["0", "1", "2", "3", "4"]

# 임시 DataFrame temp_df 정의
temp_df = df.copy()

# direction을 숫자 레이블로 변환
temp_df['direction'] = temp_df['direction'].map(direction_map)

# 체감온도 단계 파생변수 추가
temp_df['feel_stage'] = pd.cut(temp_df['feel_temp'], bins=bins, labels=labels).astype(int)

In [ ]:
holidays = [
    # 2021
    '20210101','20210211','20210212','20210213','20210301',
    '20210505','20210519','20210606','20210815','20210920',
    '20210921','20210922','20211003','20211009','20211225',
    # 2022
    '20220101','20220131','20220201','20220202','20220301',
    '20220309','20220505','20220508','20220601','20220606',
    '20220815','20220909','20220910','20220911','20220912',
    '20221003','20221009','20221010','20221225',
    # 2023
    '20230101','20230121','20230122','20230123','20230124',
    '20230301','20230505','20230527','20230529','20230606',
    '20230815','20230928','20230929','20230930','20231002',
    '20231003','20231009','20231225'
]
# 공휴일 리스트를 set으로 변환하여 조회 속도 향상
holidays_set = set(holidays)

# 2. 'is_holiday' 컬럼 초기화 (기본값 0: 평일)
temp_df['is_holiday'] = 0

# 3. 주말(토/일) 확인하여 1로 설정
# .dt.dayofweek는 요일을 숫자로 반환합니다 (월=0, 화=1, ..., 토=5, 일=6)
is_weekend = (temp_df['time'].dt.dayofweek >= 5)
temp_df.loc[is_weekend, 'is_holiday'] = 1

# 4. 공휴일 확인하여 1로 설정 (주말과 겹치더라도 1로 유지됨)
# .dt.strftime('%Y%m%d')로 날짜 부분만 YYYYMMDD 문자열로 변환하여 공휴일 리스트와 비교
is_in_holidays = temp_df['time'].dt.strftime('%Y%m%d').isin(holidays_set)
temp_df.loc[is_in_holidays, 'is_holiday'] = 1

In [ ]:
temp_df = temp_df.sort_values(['station_number', 'AWS_num','direction','time']).reset_index(drop=True)
temp_df

,time,line,station_number,station_name,direction,AWS_num,temp,wind_direction,wind_speed,rn_day,rn_hr,humidity,solar,feel_temp,congestion,feel_stage,is_holiday
0,2021-01-01 00:00:00,1,150,서울역,0,419,-9.6,291.1,3.3,0.0,0.0,64.1,0.000000,-12.6,0,0,1
1,2021-01-01 01:00:00,1,150,서울역,0,419,-9.7,284.6,2.0,0.0,0.0,64.1,0.000000,-9.8,0,1,1
2,2021-01-01 05:00:00,1,150,서울역,0,419,-9.3,124.7,2.4,0.0,0.0,64.1,0.000000,-10.3,1,0,1
3,2021-01-01 06:00:00,1,150,서울역,0,419,-9.3,126.2,1.7,0.0,0.0,64.1,0.000000,-10.1,2,0,1
4,2021-01-01 07:00:00,1,150,서울역,0,419,-9.1,145.7,1.3,0.0,0.0,64.1,0.000000,-9.7,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023-12-31 19:00:00,6,9006,응암S,1,400,1.4,0.0,0.0,0.0,0.0,92.1,0.007959,1.3,15,1,1
16369320,2023-12-31 20:00:00,6,9006,응암S,1,400,0.8,308.8,0.5,0.0,0.0,95.3,0.000000,0.7,13,1,1
16369321,2023-12-31 21:00:00,6,9006,응암S,1,400,0.4,320.6,0.1,0.0,0.0,96.2,0.000000,0.2,14,1,1
16369322,2023-12-31 22:00:00,6,9006,응암S,1,400,0.0,117.6,0.1,0.0,0.0,97.1,0.000000,0.0,14,1,1
16369323,2023-12-31 23:00:00,6,9006,응암S,1,400,-0.2,0.4,0.2,0.0,0.0,97.6,0.000000,-0.4,12,1,1

In [ ]:
# 필요한 칼럼만 추출
selected_cols = [
    'time',
    'station_number',
    'direction',
    'temp',
    'wind_speed',
    'rn_hr',
    'humidity',
    'solar',
    'congestion',
    'feel_temp',
    'feel_stage',
    'is_holiday'
]

# temp_df에서 필요한 컬럼만 train_data DataFrame에 저장
train_data = temp_df[selected_cols].copy()

# station_number, direction, time 순으로 정렬
train_data = train_data.sort_values(
    by=['station_number', 'direction', 'time']
).reset_index(drop=True)

# time 제거
train_data = train_data.iloc[:, 1:]

# 완성
train_data

,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_temp,feel_stage,is_holiday
0,150,0,-9.6,3.3,0.0,64.1,0.000000,0,-12.6,0,1
1,150,0,-9.7,2.0,0.0,64.1,0.000000,0,-9.8,1,1
2,150,0,-9.3,2.4,0.0,64.1,0.000000,1,-10.3,0,1
3,150,0,-9.3,1.7,0.0,64.1,0.000000,2,-10.1,0,1
4,150,0,-9.1,1.3,0.0,64.1,0.000000,3,-9.7,1,1
...,...,...,...,...,...,...,...,...,...,...,...
16369319,9006,1,1.4,0.0,0.0,92.1,0.007959,15,1.3,1,1
16369320,9006,1,0.8,0.5,0.0,95.3,0.000000,13,0.7,1,1
16369321,9006,1,0.4,0.1,0.0,96.2,0.000000,14,0.2,1,1
16369322,9006,1,0.0,0.1,0.0,97.1,0.000000,14,0.0,1,1
16369323,9006,1,-0.2,0.2,0.0,97.6,0.000000,12,-0.4,1,1

## 슬라이딩 윈도우

In [ ]:
def extract_inputoutput_shift(df, lookback_time=2, predict_time=1):
    # 1) 과거 시점별 피처 생성
    feat_dfs = []
    for t in range(lookback_time):
        tmp = df.shift(t)
        feat_dfs.append(tmp)
    X = pd.concat(feat_dfs, axis=1)

    # 2) 예측 대상(타깃) 생성
    y = df[['congestion']].shift(-predict_time)

    # 3) NaN 제거 및 인덱스 리셋
    valid_idx = X.dropna().index.intersection(y.dropna().index)
    X = X.loc[valid_idx].reset_index(drop=True)
    y = y.loc[valid_idx].reset_index(drop=True)

    print("X, Y 데이터 분류 완료!")
    return X, y

In [ ]:
x, t = extract_inputoutput_shift(train_data)
x

X, Y 데이터 분류 완료!

,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_temp,feel_stage,...,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_temp,feel_stage,is_holiday
0,150,0,-9.7,2.0,0.0,64.1,0.000000,0,-9.8,1,...,0.0,-9.6,3.3,0.0,64.1,0.000000,0.0,-12.6,0.0,1.0
1,150,0,-9.3,2.4,0.0,64.1,0.000000,1,-10.3,0,...,0.0,-9.7,2.0,0.0,64.1,0.000000,0.0,-9.8,1.0,1.0
2,150,0,-9.3,1.7,0.0,64.1,0.000000,2,-10.1,0,...,0.0,-9.3,2.4,0.0,64.1,0.000000,1.0,-10.3,0.0,1.0
3,150,0,-9.1,1.3,0.0,64.1,0.000000,3,-9.7,1,...,0.0,-9.3,1.7,0.0,64.1,0.000000,2.0,-10.1,0.0,1.0
4,150,0,-8.5,0.6,0.0,64.1,0.000000,3,-9.7,1,...,0.0,-9.1,1.3,0.0,64.1,0.000000,3.0,-9.7,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369317,9006,1,2.6,0.3,0.0,86.6,0.030000,19,2.3,1,...,1.0,4.6,0.7,0.0,76.2,0.260000,18.0,4.1,1.0,1.0
16369318,9006,1,1.4,0.0,0.0,92.1,0.007959,15,1.3,1,...,1.0,2.6,0.3,0.0,86.6,0.030000,19.0,2.3,1.0,1.0
16369319,9006,1,0.8,0.5,0.0,95.3,0.000000,13,0.7,1,...,1.0,1.4,0.0,0.0,92.1,0.007959,15.0,1.3,1.0,1.0
16369320,9006,1,0.4,0.1,0.0,96.2,0.000000,14,0.2,1,...,1.0,0.8,0.5,0.0,95.3,0.000000,13.0,0.7,1.0,1.0
16369321,9006,1,0.0,0.1,0.0,97.1,0.000000,14,0.0,1,...,1.0,0.4,0.1,0.0,96.2,0.000000,14.0,0.2,1.0,1.0

In [ ]:
t

          congestion
0                1.0
1                2.0
2                3.0
3                3.0
4                5.0
...              ...
16369317        15.0
16369318        13.0
16369319        14.0
16369320        14.0
16369321        12.0

[16369322 rows x 1 columns]

In [ ]:
x_train, x_test, t_train, t_test = train_test_split(x, t, test_size=0.3, shuffle=False)

print('x_train shape :', x_train.shape)
print('t_train shape :', t_train.shape)
print('x_test shape :', x_test.shape)
print('t_test shape :', t_test.shape)

x_train shape : (11458525, 22)
t_train shape : (11458525, 1)
x_test shape : (4910797, 22)
t_test shape : (4910797, 1)

In [ ]:
timesteps = 2
feature = 11

x_train = np.array(x_train)
x_train = x_train.reshape(x_train.shape[0], timesteps, feature)

x_test = np.array(x_test)
x_test = x_test.reshape(x_test.shape[0], timesteps, feature)

t_train = np.array(t_train)
t_test = np.array(t_test)

print('reshape 후 x_train shape :', x_train.shape)
print('t_train shape :', t_train.shape)
print('reshape 후 x_test shape :', x_test.shape)
print('t_test shape :', t_test.shape)

reshape 후 x_train shape : (11458525, 2, 11)
t_train shape : (11458525, 1)
reshape 후 x_test shape : (4910797, 2, 11)
t_test shape : (4910797, 1)

In [ ]:
from tensorflow.keras import regularizers
def lstm_model(cell_size=128, learning_rate=0.001):
    timesteps = 2
    feature = 11
    model = Sequential(name='congestion_gru')
    model.add(LSTM(cell_size, input_shape=(timesteps, feature), return_sequences=True,
                  kernel_regularizer=regularizers.l2(0.001)))
    model.add(LSTM(cell_size, kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    model.compile(loss='mse', optimizer=Adam(learning_rate=learning_rate), metrics=[RootMeanSquaredError()])
    return model

In [ ]:
temp_grue = lstm_model()
temp_grue.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "congestion_gru"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 2, 128)         │        71,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 128)            │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 203,393 (794.50 KB)

 Trainable params: 203,393 (794.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import optuna
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import cross_val_score
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from tensorflow.keras import regularizers
#
early_stopping = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

#성능 평가 함수(scoring)로 평균제곱근오차 기본 제공이 아니라 커스텀
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))
rmse_scorer = make_scorer(rmse, greater_is_better=False)

#데이터가 너무 많아 10~20%만 추출하여 하이퍼파라미터 탐색하도록(더 빠르게)
x_train_subset, _, t_train_subset, _ = train_test_split(
    x_train, t_train, train_size=0.1, shuffle=False , random_state=42
)
def objective(trial):
    # Optuna에서 베이지안 방식으로 샘플링할 파라미터 정의
    cell_size = trial.suggest_categorical('cell_size', [128, 248])
    learning_rate = trial.suggest_float('learning_rate', 7e-4, 1e-3, log=True)
    epochs = trial.suggest_int('epochs', 15, 25)
    batch_size = trial.suggest_categorical('batch_size', [64, 128])

    # scikeras로 래핑
    Congestion_LSTM_MODEL = KerasRegressor(
        model=lstm_model,
        cell_size=cell_size,
        learning_rate=learning_rate,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[early_stopping]
    )
    # cross_val_score에서 cv=2와 데이터 직접 전달
    scores = cross_val_score(Congestion_LSTM_MODEL, x_train_subset, t_train_subset, scoring=rmse_scorer, cv=2)
    return -scores.mean()  # minimize(RMSE)

In [ ]:
bayesian_study = optuna.create_study(direction='minimize')

bayesian_study.optimize(objective, n_trials=20)

[I 2025-06-17 07:43:03,892] A new study created in memory with name: no-name-032acb64-2f43-46c9-8730-e63550de7d2b
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 5ms/step - loss: 94.5289 - root_mean_squared_error: 9.5649
Epoch 2/15
  20/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 59.3282 - root_mean_squared_error: 7.6260

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 67.1687 - root_mean_squared_error: 8.1214
Epoch 3/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 62.9345 - root_mean_squared_error: 7.8452
Epoch 4/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 59.9788 - root_mean_squared_error: 7.6432
Epoch 5/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 57.4396 - root_mean_squared_error: 7.4650
Epoch 6/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 56.5398 - root_mean_squared_error: 7.3957
Epoch 7/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 54.9559 - root_mean_squared_error: 7.2791
Epoch 8/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 54.2695 - root_mean_squared_error: 7.2239
Epoch 9/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 53.4176 - root_mean_squared_error: 7.1580
Epoch 10/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 53.9981 - root_mean_squared_error: 7.1908
Epoch 11/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 52.3883 - root_mean_squared_error: 7.0731
Epoch 12/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 52.1636 - root_mean_squared_error: 7.0509
Epoch 13/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 51.3770 - root_mean_squared_error: 6.9884
Epoch 14/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 50.7534 - root_mean_squared_error: 6.9374
Epoch 15/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 50.6791 - root_mean_squared_error: 6.9276
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 13s 1ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 77.1150 - root_mean_squared_error: 8.6418
Epoch 2/15
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 62.8911 - root_mean_squared_error: 7.8461

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 53.6187 - root_mean_squared_error: 7.2399
Epoch 3/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 48.8771 - root_mean_squared_error: 6.8798
Epoch 4/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 46.2424 - root_mean_squared_error: 6.6707
Epoch 5/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 44.4903 - root_mean_squared_error: 6.5292
Epoch 6/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 44.3508 - root_mean_squared_error: 6.5122
Epoch 7/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 42.6931 - root_mean_squared_error: 6.3776
Epoch 8/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 42.3426 - root_mean_squared_error: 6.3454
Epoch 9/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 42.5321 - root_mean_squared_error: 6.3555
Epoch 10/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 41.5907 - root_mean_squared_error: 6.2764
Epoch 11/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 40.6834 - root_mean_squared_error: 6.2007
Epoch 12/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 40.6640 - root_mean_squared_error: 6.1968
Epoch 13/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 40.3010 - root_mean_squared_error: 6.1649
Epoch 14/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 39.8146 - root_mean_squared_error: 6.1214
Epoch 15/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 39.1357 - root_mean_squared_error: 6.0637
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 08:06:41,639] Trial 0 finished with value: 9.768747757509727 and parameters: {'cell_size': 248, 'learning_rate': 0.0009765208680612534, 'epochs': 15, 'batch_size': 64}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 113.0081 - root_mean_squared_error: 10.3713
Epoch 2/18
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 74.3700 - root_mean_squared_error: 8.5683

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 68.4353 - root_mean_squared_error: 8.2295
Epoch 3/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 65.0433 - root_mean_squared_error: 8.0121
Epoch 4/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 63.1217 - root_mean_squared_error: 7.8829
Epoch 5/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 61.0201 - root_mean_squared_error: 7.7393
Epoch 6/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 59.4661 - root_mean_squared_error: 7.6291
Epoch 7/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 58.3737 - root_mean_squared_error: 7.5477
Epoch 8/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 57.0120 - root_mean_squared_error: 7.4478
Epoch 9/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 56.3081 - root_mean_squared_error: 7.3908
Epoch 10/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 55.0899 - root_mean_squared_error: 7.2991
Epoch 11/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 54.4215 - root_mean_squared_error: 7.2447
Epoch 12/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 53.4840 - root_mean_squared_error: 7.1716
Epoch 13/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 52.9930 - root_mean_squared_error: 7.1301
Epoch 14/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 52.6547 - root_mean_squared_error: 7.1000
Epoch 15/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 52.1501 - root_mean_squared_error: 7.0584
Epoch 16/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 51.8288 - root_mean_squared_error: 7.0310
Epoch 17/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 51.2246 - root_mean_squared_error: 6.9839
Epoch 18/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 45s 5ms/step - loss: 51.0573 - root_mean_squared_error: 6.9678
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 13s 1ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 89.8153 - root_mean_squared_error: 9.2619
Epoch 2/18
  20/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 63.0912 - root_mean_squared_error: 7.9044

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 53.3872 - root_mean_squared_error: 7.2664
Epoch 3/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 48.9201 - root_mean_squared_error: 6.9369
Epoch 4/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 45.9504 - root_mean_squared_error: 6.7051
Epoch 5/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 44.0441 - root_mean_squared_error: 6.5476
Epoch 6/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 43.0326 - root_mean_squared_error: 6.4583
Epoch 7/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 41.7612 - root_mean_squared_error: 6.3486
Epoch 8/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 41.1588 - root_mean_squared_error: 6.2909
Epoch 9/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 40.0555 - root_mean_squared_error: 6.1947
Epoch 10/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 39.8241 - root_mean_squared_error: 6.1685
Epoch 11/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 39.1909 - root_mean_squared_error: 6.1097
Epoch 12/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.1468 - root_mean_squared_error: 6.0987
Epoch 13/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 38.5382 - root_mean_squared_error: 6.0413
Epoch 14/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.4959 - root_mean_squared_error: 5.9496
Epoch 15/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 37.5002 - root_mean_squared_error: 5.9444
Epoch 16/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.2523 - root_mean_squared_error: 5.9175
Epoch 17/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 36.5066 - root_mean_squared_error: 5.8495
Epoch 18/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 35.9735 - root_mean_squared_error: 5.7998
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

[I 2025-06-17 08:34:45,046] Trial 1 finished with value: 10.452628596315648 and parameters: {'cell_size': 128, 'learning_rate': 0.0007309417666869617, 'epochs': 18, 'batch_size': 64}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 111.5486 - root_mean_squared_error: 10.3099
Epoch 2/17
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 72.7255 - root_mean_squared_error: 8.4857

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 68.7951 - root_mean_squared_error: 8.2522
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 64.9076 - root_mean_squared_error: 8.0028
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 61.8314 - root_mean_squared_error: 7.7972
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 60.1703 - root_mean_squared_error: 7.6785
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 58.7263 - root_mean_squared_error: 7.5729
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 57.5431 - root_mean_squared_error: 7.4834
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 56.9773 - root_mean_squared_error: 7.4347
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 55.6739 - root_mean_squared_error: 7.3347
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 54.8278 - root_mean_squared_error: 7.2654
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 53.5663 - root_mean_squared_error: 7.1673
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.1284 - root_mean_squared_error: 7.0578
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.6097 - root_mean_squared_error: 7.0136
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.3587 - root_mean_squared_error: 6.9888
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.1303 - root_mean_squared_error: 6.9661
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 50.2432 - root_mean_squared_error: 6.8968
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 6ms/step - loss: 49.8018 - root_mean_squared_error: 6.8607
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step
Epoch 1/17

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 53s 6ms/step - loss: 87.8349 - root_mean_squared_error: 9.1730
Epoch 2/17
  19/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 46.4821 - root_mean_squared_error: 6.7531

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 54.0195 - root_mean_squared_error: 7.3042
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 49.6373 - root_mean_squared_error: 6.9827
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 51s 6ms/step - loss: 46.8236 - root_mean_squared_error: 6.7625
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 52s 6ms/step - loss: 45.0638 - root_mean_squared_error: 6.6186
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 51s 6ms/step - loss: 43.7348 - root_mean_squared_error: 6.5066
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 52s 6ms/step - loss: 42.9702 - root_mean_squared_error: 6.4381
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 52s 6ms/step - loss: 41.9848 - root_mean_squared_error: 6.3531
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 51s 6ms/step - loss: 41.6575 - root_mean_squared_error: 6.3203
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 41.1407 - root_mean_squared_error: 6.2737
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 40.7700 - root_mean_squared_error: 6.2391
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 40.4214 - root_mean_squared_error: 6.2070
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 40.2249 - root_mean_squared_error: 6.1875
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 40.1875 - root_mean_squared_error: 6.1811
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 39.3841 - root_mean_squared_error: 6.1122
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 39.1780 - root_mean_squared_error: 6.0923
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 6ms/step - loss: 38.5955 - root_mean_squared_error: 6.0415
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 09:03:00,561] Trial 2 finished with value: 10.966287894708428 and parameters: {'cell_size': 128, 'learning_rate': 0.0008136160345957509, 'epochs': 17, 'batch_size': 64}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 110.1277 - root_mean_squared_error: 10.2513
Epoch 2/19
  20/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 63.9748 - root_mean_squared_error: 7.9377

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 66.8158 - root_mean_squared_error: 8.1159
Epoch 3/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 63.5563 - root_mean_squared_error: 7.9033
Epoch 4/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 60.1182 - root_mean_squared_error: 7.6718
Epoch 5/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 57.5721 - root_mean_squared_error: 7.4922
Epoch 6/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 56.1436 - root_mean_squared_error: 7.3856
Epoch 7/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 54.8678 - root_mean_squared_error: 7.2883
Epoch 8/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 53.3737 - root_mean_squared_error: 7.1757
Epoch 9/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 52.1940 - root_mean_squared_error: 7.0856
Epoch 10/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 51.1194 - root_mean_squared_error: 7.0014
Epoch 11/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 50.7458 - root_mean_squared_error: 6.9668
Epoch 12/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 49.5013 - root_mean_squared_error: 6.8694
Epoch 13/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 48.9115 - root_mean_squared_error: 6.8199
Epoch 14/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 48.9431 - root_mean_squared_error: 6.8157
Epoch 15/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 48.3077 - root_mean_squared_error: 6.7633
Epoch 16/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 47.4896 - root_mean_squared_error: 6.6979
Epoch 17/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 47.3615 - root_mean_squared_error: 6.6835
Epoch 18/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 47.0629 - root_mean_squared_error: 6.6575
Epoch 19/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 46.6457 - root_mean_squared_error: 6.6229
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step
Epoch 1/19

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 85.3848 - root_mean_squared_error: 9.0494
Epoch 2/19
  19/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 56.0618 - root_mean_squared_error: 7.4265

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 52.9165 - root_mean_squared_error: 7.2175
Epoch 3/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 48.1157 - root_mean_squared_error: 6.8602
Epoch 4/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 44.5867 - root_mean_squared_error: 6.5799
Epoch 5/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 42.8836 - root_mean_squared_error: 6.4348
Epoch 6/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 41.3612 - root_mean_squared_error: 6.3033
Epoch 7/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 40.3865 - root_mean_squared_error: 6.2145
Epoch 8/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 39.7218 - root_mean_squared_error: 6.1510
Epoch 9/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 38.6002 - root_mean_squared_error: 6.0510
Epoch 10/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 37.8590 - root_mean_squared_error: 5.9831
Epoch 11/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 37.1493 - root_mean_squared_error: 5.9177
Epoch 12/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 36.8596 - root_mean_squared_error: 5.8878
Epoch 13/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 36.8688 - root_mean_squared_error: 5.8849
Epoch 14/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 36.2298 - root_mean_squared_error: 5.8275
Epoch 15/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 35.4725 - root_mean_squared_error: 5.7592
Epoch 16/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 35.6189 - root_mean_squared_error: 5.7682
Epoch 17/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 34.5635 - root_mean_squared_error: 5.6736
Epoch 18/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 34.4460 - root_mean_squared_error: 5.6605
Epoch 19/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 34.5086 - root_mean_squared_error: 5.6619
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step

[I 2025-06-17 09:19:21,851] Trial 3 finished with value: 10.408037987241135 and parameters: {'cell_size': 248, 'learning_rate': 0.0008681324286479466, 'epochs': 19, 'batch_size': 128}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 5ms/step - loss: 96.1590 - root_mean_squared_error: 9.6487
Epoch 2/23
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 77.5641 - root_mean_squared_error: 8.7374

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 67.8586 - root_mean_squared_error: 8.1650
Epoch 3/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 64.5052 - root_mean_squared_error: 7.9444
Epoch 4/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 62.4552 - root_mean_squared_error: 7.8033
Epoch 5/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 60.0678 - root_mean_squared_error: 7.6364
Epoch 6/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 58.0879 - root_mean_squared_error: 7.4970
Epoch 7/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 56.5439 - root_mean_squared_error: 7.3862
Epoch 8/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 55.1403 - root_mean_squared_error: 7.2824
Epoch 9/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 54.2763 - root_mean_squared_error: 7.2143
Epoch 10/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 53.4796 - root_mean_squared_error: 7.1526
Epoch 11/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.7166 - root_mean_squared_error: 7.0931
Epoch 12/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 52.3990 - root_mean_squared_error: 7.0660
Epoch 13/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.3140 - root_mean_squared_error: 6.9843
Epoch 14/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.7701 - root_mean_squared_error: 6.9402
Epoch 15/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.5597 - root_mean_squared_error: 6.9194
Epoch 16/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.4380 - root_mean_squared_error: 6.9057
Epoch 17/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.7598 - root_mean_squared_error: 6.8528
Epoch 18/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.5255 - root_mean_squared_error: 6.8323
Epoch 19/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.5209 - root_mean_squared_error: 6.8271
Epoch 20/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.1064 - root_mean_squared_error: 6.7924
Epoch 21/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.9030 - root_mean_squared_error: 6.7746
Epoch 22/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.4181 - root_mean_squared_error: 6.8097
Epoch 23/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.5640 - root_mean_squared_error: 6.7447
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step
Epoch 1/23

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 77.1199 - root_mean_squared_error: 8.6385
Epoch 2/23
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.7121 - root_mean_squared_error: 6.9533

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.6038 - root_mean_squared_error: 7.2433
Epoch 3/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.2248 - root_mean_squared_error: 6.8374
Epoch 4/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 45.7931 - root_mean_squared_error: 6.6337
Epoch 5/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 44.8712 - root_mean_squared_error: 6.5505
Epoch 6/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 44.2801 - root_mean_squared_error: 6.4932
Epoch 7/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.7278 - root_mean_squared_error: 6.3639
Epoch 8/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.2408 - root_mean_squared_error: 6.3175
Epoch 9/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 41.1402 - root_mean_squared_error: 6.2257
Epoch 10/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 40.5598 - root_mean_squared_error: 6.1726
Epoch 11/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 40.2819 - root_mean_squared_error: 6.1433
Epoch 12/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.7786 - root_mean_squared_error: 6.0954
Epoch 13/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.0993 - root_mean_squared_error: 6.0350
Epoch 14/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.2654 - root_mean_squared_error: 6.0445
Epoch 15/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.4109 - root_mean_squared_error: 5.9701
Epoch 16/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.0032 - root_mean_squared_error: 5.9333
Epoch 17/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.5863 - root_mean_squared_error: 5.8949
Epoch 18/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.2230 - root_mean_squared_error: 5.8612
Epoch 19/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.3729 - root_mean_squared_error: 5.7851
Epoch 20/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.9791 - root_mean_squared_error: 5.7484
Epoch 21/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.9470 - root_mean_squared_error: 5.7442
Epoch 22/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.8419 - root_mean_squared_error: 5.7322
Epoch 23/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.6073 - root_mean_squared_error: 5.7086
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

[I 2025-06-17 09:56:23,663] Trial 4 finished with value: 10.133275839225632 and parameters: {'cell_size': 248, 'learning_rate': 0.0009772425742783687, 'epochs': 23, 'batch_size': 64}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 130.7013 - root_mean_squared_error: 11.0880
Epoch 2/19
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 70.0926 - root_mean_squared_error: 8.3341

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 67.3538 - root_mean_squared_error: 8.1687
Epoch 3/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 64.2383 - root_mean_squared_error: 7.9683
Epoch 4/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 61.9409 - root_mean_squared_error: 7.8157
Epoch 5/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.7087 - root_mean_squared_error: 7.6636
Epoch 6/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.5752 - root_mean_squared_error: 7.5148
Epoch 7/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.8219 - root_mean_squared_error: 7.3895
Epoch 8/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.2352 - root_mean_squared_error: 7.3424
Epoch 9/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.1790 - root_mean_squared_error: 7.2637
Epoch 10/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.9098 - root_mean_squared_error: 7.2387
Epoch 11/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.0805 - root_mean_squared_error: 7.1755
Epoch 12/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.3706 - root_mean_squared_error: 7.1206
Epoch 13/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.9837 - root_mean_squared_error: 7.0889
Epoch 14/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.1904 - root_mean_squared_error: 7.0275
Epoch 15/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.6864 - root_mean_squared_error: 6.9868
Epoch 16/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.5954 - root_mean_squared_error: 6.9039
Epoch 17/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.4014 - root_mean_squared_error: 6.8850
Epoch 18/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.0907 - root_mean_squared_error: 6.8578
Epoch 19/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.6677 - root_mean_squared_error: 6.8225
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step
Epoch 1/19

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 100.4862 - root_mean_squared_error: 9.7524
Epoch 2/19
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 53.4054 - root_mean_squared_error: 7.2736

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.6338 - root_mean_squared_error: 7.2884
Epoch 3/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.5584 - root_mean_squared_error: 6.9933
Epoch 4/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.5105 - root_mean_squared_error: 6.7601
Epoch 5/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.1700 - root_mean_squared_error: 6.5731
Epoch 6/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.6599 - root_mean_squared_error: 6.4469
Epoch 7/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.9539 - root_mean_squared_error: 6.3830
Epoch 8/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.9535 - root_mean_squared_error: 6.2970
Epoch 9/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.2639 - root_mean_squared_error: 6.2349
Epoch 10/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.5502 - root_mean_squared_error: 6.1714
Epoch 11/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.0361 - root_mean_squared_error: 6.1239
Epoch 12/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.5647 - root_mean_squared_error: 6.0805
Epoch 13/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.0164 - root_mean_squared_error: 6.0305
Epoch 14/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.4533 - root_mean_squared_error: 5.9802
Epoch 15/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.9203 - root_mean_squared_error: 5.9318
Epoch 16/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.0740 - root_mean_squared_error: 5.9418
Epoch 17/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.5433 - root_mean_squared_error: 5.8945
Epoch 18/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.1310 - root_mean_squared_error: 5.8577
Epoch 19/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.9797 - root_mean_squared_error: 5.8424
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step

[I 2025-06-17 10:11:22,154] Trial 5 finished with value: 10.670674009564788 and parameters: {'cell_size': 128, 'learning_rate': 0.0009195016781710302, 'epochs': 19, 'batch_size': 128}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 126.0710 - root_mean_squared_error: 10.9080
Epoch 2/22
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 77.0905 - root_mean_squared_error: 8.7434

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 68.7973 - root_mean_squared_error: 8.2557
Epoch 3/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 65.8104 - root_mean_squared_error: 8.0654
Epoch 4/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 63.3930 - root_mean_squared_error: 7.9063
Epoch 5/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 61.5175 - root_mean_squared_error: 7.7774
Epoch 6/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 59.4203 - root_mean_squared_error: 7.6312
Epoch 7/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 58.4169 - root_mean_squared_error: 7.5558
Epoch 8/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 57.1210 - root_mean_squared_error: 7.4603
Epoch 9/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.1053 - root_mean_squared_error: 7.3829
Epoch 10/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 54.9898 - root_mean_squared_error: 7.2983
Epoch 11/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.2412 - root_mean_squared_error: 7.2382
Epoch 12/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.4062 - root_mean_squared_error: 7.1723
Epoch 13/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 52.7129 - root_mean_squared_error: 7.1165
Epoch 14/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 52.3546 - root_mean_squared_error: 7.0842
Epoch 15/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.5770 - root_mean_squared_error: 7.0235
Epoch 16/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.1581 - root_mean_squared_error: 6.9880
Epoch 17/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.6283 - root_mean_squared_error: 6.9447
Epoch 18/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 50.4502 - root_mean_squared_error: 6.9273
Epoch 19/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.3719 - root_mean_squared_error: 6.9177
Epoch 20/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.5391 - root_mean_squared_error: 6.8535
Epoch 21/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.6637 - root_mean_squared_error: 6.8596
Epoch 22/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.2697 - root_mean_squared_error: 6.8271
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step
Epoch 1/22

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 98.8333 - root_mean_squared_error: 9.6827
Epoch 2/22
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.4259 - root_mean_squared_error: 7.4038

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.9904 - root_mean_squared_error: 7.3093
Epoch 3/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.6861 - root_mean_squared_error: 6.9942
Epoch 4/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.2639 - root_mean_squared_error: 6.7293
Epoch 5/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.7817 - root_mean_squared_error: 6.5262
Epoch 6/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.4362 - root_mean_squared_error: 6.4098
Epoch 7/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.5369 - root_mean_squared_error: 6.3285
Epoch 8/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.1765 - root_mean_squared_error: 6.2910
Epoch 9/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.5103 - root_mean_squared_error: 6.2288
Epoch 10/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.1585 - root_mean_squared_error: 6.1127
Epoch 11/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.0000 - root_mean_squared_error: 6.0950
Epoch 12/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.3389 - root_mean_squared_error: 6.0363
Epoch 13/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.3407 - root_mean_squared_error: 6.0313
Epoch 14/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.5755 - root_mean_squared_error: 5.9655
Epoch 15/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.1876 - root_mean_squared_error: 5.8463
Epoch 16/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.5302 - root_mean_squared_error: 5.8723
Epoch 17/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.0375 - root_mean_squared_error: 5.8290
Epoch 18/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.5808 - root_mean_squared_error: 5.7881
Epoch 19/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.9796 - root_mean_squared_error: 5.7356
Epoch 20/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.0248 - root_mean_squared_error: 5.7371
Epoch 21/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.7842 - root_mean_squared_error: 5.7133
Epoch 22/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.2000 - root_mean_squared_error: 5.6609
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step

[I 2025-06-17 10:28:56,874] Trial 6 finished with value: 10.608011719614217 and parameters: {'cell_size': 128, 'learning_rate': 0.0009935608101200703, 'epochs': 22, 'batch_size': 128}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 97.2517 - root_mean_squared_error: 9.6945
Epoch 2/23
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 71.9784 - root_mean_squared_error: 8.4247

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.9896 - root_mean_squared_error: 8.1264
Epoch 3/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 63.7218 - root_mean_squared_error: 7.9118
Epoch 4/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 60.6678 - root_mean_squared_error: 7.7027
Epoch 5/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.8032 - root_mean_squared_error: 7.5011
Epoch 6/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 56.2966 - root_mean_squared_error: 7.3882
Epoch 7/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.2300 - root_mean_squared_error: 7.3063
Epoch 8/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 54.5346 - root_mean_squared_error: 7.2493
Epoch 9/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.4494 - root_mean_squared_error: 7.1673
Epoch 10/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.5259 - root_mean_squared_error: 7.0965
Epoch 11/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.7321 - root_mean_squared_error: 7.0346
Epoch 12/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.1559 - root_mean_squared_error: 6.9886
Epoch 13/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.8738 - root_mean_squared_error: 6.9630
Epoch 14/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.3934 - root_mean_squared_error: 6.9235
Epoch 15/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.0148 - root_mean_squared_error: 6.8927
Epoch 16/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.1814 - root_mean_squared_error: 6.9012
Epoch 17/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.6575 - root_mean_squared_error: 6.8602
Epoch 18/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.8669 - root_mean_squared_error: 6.7997
Epoch 19/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.1009 - root_mean_squared_error: 6.8145
Epoch 20/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.5391 - root_mean_squared_error: 6.7716
Epoch 21/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.4116 - root_mean_squared_error: 6.7590
Epoch 22/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.6968 - root_mean_squared_error: 6.7037
Epoch 23/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.6840 - root_mean_squared_error: 6.6992
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step
Epoch 1/23

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 79.5800 - root_mean_squared_error: 8.7693
Epoch 2/23
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 74.8219 - root_mean_squared_error: 8.5600

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.3304 - root_mean_squared_error: 7.1556
Epoch 3/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.2951 - root_mean_squared_error: 6.6900
Epoch 4/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 44.4904 - root_mean_squared_error: 6.5319
Epoch 5/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.2837 - root_mean_squared_error: 6.3451
Epoch 6/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 41.0851 - root_mean_squared_error: 6.2392
Epoch 7/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 40.1449 - root_mean_squared_error: 6.1526
Epoch 8/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.5840 - root_mean_squared_error: 6.0995
Epoch 9/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.6311 - root_mean_squared_error: 6.0141
Epoch 10/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.3673 - root_mean_squared_error: 5.9875
Epoch 11/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.7934 - root_mean_squared_error: 5.9343
Epoch 12/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.8848 - root_mean_squared_error: 5.8520
Epoch 13/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.6993 - root_mean_squared_error: 5.8323
Epoch 14/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.4263 - root_mean_squared_error: 5.8059
Epoch 15/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.6399 - root_mean_squared_error: 5.7363
Epoch 16/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.3578 - root_mean_squared_error: 5.7102
Epoch 17/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.5984 - root_mean_squared_error: 5.6399
Epoch 18/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.3488 - root_mean_squared_error: 5.6150
Epoch 19/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 33.8772 - root_mean_squared_error: 5.5710
Epoch 20/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 33.7699 - root_mean_squared_error: 5.5593
Epoch 21/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 33.3195 - root_mean_squared_error: 5.5163
Epoch 22/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 33.4246 - root_mean_squared_error: 5.5237
Epoch 23/23
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 32.6893 - root_mean_squared_error: 5.4559
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 11:05:42,658] Trial 7 finished with value: 9.888314913436886 and parameters: {'cell_size': 248, 'learning_rate': 0.0007668386702036629, 'epochs': 23, 'batch_size': 64}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 106.0000 - root_mean_squared_error: 10.0859
Epoch 2/15
  20/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 73.6859 - root_mean_squared_error: 8.5280

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 67.3234 - root_mean_squared_error: 8.1447
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 63.5095 - root_mean_squared_error: 7.8946
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 60.5877 - root_mean_squared_error: 7.6942
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 58.3792 - root_mean_squared_error: 7.5366
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 56.9311 - root_mean_squared_error: 7.4284
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 54.9085 - root_mean_squared_error: 7.2798
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 53.8476 - root_mean_squared_error: 7.1965
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 53.1665 - root_mean_squared_error: 7.1400
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.9292 - root_mean_squared_error: 7.0455
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.2489 - root_mean_squared_error: 6.9892
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.9714 - root_mean_squared_error: 6.8909
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.1933 - root_mean_squared_error: 6.8264
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.1954 - root_mean_squared_error: 6.8201
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 48.4573 - root_mean_squared_error: 6.7596
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 85.9148 - root_mean_squared_error: 9.0666
Epoch 2/15
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.5824 - root_mean_squared_error: 7.4637

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 52.5395 - root_mean_squared_error: 7.1855
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 47.1330 - root_mean_squared_error: 6.7756
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 44.0290 - root_mean_squared_error: 6.5230
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 42.4770 - root_mean_squared_error: 6.3863
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 40.7566 - root_mean_squared_error: 6.2374
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 39.4936 - root_mean_squared_error: 6.1243
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 38.7863 - root_mean_squared_error: 6.0581
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 37.7210 - root_mean_squared_error: 5.9607
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 36.7795 - root_mean_squared_error: 5.8753
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 36.4316 - root_mean_squared_error: 5.8392
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 35.7273 - root_mean_squared_error: 5.7752
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 35.0277 - root_mean_squared_error: 5.7124
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 34.4787 - root_mean_squared_error: 5.6630
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 34.3925 - root_mean_squared_error: 5.6515
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step

[I 2025-06-17 11:17:58,872] Trial 8 finished with value: 11.102911398414198 and parameters: {'cell_size': 248, 'learning_rate': 0.0009686685197873896, 'epochs': 15, 'batch_size': 128}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 130.1560 - root_mean_squared_error: 11.0674
Epoch 2/25
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 72.2826 - root_mean_squared_error: 8.4674

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 68.6281 - root_mean_squared_error: 8.2475
Epoch 3/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 65.3334 - root_mean_squared_error: 8.0382
Epoch 4/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 62.7587 - root_mean_squared_error: 7.8686
Epoch 5/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 59.7552 - root_mean_squared_error: 7.6665
Epoch 6/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 58.1614 - root_mean_squared_error: 7.5533
Epoch 7/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 57.0976 - root_mean_squared_error: 7.4752
Epoch 8/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 55.6587 - root_mean_squared_error: 7.3715
Epoch 9/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 54.5030 - root_mean_squared_error: 7.2855
Epoch 10/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 53.8347 - root_mean_squared_error: 7.2332
Epoch 11/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 53.5348 - root_mean_squared_error: 7.2064
Epoch 12/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 52.8227 - root_mean_squared_error: 7.1519
Epoch 13/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.9103 - root_mean_squared_error: 7.0832
Epoch 14/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.9460 - root_mean_squared_error: 7.0813
Epoch 15/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.0903 - root_mean_squared_error: 7.0159
Epoch 16/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 50.3716 - root_mean_squared_error: 6.9596
Epoch 17/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 50.4646 - root_mean_squared_error: 6.9617
Epoch 18/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 50.2401 - root_mean_squared_error: 6.9412
Epoch 19/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.6849 - root_mean_squared_error: 6.8970
Epoch 20/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.3915 - root_mean_squared_error: 6.8717
Epoch 21/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 48.7736 - root_mean_squared_error: 6.8227
Epoch 22/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 49.1188 - root_mean_squared_error: 6.8445
Epoch 23/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 48.5459 - root_mean_squared_error: 6.7993
Epoch 24/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 48.2099 - root_mean_squared_error: 6.7706
Epoch 25/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 48.0498 - root_mean_squared_error: 6.7552
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step
Epoch 1/25

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 103.3154 - root_mean_squared_error: 9.8680
Epoch 2/25
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 57.1726 - root_mean_squared_error: 7.5242

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.0734 - root_mean_squared_error: 7.2495
Epoch 3/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.6256 - root_mean_squared_error: 6.9978
Epoch 4/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.9967 - root_mean_squared_error: 6.7964
Epoch 5/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.8683 - root_mean_squared_error: 6.6273
Epoch 6/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.5752 - root_mean_squared_error: 6.5195
Epoch 7/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.2499 - root_mean_squared_error: 6.4078
Epoch 8/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.2552 - root_mean_squared_error: 6.3223
Epoch 9/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.7352 - root_mean_squared_error: 6.2738
Epoch 10/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.0772 - root_mean_squared_error: 6.2145
Epoch 11/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.3163 - root_mean_squared_error: 6.1472
Epoch 12/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.8851 - root_mean_squared_error: 6.1063
Epoch 13/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.2752 - root_mean_squared_error: 6.0511
Epoch 14/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.4566 - root_mean_squared_error: 6.0618
Epoch 15/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.7755 - root_mean_squared_error: 6.0009
Epoch 16/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.5955 - root_mean_squared_error: 5.9818
Epoch 17/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.8470 - root_mean_squared_error: 5.9148
Epoch 18/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.0082 - root_mean_squared_error: 5.9238
Epoch 19/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.1539 - root_mean_squared_error: 5.8472
Epoch 20/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.9033 - root_mean_squared_error: 5.8224
Epoch 21/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.8782 - root_mean_squared_error: 5.8171
Epoch 22/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.7266 - root_mean_squared_error: 5.8014
Epoch 23/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.5384 - root_mean_squared_error: 5.7821
Epoch 24/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.8530 - root_mean_squared_error: 5.7198
Epoch 25/25
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.8283 - root_mean_squared_error: 5.7150
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step

[I 2025-06-17 11:37:51,166] Trial 9 finished with value: 10.451206702065072 and parameters: {'cell_size': 128, 'learning_rate': 0.000879139556249241, 'epochs': 25, 'batch_size': 128}. Best is trial 0 with value: 9.768747757509727.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 97.5292 - root_mean_squared_error: 9.7047
Epoch 2/15
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 68.1909 - root_mean_squared_error: 8.2010

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.7055 - root_mean_squared_error: 8.1103
Epoch 3/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 63.3711 - root_mean_squared_error: 7.8919
Epoch 4/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.9538 - root_mean_squared_error: 7.6590
Epoch 5/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.3970 - root_mean_squared_error: 7.4771
Epoch 6/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.8631 - root_mean_squared_error: 7.3634
Epoch 7/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 54.7290 - root_mean_squared_error: 7.2773
Epoch 8/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.8077 - root_mean_squared_error: 7.2062
Epoch 9/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.3859 - root_mean_squared_error: 7.0995
Epoch 10/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 52.1717 - root_mean_squared_error: 7.0778
Epoch 11/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.3611 - root_mean_squared_error: 7.0155
Epoch 12/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.6157 - root_mean_squared_error: 6.9553
Epoch 13/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.8588 - root_mean_squared_error: 6.8950
Epoch 14/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.3152 - root_mean_squared_error: 6.8511
Epoch 15/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.0197 - root_mean_squared_error: 6.8259
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 78.5536 - root_mean_squared_error: 8.7196
Epoch 2/15
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.9479 - root_mean_squared_error: 7.4141

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.5519 - root_mean_squared_error: 7.1827
Epoch 3/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.1831 - root_mean_squared_error: 6.7706
Epoch 4/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 43.9173 - root_mean_squared_error: 6.5020
Epoch 5/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 41.3981 - root_mean_squared_error: 6.2893
Epoch 6/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.8830 - root_mean_squared_error: 6.1551
Epoch 7/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.8789 - root_mean_squared_error: 6.0627
Epoch 8/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.4014 - root_mean_squared_error: 6.0173
Epoch 9/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.4058 - root_mean_squared_error: 5.9275
Epoch 10/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.3389 - root_mean_squared_error: 5.9161
Epoch 11/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.2716 - root_mean_squared_error: 5.8221
Epoch 12/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.2523 - root_mean_squared_error: 5.8153
Epoch 13/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.1805 - root_mean_squared_error: 5.7195
Epoch 14/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.9378 - root_mean_squared_error: 5.6952
Epoch 15/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.4435 - root_mean_squared_error: 5.6496
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

[I 2025-06-17 12:02:06,969] Trial 10 finished with value: 9.611005217868936 and parameters: {'cell_size': 248, 'learning_rate': 0.0007008445791406316, 'epochs': 15, 'batch_size': 64}. Best is trial 10 with value: 9.611005217868936.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 96.9418 - root_mean_squared_error: 9.6697
Epoch 2/15
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 64.2912 - root_mean_squared_error: 7.9542

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.6111 - root_mean_squared_error: 8.1014
Epoch 3/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 63.6098 - root_mean_squared_error: 7.9023
Epoch 4/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 61.2809 - root_mean_squared_error: 7.7393
Epoch 5/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.4478 - root_mean_squared_error: 7.4752
Epoch 6/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 56.3914 - root_mean_squared_error: 7.3940
Epoch 7/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 54.6995 - root_mean_squared_error: 7.2702
Epoch 8/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.5764 - root_mean_squared_error: 7.1856
Epoch 9/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.2718 - root_mean_squared_error: 7.0891
Epoch 10/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.0137 - root_mean_squared_error: 7.0666
Epoch 11/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.0193 - root_mean_squared_error: 6.9920
Epoch 12/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.3998 - root_mean_squared_error: 6.9432
Epoch 13/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.5247 - root_mean_squared_error: 6.8776
Epoch 14/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.1470 - root_mean_squared_error: 6.8472
Epoch 15/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.7216 - root_mean_squared_error: 6.8137
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 51s 5ms/step - loss: 79.5129 - root_mean_squared_error: 8.7534
Epoch 2/15
  19/8952 ━━━━━━━━━━━━━━━━━━━━ 52s 6ms/step - loss: 49.7364 - root_mean_squared_error: 6.9736

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 52.0908 - root_mean_squared_error: 7.1443
Epoch 3/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 45.6090 - root_mean_squared_error: 6.6419
Epoch 4/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 42.9580 - root_mean_squared_error: 6.4151
Epoch 5/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 41.8268 - root_mean_squared_error: 6.3099
Epoch 6/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 40.1134 - root_mean_squared_error: 6.1597
Epoch 7/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.2522 - root_mean_squared_error: 6.0797
Epoch 8/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.2587 - root_mean_squared_error: 5.9898
Epoch 9/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 37.1802 - root_mean_squared_error: 5.8917
Epoch 10/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.6129 - root_mean_squared_error: 5.8393
Epoch 11/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.9021 - root_mean_squared_error: 5.7750
Epoch 12/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.7019 - root_mean_squared_error: 5.7543
Epoch 13/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.9376 - root_mean_squared_error: 5.6849
Epoch 14/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.7172 - root_mean_squared_error: 5.6620
Epoch 15/15
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.2561 - root_mean_squared_error: 5.6181
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 12:26:34,672] Trial 11 finished with value: 9.896991307141366 and parameters: {'cell_size': 248, 'learning_rate': 0.0007038629280814283, 'epochs': 15, 'batch_size': 64}. Best is trial 10 with value: 9.611005217868936.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 5ms/step - loss: 95.9436 - root_mean_squared_error: 9.6332
Epoch 2/16
  20/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 74.5280 - root_mean_squared_error: 8.5690

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 66.5738 - root_mean_squared_error: 8.0943
Epoch 3/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 62.5165 - root_mean_squared_error: 7.8271
Epoch 4/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 59.1664 - root_mean_squared_error: 7.5999
Epoch 5/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 57.0782 - root_mean_squared_error: 7.4528
Epoch 6/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 55.4536 - root_mean_squared_error: 7.3342
Epoch 7/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 53.9662 - root_mean_squared_error: 7.2240
Epoch 8/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 52.8123 - root_mean_squared_error: 7.1364
Epoch 9/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.9260 - root_mean_squared_error: 7.0685
Epoch 10/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.1612 - root_mean_squared_error: 7.0088
Epoch 11/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.5809 - root_mean_squared_error: 6.9623
Epoch 12/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.4286 - root_mean_squared_error: 6.9460
Epoch 13/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.5033 - root_mean_squared_error: 6.8735
Epoch 14/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.3202 - root_mean_squared_error: 6.8567
Epoch 15/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.8812 - root_mean_squared_error: 6.8210
Epoch 16/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.1762 - root_mean_squared_error: 6.7651
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step
Epoch 1/16

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 79.3797 - root_mean_squared_error: 8.7533
Epoch 2/16
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.0898 - root_mean_squared_error: 7.4841

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.5093 - root_mean_squared_error: 7.1711
Epoch 3/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.1520 - root_mean_squared_error: 6.7601
Epoch 4/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 45.1296 - root_mean_squared_error: 6.5863
Epoch 5/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 43.4101 - root_mean_squared_error: 6.4367
Epoch 6/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 41.9297 - root_mean_squared_error: 6.3082
Epoch 7/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 40.5650 - root_mean_squared_error: 6.1890
Epoch 8/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.9474 - root_mean_squared_error: 6.0488
Epoch 9/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.8128 - root_mean_squared_error: 6.0272
Epoch 10/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.4980 - root_mean_squared_error: 5.9102
Epoch 11/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.8964 - root_mean_squared_error: 5.8540
Epoch 12/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.1962 - root_mean_squared_error: 5.7882
Epoch 13/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.8852 - root_mean_squared_error: 5.7567
Epoch 14/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.1778 - root_mean_squared_error: 5.6918
Epoch 15/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.9535 - root_mean_squared_error: 5.6692
Epoch 16/16
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.3189 - root_mean_squared_error: 5.6101
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

[I 2025-06-17 12:52:36,980] Trial 12 finished with value: 9.206345962526303 and parameters: {'cell_size': 248, 'learning_rate': 0.0007978553984451847, 'epochs': 16, 'batch_size': 64}. Best is trial 12 with value: 9.206345962526303.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 96.5370 - root_mean_squared_error: 9.6644
Epoch 2/17
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.1187 - root_mean_squared_error: 8.0646

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 67.1637 - root_mean_squared_error: 8.1319
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 62.9464 - root_mean_squared_error: 7.8558
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.8172 - root_mean_squared_error: 7.6428
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.5712 - root_mean_squared_error: 7.4850
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 56.6670 - root_mean_squared_error: 7.4158
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 55.2904 - root_mean_squared_error: 7.3166
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 54.4829 - root_mean_squared_error: 7.2554
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.8840 - root_mean_squared_error: 7.2086
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.1920 - root_mean_squared_error: 7.1542
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.0475 - root_mean_squared_error: 7.0688
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.4179 - root_mean_squared_error: 7.0190
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.8292 - root_mean_squared_error: 6.9728
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.0615 - root_mean_squared_error: 6.9137
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.3671 - root_mean_squared_error: 6.8597
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.0898 - root_mean_squared_error: 6.8357
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.4270 - root_mean_squared_error: 6.7823
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/17

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 78.3796 - root_mean_squared_error: 8.7051
Epoch 2/17
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.7047 - root_mean_squared_error: 7.1673

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.6482 - root_mean_squared_error: 7.1790
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.9397 - root_mean_squared_error: 6.8177
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 45.1027 - root_mean_squared_error: 6.5833
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.7316 - root_mean_squared_error: 6.3883
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 41.5351 - root_mean_squared_error: 6.2834
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 40.5309 - root_mean_squared_error: 6.1936
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.1579 - root_mean_squared_error: 6.0737
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.3610 - root_mean_squared_error: 6.0012
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.5091 - root_mean_squared_error: 5.9239
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.0702 - root_mean_squared_error: 5.8819
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.6053 - root_mean_squared_error: 5.8378
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.0622 - root_mean_squared_error: 5.7860
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.6410 - root_mean_squared_error: 5.7470
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.7370 - root_mean_squared_error: 5.6637
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.9727 - root_mean_squared_error: 5.6808
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.3563 - root_mean_squared_error: 5.6219
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

[I 2025-06-17 13:20:04,425] Trial 13 finished with value: 9.910877114593205 and parameters: {'cell_size': 248, 'learning_rate': 0.0007898394278979929, 'epochs': 17, 'batch_size': 64}. Best is trial 12 with value: 9.206345962526303.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 97.0966 - root_mean_squared_error: 9.6935
Epoch 2/17
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 67.1166 - root_mean_squared_error: 8.1257

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.7136 - root_mean_squared_error: 8.1078
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 61.7398 - root_mean_squared_error: 7.7832
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.0415 - root_mean_squared_error: 7.5942
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.1617 - root_mean_squared_error: 7.4567
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.1253 - root_mean_squared_error: 7.3098
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.6975 - root_mean_squared_error: 7.2021
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.9441 - root_mean_squared_error: 7.1417
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.7041 - root_mean_squared_error: 7.0475
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.7936 - root_mean_squared_error: 6.9753
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.7968 - root_mean_squared_error: 6.8965
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.7078 - root_mean_squared_error: 6.8091
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.7208 - root_mean_squared_error: 6.7296
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.1030 - root_mean_squared_error: 6.6771
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.4684 - root_mean_squared_error: 6.6248
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 45.7079 - root_mean_squared_error: 6.5642
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 45.5274 - root_mean_squared_error: 6.5463
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/17

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 5ms/step - loss: 78.3684 - root_mean_squared_error: 8.7103
Epoch 2/17
  20/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 52.1717 - root_mean_squared_error: 7.1543

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.8788 - root_mean_squared_error: 7.1267
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 46.4323 - root_mean_squared_error: 6.7040
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 44.2035 - root_mean_squared_error: 6.5132
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 42.0371 - root_mean_squared_error: 6.3273
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 40.5411 - root_mean_squared_error: 6.1937
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.3582 - root_mean_squared_error: 6.0855
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.7159 - root_mean_squared_error: 6.0229
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 37.4612 - root_mean_squared_error: 5.9106
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.9226 - root_mean_squared_error: 5.8584
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.0464 - root_mean_squared_error: 5.7775
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.3341 - root_mean_squared_error: 5.7124
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.8634 - root_mean_squared_error: 5.6689
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.3499 - root_mean_squared_error: 5.6204
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 34.0247 - root_mean_squared_error: 5.5892
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.0114 - root_mean_squared_error: 5.5854
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 33.1697 - root_mean_squared_error: 5.5062
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 13:47:46,112] Trial 14 finished with value: 9.152462919591748 and parameters: {'cell_size': 248, 'learning_rate': 0.0007522202309933531, 'epochs': 17, 'batch_size': 64}. Best is trial 14 with value: 9.152462919591748.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 5ms/step - loss: 98.3164 - root_mean_squared_error: 9.7330
Epoch 2/17
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 76.3045 - root_mean_squared_error: 8.6711

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 67.4812 - root_mean_squared_error: 8.1493
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 63.2424 - root_mean_squared_error: 7.8717
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.8150 - root_mean_squared_error: 7.6371
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.2859 - root_mean_squared_error: 7.4584
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 55.7595 - root_mean_squared_error: 7.3464
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 54.2855 - root_mean_squared_error: 7.2381
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 53.1596 - root_mean_squared_error: 7.1526
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.7240 - root_mean_squared_error: 7.0436
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.0347 - root_mean_squared_error: 6.9889
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.4920 - root_mean_squared_error: 6.9432
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.3963 - root_mean_squared_error: 6.8589
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.8939 - root_mean_squared_error: 6.8158
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.8368 - root_mean_squared_error: 6.7317
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.6001 - root_mean_squared_error: 6.7075
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.0700 - root_mean_squared_error: 6.6630
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.8043 - root_mean_squared_error: 6.6388
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/17

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 79.6461 - root_mean_squared_error: 8.7651
Epoch 2/17
  20/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.8920 - root_mean_squared_error: 7.1399

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.5693 - root_mean_squared_error: 7.1820
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.8369 - root_mean_squared_error: 6.7470
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 44.1151 - root_mean_squared_error: 6.5196
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.1909 - root_mean_squared_error: 6.3547
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 40.6832 - root_mean_squared_error: 6.2238
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.6029 - root_mean_squared_error: 6.1267
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.7714 - root_mean_squared_error: 6.0505
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.0248 - root_mean_squared_error: 5.9812
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.9469 - root_mean_squared_error: 5.8861
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.4243 - root_mean_squared_error: 5.8372
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.8801 - root_mean_squared_error: 5.7876
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.1702 - root_mean_squared_error: 5.7222
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.9926 - root_mean_squared_error: 5.7047
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.6119 - root_mean_squared_error: 5.6684
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.3292 - root_mean_squared_error: 5.6408
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 33.9095 - root_mean_squared_error: 5.6012
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 14:15:14,223] Trial 15 finished with value: 10.18379461998255 and parameters: {'cell_size': 248, 'learning_rate': 0.0007534738579847233, 'epochs': 17, 'batch_size': 64}. Best is trial 14 with value: 9.152462919591748.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 96.5784 - root_mean_squared_error: 9.6574
Epoch 2/21
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 86.7515 - root_mean_squared_error: 9.2386

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 67.4893 - root_mean_squared_error: 8.1497
Epoch 3/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 64.1393 - root_mean_squared_error: 7.9293
Epoch 4/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 61.1672 - root_mean_squared_error: 7.7289
Epoch 5/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.2358 - root_mean_squared_error: 7.5925
Epoch 6/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 57.1038 - root_mean_squared_error: 7.4414
Epoch 7/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.2714 - root_mean_squared_error: 7.3057
Epoch 8/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 54.3763 - root_mean_squared_error: 7.2346
Epoch 9/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.3099 - root_mean_squared_error: 7.1513
Epoch 10/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.8973 - root_mean_squared_error: 7.1141
Epoch 11/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.2012 - root_mean_squared_error: 7.0573
Epoch 12/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.0406 - root_mean_squared_error: 6.9677
Epoch 13/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.8911 - root_mean_squared_error: 6.9506
Epoch 14/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.2891 - root_mean_squared_error: 6.8998
Epoch 15/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.9717 - root_mean_squared_error: 6.8703
Epoch 16/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.1257 - root_mean_squared_error: 6.8032
Epoch 17/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.8252 - root_mean_squared_error: 6.7762
Epoch 18/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.9573 - root_mean_squared_error: 6.7821
Epoch 19/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.1598 - root_mean_squared_error: 6.7196
Epoch 20/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.4549 - root_mean_squared_error: 6.6630
Epoch 21/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.0831 - root_mean_squared_error: 6.6316
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/21

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 78.3120 - root_mean_squared_error: 8.6967
Epoch 2/21
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.9656 - root_mean_squared_error: 7.1388

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.8082 - root_mean_squared_error: 7.1929
Epoch 3/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.1131 - root_mean_squared_error: 6.8337
Epoch 4/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 45.6566 - root_mean_squared_error: 6.6313
Epoch 5/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 43.8630 - root_mean_squared_error: 6.4808
Epoch 6/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 42.1543 - root_mean_squared_error: 6.3387
Epoch 7/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.0076 - root_mean_squared_error: 6.3208
Epoch 8/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 40.6901 - root_mean_squared_error: 6.2106
Epoch 9/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.6952 - root_mean_squared_error: 6.1260
Epoch 10/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.3800 - root_mean_squared_error: 6.0973
Epoch 11/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.5698 - root_mean_squared_error: 6.0271
Epoch 12/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.4161 - root_mean_squared_error: 6.0127
Epoch 13/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.1098 - root_mean_squared_error: 5.9834
Epoch 14/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.8902 - root_mean_squared_error: 5.8785
Epoch 15/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.7533 - root_mean_squared_error: 5.8631
Epoch 16/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.4555 - root_mean_squared_error: 5.8364
Epoch 17/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.4411 - root_mean_squared_error: 5.8343
Epoch 18/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.7058 - root_mean_squared_error: 5.7690
Epoch 19/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.2905 - root_mean_squared_error: 5.7309
Epoch 20/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.8954 - root_mean_squared_error: 5.6935
Epoch 21/21
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.6101 - root_mean_squared_error: 5.6689
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 14:49:03,114] Trial 16 finished with value: 9.555328160072683 and parameters: {'cell_size': 248, 'learning_rate': 0.0008346361067302213, 'epochs': 21, 'batch_size': 64}. Best is trial 14 with value: 9.152462919591748.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 50s 5ms/step - loss: 97.7356 - root_mean_squared_error: 9.7089
Epoch 2/17
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 74.4823 - root_mean_squared_error: 8.5689

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.6107 - root_mean_squared_error: 8.0973
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 62.1039 - root_mean_squared_error: 7.7989
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.2341 - root_mean_squared_error: 7.5974
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 56.7793 - root_mean_squared_error: 7.4197
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.2817 - root_mean_squared_error: 7.3070
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 53.6154 - root_mean_squared_error: 7.1820
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.3488 - root_mean_squared_error: 7.0855
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.9981 - root_mean_squared_error: 6.9801
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.2468 - root_mean_squared_error: 6.9184
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.6842 - root_mean_squared_error: 6.8712
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.8792 - root_mean_squared_error: 6.8048
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.2004 - root_mean_squared_error: 6.7484
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 47.4170 - root_mean_squared_error: 6.6840
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.8444 - root_mean_squared_error: 6.6354
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.4894 - root_mean_squared_error: 6.6039
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.1299 - root_mean_squared_error: 6.5720
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/17

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 51s 5ms/step - loss: 78.2846 - root_mean_squared_error: 8.7092
Epoch 2/17
  19/8952 ━━━━━━━━━━━━━━━━━━━━ 52s 6ms/step - loss: 52.1825 - root_mean_squared_error: 7.1552

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 52.6351 - root_mean_squared_error: 7.1831
Epoch 3/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.7635 - root_mean_squared_error: 6.8125
Epoch 4/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 44.6740 - root_mean_squared_error: 6.5611
Epoch 5/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 42.7422 - root_mean_squared_error: 6.3963
Epoch 6/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 41.5004 - root_mean_squared_error: 6.2828
Epoch 7/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.8499 - root_mean_squared_error: 6.1388
Epoch 8/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 38.3709 - root_mean_squared_error: 6.0069
Epoch 9/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 37.9049 - root_mean_squared_error: 5.9594
Epoch 10/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 37.0669 - root_mean_squared_error: 5.8822
Epoch 11/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.3639 - root_mean_squared_error: 5.8168
Epoch 12/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.7556 - root_mean_squared_error: 5.7615
Epoch 13/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.1863 - root_mean_squared_error: 5.7087
Epoch 14/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.3952 - root_mean_squared_error: 5.6356
Epoch 15/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.1195 - root_mean_squared_error: 5.6070
Epoch 16/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 6ms/step - loss: 34.2360 - root_mean_squared_error: 5.6156
Epoch 17/17
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 33.8587 - root_mean_squared_error: 5.5780
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 15:16:52,618] Trial 17 finished with value: 10.573684536478453 and parameters: {'cell_size': 248, 'learning_rate': 0.000791736601928287, 'epochs': 17, 'batch_size': 64}. Best is trial 14 with value: 9.152462919591748.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 51s 5ms/step - loss: 97.5061 - root_mean_squared_error: 9.7013
Epoch 2/20
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 65.5788 - root_mean_squared_error: 8.0287

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 66.7625 - root_mean_squared_error: 8.1044
Epoch 3/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 62.3940 - root_mean_squared_error: 7.8159
Epoch 4/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 58.9447 - root_mean_squared_error: 7.5801
Epoch 5/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 57.2514 - root_mean_squared_error: 7.4559
Epoch 6/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 55.6415 - root_mean_squared_error: 7.3374
Epoch 7/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 54.2701 - root_mean_squared_error: 7.2341
Epoch 8/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 52.2868 - root_mean_squared_error: 7.0884
Epoch 9/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 51.8424 - root_mean_squared_error: 7.0511
Epoch 10/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.6257 - root_mean_squared_error: 6.9581
Epoch 11/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 50.2903 - root_mean_squared_error: 6.9292
Epoch 12/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 49.3828 - root_mean_squared_error: 6.8602
Epoch 13/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.7600 - root_mean_squared_error: 6.8104
Epoch 14/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.3632 - root_mean_squared_error: 6.7782
Epoch 15/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 48.2152 - root_mean_squared_error: 6.7646
Epoch 16/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.4189 - root_mean_squared_error: 6.7043
Epoch 17/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.3418 - root_mean_squared_error: 6.6960
Epoch 18/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 46.8373 - root_mean_squared_error: 6.6557
Epoch 19/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 46.3929 - root_mean_squared_error: 6.6189
Epoch 20/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 46.4558 - root_mean_squared_error: 6.6200
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step
Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 78.8427 - root_mean_squared_error: 8.7279
Epoch 2/20
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 54.0613 - root_mean_squared_error: 7.2754

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.5554 - root_mean_squared_error: 7.1759
Epoch 3/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 47.4109 - root_mean_squared_error: 6.7823
Epoch 4/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 44.9034 - root_mean_squared_error: 6.5728
Epoch 5/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.7836 - root_mean_squared_error: 6.3924
Epoch 6/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 41.5846 - root_mean_squared_error: 6.2839
Epoch 7/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 40.5637 - root_mean_squared_error: 6.1919
Epoch 8/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.6777 - root_mean_squared_error: 6.1135
Epoch 9/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 39.0498 - root_mean_squared_error: 6.0560
Epoch 10/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 38.2958 - root_mean_squared_error: 5.9878
Epoch 11/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 37.3255 - root_mean_squared_error: 5.9005
Epoch 12/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 37.1038 - root_mean_squared_error: 5.8798
Epoch 13/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 36.5722 - root_mean_squared_error: 5.8334
Epoch 14/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.7137 - root_mean_squared_error: 5.7573
Epoch 15/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 35.3355 - root_mean_squared_error: 5.7208
Epoch 16/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 35.2255 - root_mean_squared_error: 5.7083
Epoch 17/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.5314 - root_mean_squared_error: 5.6452
Epoch 18/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 34.1845 - root_mean_squared_error: 5.6131
Epoch 19/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 33.6976 - root_mean_squared_error: 5.5665
Epoch 20/20
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 33.3112 - root_mean_squared_error: 5.5305
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step

[I 2025-06-17 15:49:33,035] Trial 18 finished with value: 10.28148709734911 and parameters: {'cell_size': 248, 'learning_rate': 0.0007446603534154894, 'epochs': 20, 'batch_size': 64}. Best is trial 14 with value: 9.152462919591748.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 97.0006 - root_mean_squared_error: 9.6671
Epoch 2/18
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 46s 5ms/step - loss: 69.5409 - root_mean_squared_error: 8.2726

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 66.8789 - root_mean_squared_error: 8.1139
Epoch 3/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 62.3116 - root_mean_squared_error: 7.8160
Epoch 4/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 59.3110 - root_mean_squared_error: 7.6076
Epoch 5/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 48s 5ms/step - loss: 57.0900 - root_mean_squared_error: 7.4463
Epoch 6/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 55.1617 - root_mean_squared_error: 7.3044
Epoch 7/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.8759 - root_mean_squared_error: 7.2067
Epoch 8/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 53.2986 - root_mean_squared_error: 7.1588
Epoch 9/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.2621 - root_mean_squared_error: 7.0797
Epoch 10/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.6088 - root_mean_squared_error: 7.0273
Epoch 11/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.8373 - root_mean_squared_error: 6.9677
Epoch 12/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.5467 - root_mean_squared_error: 6.9423
Epoch 13/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 50.0108 - root_mean_squared_error: 6.8998
Epoch 14/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.3552 - root_mean_squared_error: 6.8478
Epoch 15/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 49.0269 - root_mean_squared_error: 6.8195
Epoch 16/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.4179 - root_mean_squared_error: 6.7706
Epoch 17/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.5840 - root_mean_squared_error: 6.7805
Epoch 18/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 48.0109 - root_mean_squared_error: 6.7362
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 49s 5ms/step - loss: 79.9224 - root_mean_squared_error: 8.7784
Epoch 2/18
  21/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 51.6976 - root_mean_squared_error: 7.1103

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 52.6436 - root_mean_squared_error: 7.1844
Epoch 3/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 46.4097 - root_mean_squared_error: 6.7086
Epoch 4/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 43.4640 - root_mean_squared_error: 6.4621
Epoch 5/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 42.0232 - root_mean_squared_error: 6.3352
Epoch 6/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 40.8604 - root_mean_squared_error: 6.2316
Epoch 7/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.7797 - root_mean_squared_error: 6.1357
Epoch 8/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 39.1765 - root_mean_squared_error: 6.0785
Epoch 9/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 38.8142 - root_mean_squared_error: 6.0422
Epoch 10/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.6620 - root_mean_squared_error: 5.9419
Epoch 11/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 37.1988 - root_mean_squared_error: 5.8984
Epoch 12/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.6472 - root_mean_squared_error: 5.8482
Epoch 13/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 36.6158 - root_mean_squared_error: 5.8417
Epoch 14/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.7877 - root_mean_squared_error: 5.7677
Epoch 15/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.8590 - root_mean_squared_error: 5.7710
Epoch 16/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 35.3978 - root_mean_squared_error: 5.7279
Epoch 17/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.9378 - root_mean_squared_error: 5.6851
Epoch 18/18
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 47s 5ms/step - loss: 34.9673 - root_mean_squared_error: 5.6858
8952/8952 ━━━━━━━━━━━━━━━━━━━━ 14s 1ms/step

[I 2025-06-17 16:18:25,956] Trial 19 finished with value: 9.971667937449244 and parameters: {'cell_size': 248, 'learning_rate': 0.0007769946632877385, 'epochs': 18, 'batch_size': 64}. Best is trial 14 with value: 9.152462919591748.

In [ ]:
print("Random Search에서의 최고의 하이퍼파라미터 조합 : ", bayesian_study.best_trial)

Random Search에서의 최고의 하이퍼파라미터 조합 :  FrozenTrial(number=14, state=1, values=[9.152462919591748], datetime_start=datetime.datetime(2025, 6, 17, 13, 20, 4, 426085), datetime_complete=datetime.datetime(2025, 6, 17, 13, 47, 46, 112029), params={'cell_size': 248, 'learning_rate': 0.0007522202309933531, 'epochs': 17, 'batch_size': 64}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'cell_size': CategoricalDistribution(choices=(128, 248)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0007, step=None), 'epochs': IntDistribution(high=25, log=False, low=15, step=1), 'batch_size': CategoricalDistribution(choices=(64, 128))}, trial_id=14, value=None)

In [ ]:
best_params = bayesian_study.best_params
final_lstm_model = lstm_model(
    cell_size=best_params['cell_size'],
    learning_rate=best_params['learning_rate']
)
history = final_lstm_model.fit(
    x_train, t_train,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    callbacks=[early_stopping]
)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 934s 5ms/step - loss: 109.0184 - root_mean_squared_error: 10.3589
Epoch 2/17

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

179040/179040 ━━━━━━━━━━━━━━━━━━━━ 931s 5ms/step - loss: 96.9379 - root_mean_squared_error: 9.7411
Epoch 3/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 933s 5ms/step - loss: 93.0988 - root_mean_squared_error: 9.5248
Epoch 4/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 934s 5ms/step - loss: 91.1919 - root_mean_squared_error: 9.4149
Epoch 5/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 934s 5ms/step - loss: 89.8192 - root_mean_squared_error: 9.3293
Epoch 6/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 935s 5ms/step - loss: 88.1216 - root_mean_squared_error: 9.2251
Epoch 7/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 935s 5ms/step - loss: 86.6404 - root_mean_squared_error: 9.1325
Epoch 8/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 936s 5ms/step - loss: 85.8941 - root_mean_squared_error: 9.0752
Epoch 9/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 936s 5ms/step - loss: 85.2114 - root_mean_squared_error: 9.0289
Epoch 10/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 936s 5ms/step - loss: 84.6078 - root_mean_squared_error: 8.9873
Epoch 11/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 937s 5ms/step - loss: 83.5643 - root_mean_squared_error: 8.9243
Epoch 12/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 938s 5ms/step - loss: 82.9111 - root_mean_squared_error: 8.8800
Epoch 13/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 937s 5ms/step - loss: 82.1820 - root_mean_squared_error: 8.8317
Epoch 14/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 939s 5ms/step - loss: 81.0026 - root_mean_squared_error: 8.7600
Epoch 15/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 938s 5ms/step - loss: 80.5777 - root_mean_squared_error: 8.7281
Epoch 16/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 938s 5ms/step - loss: 80.6552 - root_mean_squared_error: 8.7330
Epoch 17/17
179040/179040 ━━━━━━━━━━━━━━━━━━━━ 938s 5ms/step - loss: 80.1470 - root_mean_squared_error: 8.7038

In [ ]:
pred = final_lstm_model.predict(x_test)

for i in range(0, 20):
    print('혼잡도 예측 : ', round(pred[i][0], 2), '/정답 :', round(t_test[i][0], 2))

153463/153463 ━━━━━━━━━━━━━━━━━━━━ 234s 2ms/step
혼잡도 예측 :  17.65 /정답 : 18.0
혼잡도 예측 :  26.86 /정답 : 15.0
혼잡도 예측 :  23.67 /정답 : 15.0
혼잡도 예측 :  21.72 /정답 : 17.0
혼잡도 예측 :  27.0 /정답 : 24.0
혼잡도 예측 :  28.43 /정답 : 22.0
혼잡도 예측 :  28.86 /정답 : 28.0
혼잡도 예측 :  27.88 /정답 : 18.0
혼잡도 예측 :  26.68 /정답 : 13.0
혼잡도 예측 :  10.85 /정답 : 13.0
혼잡도 예측 :  11.2 /정답 : 12.0
혼잡도 예측 :  9.13 /정답 : 7.0
혼잡도 예측 :  4.56 /정답 : 4.0
혼잡도 예측 :  7.17 /정답 : 0.0
혼잡도 예측 :  7.22 /정답 : 12.0
혼잡도 예측 :  13.36 /정답 : 12.0
혼잡도 예측 :  10.5 /정답 : 26.0
혼잡도 예측 :  28.18 /정답 : 25.0
혼잡도 예측 :  27.19 /정답 : 16.0
혼잡도 예측 :  24.68 /정답 : 15.0

In [ ]:
loss, rmse = final_lstm_model.evaluate(x_test, t_test, verbose=1)
print('test loss(MSE) :', round(loss, 6))
print('test RMSE :', round(rmse, 2))

153463/153463 ━━━━━━━━━━━━━━━━━━━━ 398s 3ms/step - loss: 102.1327 - root_mean_squared_error: 9.7997
test loss(MSE) : 123.534897
test RMSE : 10.91

In [ ]:
final_lstm_model.save("final_lstm_model.keras")

In [ ]:
#'cell_size': 248, 'learning_rate': 0.0007522202309933531, 'epochs': 17, 'batch_size': 64