# Import

In [1]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.11/dist-packages (4.4.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (1.16.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)

In [2]:
!pip install scikit-learn==1.1.3

Collecting scikit-learn==1.1.3
  Using cached scikit_learn-1.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (2.0.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (1.15.3)
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.1.3) (3.6.0)
Using cached scikit_learn-1.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32.0 MB)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.7.0
    Uninstalling scikit-learn-1.7.0:
      Successfully uninstalled scikit-learn-1.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikeras 0.13.0 requires scikit-learn>=1.4.2, but you have scikit-learn 1.1.3 which is incompatible.
imbalanced-learn 0.13.0 requires scikit-learn<2,>=1.3.2, but you have scikit-learn 1.1.3 which is incompatible.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, but you have scikit-learn 1.1.3 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.1.3 which is incompatible.
Successfully installed scikit-learn-1.1.3

In [3]:
!pip install scikeras

Requirement already satisfied: scikeras in /usr/local/lib/python3.11/dist-packages (0.13.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Collecting scikit-learn>=1.4.2 (from scikeras)
  Using cached scikit_learn-1.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (17 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.16.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Using cached scikit_learn-1.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.1.3
    Uninstalling scikit-learn-1.1.3:
      Successfully uninstalled scikit-learn-1.1.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.0 which is incompatible.
Successfully installed scikit-learn-1.7.0

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import numpy as np
import tensorflow as tf
import pandas as pd
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GRU, Dropout, Input, LayerNormalization, Bidirectional
from tensorflow.keras.losses import mse
from tensorflow.keras.metrics import RootMeanSquaredError, MeanSquaredError
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping
from sklearn.metrics import make_scorer, mean_squared_error
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler

# 원본 데이터 전처리

In [6]:
# 3개년 데이터 로드 (인덱스 자동추가 제외)
origin_2021 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_subway21.csv', index_col=0)
origin_2022 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_subway22.csv', index_col=0)
origin_2023 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_subway23.csv', index_col=0)

In [7]:
# 칼럼명 변경
origin_2021 = origin_2021.rename(columns={
    'train_subway21.tm': 'time',
    'train_subway21.line': 'line',
    'train_subway21.station_number': 'station_number',
    'train_subway21.station_name': 'station_name',
    'train_subway21.direction': 'direction',
    'train_subway21.stn': 'AWS_num',
    'train_subway21.ta': 'temp',
    'train_subway21.wd': 'wind_direction',
    'train_subway21.ws': 'wind_speed',
    'train_subway21.rn_day': 'rn_day',
    'train_subway21.rn_hr1': 'rn_hr',
    'train_subway21.hm': 'humidity',
    'train_subway21.si': 'solar',
    'train_subway21.ta_chi': 'feel_temp',
    'train_subway21.congestion': 'congestion'
})

origin_2022 = origin_2022.rename(columns={
    'train_subway22.tm': 'time',
    'train_subway22.line': 'line',
    'train_subway22.station_number': 'station_number',
    'train_subway22.station_name': 'station_name',
    'train_subway22.direction': 'direction',
    'train_subway22.stn': 'AWS_num',
    'train_subway22.ta': 'temp',
    'train_subway22.wd': 'wind_direction',
    'train_subway22.ws': 'wind_speed',
    'train_subway22.rn_day': 'rn_day',
    'train_subway22.rn_hr1': 'rn_hr',
    'train_subway22.hm': 'humidity',
    'train_subway22.si': 'solar',
    'train_subway22.ta_chi': 'feel_temp',
    'train_subway22.congestion': 'congestion'
})

origin_2023 = origin_2023.rename(columns={
    'train_subway23.tm': 'time',
    'train_subway23.line': 'line',
    'train_subway23.station_number': 'station_number',
    'train_subway23.station_name': 'station_name',
    'train_subway23.direction': 'direction',
    'train_subway23.stn': 'AWS_num',
    'train_subway23.ta': 'temp',
    'train_subway23.wd': 'wind_direction',
    'train_subway23.ws': 'wind_speed',
    'train_subway23.rn_day': 'rn_day',
    'train_subway23.rn_hr1': 'rn_hr',
    'train_subway23.hm': 'humidity',
    'train_subway23.si': 'solar',
    'train_subway23.ta_chi': 'feel_temp',
    'train_subway23.congestion': 'congestion'
})

In [8]:
# origin dataframe 통합
origin_all = pd.concat([origin_2021, origin_2022, origin_2023], ignore_index=True)
origin_all

,time,line,station_number,station_name,direction,AWS_num,temp,wind_direction,wind_speed,rn_day,rn_hr,humidity,solar,feel_temp,congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,-99.0,-99.0,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,-99.0,-99.0,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,-99.0,-99.0,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,-99.0,-99.0,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,-99.0,-99.0,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,7.0,0.0,83.1,-99.0,0.0,18
16369320,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,7.0,0.0,84.7,-99.0,-0.6,17
16369321,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,7.0,0.0,85.1,-99.0,-1.1,21
16369322,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,7.0,0.0,85.6,-99.0,-1.3,18
16369323,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,7.0,0.0,85.6,-99.0,-1.9,22

In [9]:
# 결측값 → NaN
sentinels = [-99, -99.9, -999.0]
origin_all = origin_all.replace(sentinels, np.nan)

In [10]:
#이상치 처
def find_iqr_outliers(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return (series < lower) | (series > upper)

num_cols = ['temp', 'wind_direction', 'wind_speed', 'rn_day', 'rn_hr', 'humidity', 'solar', 'feel_temp']

for col in num_cols:
    outlier_mask = find_iqr_outliers(origin_all[col])
    origin_all.loc[outlier_mask, col] = np.nan  # 이상치만 NaN 처리

In [11]:
# 결측치 확인
print('결측치 처리 전 결측치 개수')
print(origin_all.isnull().sum())

결측치 처리 전 결측치 개수
time                    0
line                    0
station_number          0
station_name            0
direction               0
AWS_num                 0
temp               216672
wind_direction     230786
wind_speed         714650
rn_day            3241523
rn_hr             1293576
humidity           844594
solar             6064242
feel_temp            1076
congestion              0
dtype: int64

In [12]:
df=origin_all.copy()

In [13]:
df['time'] = pd.to_datetime(df['time'], format='%Y%m%d%H')
df['month'] = df['time'].dt.month
df['hour'] = df['time'].dt.hour

# 2. 겨울/여름 마스크 (벡터화)
winter_mask = df['month'].isin([12, 1, 2])
summer_mask = df['month'].isin([6, 7, 8])
remain = df['month'].isin([3,4,5, 9, 10, 11])
# 3. 밤시간 (벡터화)
df['is_night'] = (
    (winter_mask & ((df['hour'] >= 20) | (df['hour'] < 5))) |
    (summer_mask & ((df['hour'] >= 22) | (df['hour'] < 5))) |
    (remain & ((df['hour'] >= 21) | (df['hour'] < 5)))
)
df.loc[df['is_night'] & df['solar'].isnull(), 'solar'] = int(0)

# 임시 컬럼 제거
df.drop(['month', 'hour', 'is_night'], axis=1, inplace=True)

In [14]:
df = df.sort_values(['AWS_num', 'time']).reset_index(drop=True)

In [15]:
target_cols = ['temp', 'wind_direction', 'wind_speed', 'rn_day', 'rn_hr', 'humidity', 'solar', 'feel_temp']
specific_cols = ['wind_direction', 'rn_day', 'rn_hr']
linear_cols = ['temp', 'wind_speed','humidity', 'solar', 'feel_temp']
# 0단계: 동일 관측소그룹별 specific_cols을 시간순으로 bfill/ffill
print('0단계 시작')
for col in specific_cols:
    df[col] = (
        df.groupby('AWS_num')[col]
        .apply(lambda x: x.bfill().ffill())  # 각 그룹에서만 보간
        .reset_index(drop=True)
    )
print(df.isnull().sum())
print('----------------------------------')

#1단계 :동일 관측소그룹별 linear_cols을 시간순으로 선형보간
print('1단계 시작')
for col in linear_cols:
    df[col] = (
        df
        .sort_values(['AWS_num', 'time'])  # 그룹 내 정렬!
        .groupby('AWS_num')[col]
        .apply(lambda x: x.interpolate(method='linear'))  # 각 그룹에서만 보간
        .reset_index(drop=True)
    )
print(df.isnull().sum())
print('----------------------------------')

print('2단계 시작')
for col in linear_cols:
    # 1) 그룹 내 중앙값으로 채우기
    df[col] = (
        df.groupby('AWS_num')[col]
        .apply(lambda x: x.fillna(x.median()))
        .reset_index(drop=True)
    )
    # 2) 그래도 남으면 전체 중앙값
    df[col] = df[col].fillna(df[col].median())
print(df.isnull().sum())
print('----------------------------------')

0단계 시작
time                    0
line                    0
station_number          0
station_name            0
direction               0
AWS_num                 0
temp               216672
wind_direction          0
wind_speed         714650
rn_day                  0
rn_hr                   0
humidity           844594
solar             2220357
feel_temp            1076
congestion              0
dtype: int64
----------------------------------
1단계 시작
time                   0
line                   0
station_number         0
station_name           0
direction              0
AWS_num                0
temp                4634
wind_direction         0
wind_speed          4636
rn_day                 0
rn_hr                  0
humidity          633392
solar                  0
feel_temp              0
congestion             0
dtype: int64
----------------------------------
2단계 시작
time              0
line              0
station_number    0
station_name      0
direction         0
AWS_num           0
temp              0
wind_direction    0
wind_speed        0
rn_day            0
rn_hr             0
humidity          0
solar             0
feel_temp         0
congestion        0
dtype: int64
----------------------------------

In [16]:
# 상/하행 레이블 정의
direction_map = {'상선': 0, '하선': 1, '내선': 2, '외선':3}

# 체감온도 구간 레이블 정의
bins = [-float('inf'), -10, 5, 20, 28, float('inf')]
labels = ["0", "1", "2", "3", "4"]

# 임시 DataFrame temp_df 정의
temp_df = df.copy()

# direction을 숫자 레이블로 변환
temp_df['direction'] = temp_df['direction'].map(direction_map)

# 체감온도 단계 파생변수 추가
temp_df['feel_stage'] = pd.cut(temp_df['feel_temp'], bins=bins, labels=labels).astype(int)

In [17]:
holidays = [
    # 2021
    '20210101','20210211','20210212','20210213','20210301',
    '20210505','20210519','20210606','20210815','20210920',
    '20210921','20210922','20211003','20211009','20211225',
    # 2022
    '20220101','20220131','20220201','20220202','20220301',
    '20220309','20220505','20220508','20220601','20220606',
    '20220815','20220909','20220910','20220911','20220912',
    '20221003','20221009','20221010','20221225',
    # 2023
    '20230101','20230121','20230122','20230123','20230124',
    '20230301','20230505','20230527','20230529','20230606',
    '20230815','20230928','20230929','20230930','20231002',
    '20231003','20231009','20231225'
]
# 공휴일 리스트를 set으로 변환하여 조회 속도 향상
holidays_set = set(holidays)

# 2. 'is_holiday' 컬럼 초기화 (기본값 0: 평일)
temp_df['is_holiday'] = 0

# 3. 주말(토/일) 확인하여 1로 설정
# .dt.dayofweek는 요일을 숫자로 반환합니다 (월=0, 화=1, ..., 토=5, 일=6)
is_weekend = (temp_df['time'].dt.dayofweek >= 5)
temp_df.loc[is_weekend, 'is_holiday'] = 1

# 4. 공휴일 확인하여 1로 설정 (주말과 겹치더라도 1로 유지됨)
# .dt.strftime('%Y%m%d')로 날짜 부분만 YYYYMMDD 문자열로 변환하여 공휴일 리스트와 비교
is_in_holidays = temp_df['time'].dt.strftime('%Y%m%d').isin(holidays_set)
temp_df.loc[is_in_holidays, 'is_holiday'] = 1

In [18]:
temp_df = temp_df.sort_values(['station_number', 'AWS_num','direction','time']).reset_index(drop=True)
temp_df

,time,line,station_number,station_name,direction,AWS_num,temp,wind_direction,wind_speed,rn_day,rn_hr,humidity,solar,feel_temp,congestion,feel_stage,is_holiday
0,2021-01-01 00:00:00,1,150,서울역,0,419,-9.6,291.1,3.3,0.0,0.0,64.1,0.000000,-12.6,0,0,1
1,2021-01-01 01:00:00,1,150,서울역,0,419,-9.7,284.6,2.0,0.0,0.0,64.1,0.000000,-9.8,0,1,1
2,2021-01-01 05:00:00,1,150,서울역,0,419,-9.3,124.7,2.4,0.0,0.0,64.1,0.000000,-10.3,1,0,1
3,2021-01-01 06:00:00,1,150,서울역,0,419,-9.3,126.2,1.7,0.0,0.0,64.1,0.000000,-10.1,2,0,1
4,2021-01-01 07:00:00,1,150,서울역,0,419,-9.1,145.7,1.3,0.0,0.0,64.1,0.000000,-9.7,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023-12-31 19:00:00,6,9006,응암S,1,400,1.4,0.0,0.0,0.0,0.0,92.1,0.007959,1.3,15,1,1
16369320,2023-12-31 20:00:00,6,9006,응암S,1,400,0.8,308.8,0.5,0.0,0.0,95.3,0.000000,0.7,13,1,1
16369321,2023-12-31 21:00:00,6,9006,응암S,1,400,0.4,320.6,0.1,0.0,0.0,96.2,0.000000,0.2,14,1,1
16369322,2023-12-31 22:00:00,6,9006,응암S,1,400,0.0,117.6,0.1,0.0,0.0,97.1,0.000000,0.0,14,1,1
16369323,2023-12-31 23:00:00,6,9006,응암S,1,400,-0.2,0.4,0.2,0.0,0.0,97.6,0.000000,-0.4,12,1,1

In [19]:
# 필요한 칼럼만 추출
selected_cols = [
    'time',
    'station_number',
    'direction',
    'temp',
    'wind_speed',
    'rn_hr',
    'humidity',
    'solar',
    'congestion',
    'feel_temp',
    'feel_stage',
    'is_holiday'
]

# temp_df에서 필요한 컬럼만 train_data DataFrame에 저장
train_data = temp_df[selected_cols].copy()

# station_number, direction, time 순으로 정렬
train_data = train_data.sort_values(
    by=['station_number', 'direction', 'time']
).reset_index(drop=True)

# time 제거
train_data = train_data.iloc[:, 1:]

# 완성
train_data

,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_temp,feel_stage,is_holiday
0,150,0,-9.6,3.3,0.0,64.1,0.000000,0,-12.6,0,1
1,150,0,-9.7,2.0,0.0,64.1,0.000000,0,-9.8,1,1
2,150,0,-9.3,2.4,0.0,64.1,0.000000,1,-10.3,0,1
3,150,0,-9.3,1.7,0.0,64.1,0.000000,2,-10.1,0,1
4,150,0,-9.1,1.3,0.0,64.1,0.000000,3,-9.7,1,1
...,...,...,...,...,...,...,...,...,...,...,...
16369319,9006,1,1.4,0.0,0.0,92.1,0.007959,15,1.3,1,1
16369320,9006,1,0.8,0.5,0.0,95.3,0.000000,13,0.7,1,1
16369321,9006,1,0.4,0.1,0.0,96.2,0.000000,14,0.2,1,1
16369322,9006,1,0.0,0.1,0.0,97.1,0.000000,14,0.0,1,1
16369323,9006,1,-0.2,0.2,0.0,97.6,0.000000,12,-0.4,1,1

## 슬라이딩 윈도우

In [20]:
def extract_inputoutput_shift(df, lookback_time=2, predict_time=1):
    # 1) 과거 시점별 피처 생성
    feat_dfs = []
    for t in range(lookback_time):
        tmp = df.shift(t)
        feat_dfs.append(tmp)
    X = pd.concat(feat_dfs, axis=1)

    # 2) 예측 대상(타깃) 생성
    y = df[['congestion']].shift(-predict_time)

    # 3) NaN 제거 및 인덱스 리셋
    valid_idx = X.dropna().index.intersection(y.dropna().index)
    X = X.loc[valid_idx].reset_index(drop=True)
    y = y.loc[valid_idx].reset_index(drop=True)

    print("X, Y 데이터 분류 완료!")
    return X, y

In [21]:
x, t = extract_inputoutput_shift(train_data)
x

X, Y 데이터 분류 완료!

,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_temp,feel_stage,...,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_temp,feel_stage,is_holiday
0,150,0,-9.7,2.0,0.0,64.1,0.000000,0,-9.8,1,...,0.0,-9.6,3.3,0.0,64.1,0.000000,0.0,-12.6,0.0,1.0
1,150,0,-9.3,2.4,0.0,64.1,0.000000,1,-10.3,0,...,0.0,-9.7,2.0,0.0,64.1,0.000000,0.0,-9.8,1.0,1.0
2,150,0,-9.3,1.7,0.0,64.1,0.000000,2,-10.1,0,...,0.0,-9.3,2.4,0.0,64.1,0.000000,1.0,-10.3,0.0,1.0
3,150,0,-9.1,1.3,0.0,64.1,0.000000,3,-9.7,1,...,0.0,-9.3,1.7,0.0,64.1,0.000000,2.0,-10.1,0.0,1.0
4,150,0,-8.5,0.6,0.0,64.1,0.000000,3,-9.7,1,...,0.0,-9.1,1.3,0.0,64.1,0.000000,3.0,-9.7,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369317,9006,1,2.6,0.3,0.0,86.6,0.030000,19,2.3,1,...,1.0,4.6,0.7,0.0,76.2,0.260000,18.0,4.1,1.0,1.0
16369318,9006,1,1.4,0.0,0.0,92.1,0.007959,15,1.3,1,...,1.0,2.6,0.3,0.0,86.6,0.030000,19.0,2.3,1.0,1.0
16369319,9006,1,0.8,0.5,0.0,95.3,0.000000,13,0.7,1,...,1.0,1.4,0.0,0.0,92.1,0.007959,15.0,1.3,1.0,1.0
16369320,9006,1,0.4,0.1,0.0,96.2,0.000000,14,0.2,1,...,1.0,0.8,0.5,0.0,95.3,0.000000,13.0,0.7,1.0,1.0
16369321,9006,1,0.0,0.1,0.0,97.1,0.000000,14,0.0,1,...,1.0,0.4,0.1,0.0,96.2,0.000000,14.0,0.2,1.0,1.0

In [22]:
t

          congestion
0                1.0
1                2.0
2                3.0
3                3.0
4                5.0
...              ...
16369317        15.0
16369318        13.0
16369319        14.0
16369320        14.0
16369321        12.0

[16369322 rows x 1 columns]

In [23]:
x_train, x_test, t_train, t_test = train_test_split(x, t, test_size=0.3, shuffle=False)

print('x_train shape :', x_train.shape)
print('t_train shape :', t_train.shape)
print('x_test shape :', x_test.shape)
print('t_test shape :', t_test.shape)

x_train shape : (11458525, 22)
t_train shape : (11458525, 1)
x_test shape : (4910797, 22)
t_test shape : (4910797, 1)

In [24]:
timesteps = 2
feature = 11

x_train = np.array(x_train)
x_train = x_train.reshape(x_train.shape[0], timesteps, feature)

x_test = np.array(x_test)
x_test = x_test.reshape(x_test.shape[0], timesteps, feature)

t_train = np.array(t_train)
t_test = np.array(t_test)

print('reshape 후 x_train shape :', x_train.shape)
print('t_train shape :', t_train.shape)
print('reshape 후 x_test shape :', x_test.shape)
print('t_test shape :', t_test.shape)

reshape 후 x_train shape : (11458525, 2, 11)
t_train shape : (11458525, 1)
reshape 후 x_test shape : (4910797, 2, 11)
t_test shape : (4910797, 1)

In [25]:
from tensorflow.keras import regularizers
def gru_model(cell_size=128, learning_rate=0.001):
    timesteps = 2
    feature = 10
    model = Sequential(name='congestion_gru')
    model.add(GRU(cell_size, input_shape=(timesteps, feature), return_sequences=True,
                  kernel_regularizer=regularizers.l2(0.001)))
    model.add(GRU(cell_size, kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    model.compile(loss='mse', optimizer=Adam(learning_rate=learning_rate), metrics=[RootMeanSquaredError()])
    return model

In [26]:
temp_grue = gru_model()
temp_grue.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "congestion_gru"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru (GRU)                       │ (None, 2, 128)         │        53,760 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 128)            │        99,072 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 152,961 (597.50 KB)

 Trainable params: 152,961 (597.50 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
import optuna
from scikeras.wrappers import KerasRegressor
from sklearn.model_selection import cross_val_score
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from tensorflow.keras import regularizers
#
early_stopping = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

#성능 평가 함수(scoring)로 평균제곱근오차 기본 제공이 아니라 커스텀
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))
rmse_scorer = make_scorer(rmse, greater_is_better=False)

#데이터가 너무 많아 10~20%만 추출하여 하이퍼파라미터 탐색하도록(더 빠르게)
x_train_subset, _, t_train_subset, _ = train_test_split(
    x_train, t_train, train_size=0.1, shuffle=False , random_state=42
)
def objective(trial):
    # Optuna에서 베이지안 방식으로 샘플링할 파라미터 정의
    cell_size = trial.suggest_categorical('cell_size', [128, 248])
    learning_rate = trial.suggest_float('learning_rate', 5e-4, 1e-3, log=True)
    epochs = trial.suggest_int('epochs', 15, 25)
    batch_size = trial.suggest_categorical('batch_size', [128, 256])

    # scikeras로 래핑
    Congestion_Gru_MODEL = KerasRegressor(
        model=gru_model,
        cell_size=cell_size,
        learning_rate=learning_rate,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[early_stopping]
    )
    # cross_val_score에서 cv=2와 데이터 직접 전달
    scores = cross_val_score(Congestion_Gru_MODEL, x_train_subset, t_train_subset, scoring=rmse_scorer, cv=2)
    return -scores.mean()  # minimize(RMSE)

In [28]:
bayesian_study = optuna.create_study(direction='minimize')

bayesian_study.optimize(objective, n_trials=20)

[I 2025-06-16 23:32:08,385] A new study created in memory with name: no-name-dbce7efa-10c2-45a6-a77e-99bd6904bb5c
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 103.6231 - root_mean_squared_error: 10.0024
Epoch 2/21
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 74.0487 - root_mean_squared_error: 8.5638

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 66.5529 - root_mean_squared_error: 8.1155
Epoch 3/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 63.7367 - root_mean_squared_error: 7.9311
Epoch 4/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 60.1863 - root_mean_squared_error: 7.6925
Epoch 5/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 56.2682 - root_mean_squared_error: 7.4184
Epoch 6/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 54.6367 - root_mean_squared_error: 7.2918
Epoch 7/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 52.2961 - root_mean_squared_error: 7.1153
Epoch 8/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 50.5493 - root_mean_squared_error: 6.9784
Epoch 9/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 50.3934 - root_mean_squared_error: 6.9555
Epoch 10/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 49.0872 - root_mean_squared_error: 6.8509
Epoch 11/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 48.3956 - root_mean_squared_error: 6.7913
Epoch 12/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 47.9133 - root_mean_squared_error: 6.7487
Epoch 13/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.9114 - root_mean_squared_error: 6.6681
Epoch 14/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.4837 - root_mean_squared_error: 6.6307
Epoch 15/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.2389 - root_mean_squared_error: 6.6075
Epoch 16/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 45.9556 - root_mean_squared_error: 6.5819
Epoch 17/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 45.5192 - root_mean_squared_error: 6.5442
Epoch 18/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 45.3295 - root_mean_squared_error: 6.5257
Epoch 19/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 44.9435 - root_mean_squared_error: 6.4927
Epoch 20/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 44.1129 - root_mean_squared_error: 6.4256
Epoch 21/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 44.3528 - root_mean_squared_error: 6.4415
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/21

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 89.6497 - root_mean_squared_error: 9.3069
Epoch 2/21
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 51.2881 - root_mean_squared_error: 7.1109

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 55.6158 - root_mean_squared_error: 7.4106
Epoch 3/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 51.0761 - root_mean_squared_error: 7.0806
Epoch 4/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 44.2348 - root_mean_squared_error: 6.5659
Epoch 5/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 41.9238 - root_mean_squared_error: 6.3747
Epoch 6/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 40.3105 - root_mean_squared_error: 6.2338
Epoch 7/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.1590 - root_mean_squared_error: 6.1305
Epoch 8/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 37.5139 - root_mean_squared_error: 5.9850
Epoch 9/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 38.3098 - root_mean_squared_error: 6.0378
Epoch 10/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.5494 - root_mean_squared_error: 5.8831
Epoch 11/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 35.7424 - root_mean_squared_error: 5.8057
Epoch 12/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 35.2633 - root_mean_squared_error: 5.7555
Epoch 13/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.7601 - root_mean_squared_error: 5.6192
Epoch 14/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.8736 - root_mean_squared_error: 5.6227
Epoch 15/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.4189 - root_mean_squared_error: 5.4863
Epoch 16/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.1404 - root_mean_squared_error: 5.4549
Epoch 17/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 31.8532 - root_mean_squared_error: 5.4227
Epoch 18/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 31.5365 - root_mean_squared_error: 5.3896
Epoch 19/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 30.8227 - root_mean_squared_error: 5.3191
Epoch 20/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 30.4918 - root_mean_squared_error: 5.2845
Epoch 21/21
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 30.7348 - root_mean_squared_error: 5.3027
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-16 23:47:58,165] Trial 0 finished with value: 15.706587756362275 and parameters: {'cell_size': 248, 'learning_rate': 0.0007616442835706245, 'epochs': 21, 'batch_size': 128}. Best is trial 0 with value: 15.706587756362275.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 171.1690 - root_mean_squared_error: 12.7076
Epoch 2/22
  22/2238 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 73.5997 - root_mean_squared_error: 8.5613

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 70.5787 - root_mean_squared_error: 8.3828
Epoch 3/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 66.1554 - root_mean_squared_error: 8.1109
Epoch 4/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 63.4322 - root_mean_squared_error: 7.9381
Epoch 5/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 61.1153 - root_mean_squared_error: 7.7874
Epoch 6/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58.7491 - root_mean_squared_error: 7.6303
Epoch 7/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.5958 - root_mean_squared_error: 7.4843
Epoch 8/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 55.8333 - root_mean_squared_error: 7.4295
Epoch 9/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 54.5980 - root_mean_squared_error: 7.3425
Epoch 10/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.5064 - root_mean_squared_error: 7.2641
Epoch 11/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.8893 - root_mean_squared_error: 7.2178
Epoch 12/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 51.9446 - root_mean_squared_error: 7.1480
Epoch 13/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.6678 - root_mean_squared_error: 7.0541
Epoch 14/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.9586 - root_mean_squared_error: 6.9998
Epoch 15/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.0122 - root_mean_squared_error: 6.9279
Epoch 16/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.5858 - root_mean_squared_error: 6.8929
Epoch 17/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.9439 - root_mean_squared_error: 6.9147
Epoch 18/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.6580 - root_mean_squared_error: 6.8172
Epoch 19/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 46.9538 - root_mean_squared_error: 6.7614
Epoch 20/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 45.9932 - root_mean_squared_error: 6.6862
Epoch 21/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 45.4214 - root_mean_squared_error: 6.6395
Epoch 22/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 46.1664 - root_mean_squared_error: 6.6915
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/22

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 125.1028 - root_mean_squared_error: 10.9036
Epoch 2/22
  22/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 61.0808 - root_mean_squared_error: 7.7955

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 57.5619 - root_mean_squared_error: 7.5650
Epoch 3/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.6851 - root_mean_squared_error: 6.9469
Epoch 4/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 44.8632 - root_mean_squared_error: 6.6599
Epoch 5/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42.8593 - root_mean_squared_error: 6.5022
Epoch 6/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41.6204 - root_mean_squared_error: 6.4007
Epoch 7/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.3722 - root_mean_squared_error: 6.2975
Epoch 8/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.5198 - root_mean_squared_error: 6.2244
Epoch 9/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 38.1711 - root_mean_squared_error: 6.1105
Epoch 10/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.3712 - root_mean_squared_error: 6.0398
Epoch 11/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.5597 - root_mean_squared_error: 5.9676
Epoch 12/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.1355 - root_mean_squared_error: 5.9272
Epoch 13/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.6197 - root_mean_squared_error: 5.8792
Epoch 14/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.7816 - root_mean_squared_error: 5.8031
Epoch 15/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 33.9487 - root_mean_squared_error: 5.7266
Epoch 16/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 33.8955 - root_mean_squared_error: 5.7181
Epoch 17/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 33.3569 - root_mean_squared_error: 5.6670
Epoch 18/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 32.9405 - root_mean_squared_error: 5.6265
Epoch 19/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 32.4338 - root_mean_squared_error: 5.5777
Epoch 20/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 31.6911 - root_mean_squared_error: 5.5072
Epoch 21/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 31.6249 - root_mean_squared_error: 5.4977
Epoch 22/22
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 31.4006 - root_mean_squared_error: 5.4740
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

[I 2025-06-16 23:56:25,063] Trial 1 finished with value: 9.640525905290367 and parameters: {'cell_size': 128, 'learning_rate': 0.0006714259535313817, 'epochs': 22, 'batch_size': 256}. Best is trial 1 with value: 9.640525905290367.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 146.8159 - root_mean_squared_error: 11.7751
Epoch 2/18
  21/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 69.8949 - root_mean_squared_error: 8.3398

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 69.0029 - root_mean_squared_error: 8.2854
Epoch 3/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 64.9542 - root_mean_squared_error: 8.0329
Epoch 4/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 62.7738 - root_mean_squared_error: 7.8907
Epoch 5/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 59.6454 - root_mean_squared_error: 7.6838
Epoch 6/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.7446 - root_mean_squared_error: 7.4867
Epoch 7/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 55.6644 - root_mean_squared_error: 7.4090
Epoch 8/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 54.3801 - root_mean_squared_error: 7.3163
Epoch 9/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.1388 - root_mean_squared_error: 7.2253
Epoch 10/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.7146 - root_mean_squared_error: 7.1904
Epoch 11/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.8131 - root_mean_squared_error: 7.0515
Epoch 12/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.4568 - root_mean_squared_error: 6.9490
Epoch 13/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.3470 - root_mean_squared_error: 6.9358
Epoch 14/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.4756 - root_mean_squared_error: 6.8674
Epoch 15/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.8108 - root_mean_squared_error: 6.8135
Epoch 16/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.3342 - root_mean_squared_error: 6.7734
Epoch 17/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 46.3383 - root_mean_squared_error: 6.6944
Epoch 18/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 46.0143 - root_mean_squared_error: 6.6655
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 118.1372 - root_mean_squared_error: 10.5987
Epoch 2/18
  20/2238 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 57.7464 - root_mean_squared_error: 7.5751

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.2766 - root_mean_squared_error: 7.4772
Epoch 3/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.4798 - root_mean_squared_error: 7.0712
Epoch 4/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 45.6967 - root_mean_squared_error: 6.7180
Epoch 5/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 43.9881 - root_mean_squared_error: 6.5821
Epoch 6/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42.1411 - root_mean_squared_error: 6.4333
Epoch 7/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.7448 - root_mean_squared_error: 6.3170
Epoch 8/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.7129 - root_mean_squared_error: 6.2278
Epoch 9/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.2816 - root_mean_squared_error: 6.1862
Epoch 10/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 38.0321 - root_mean_squared_error: 6.0780
Epoch 11/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.5510 - root_mean_squared_error: 6.0317
Epoch 12/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
Epoch 13/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
Epoch 14/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
Epoch 15/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
Epoch 16/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
Epoch 17/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
Epoch 18/18
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: nan - root_mean_squared_error: nan
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:971: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 152, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-27-2395676697>", line 12, in rmse
    return np.sqrt(mean_squared_error(y_true, y_pred))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_regression.py", line 580, in mean_squared_error
    _check_reg_targets_with_floating_dtype(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_regression.py", line 209, in _check_reg_targets_with_floating_dtype
    y_type, y_true, y_pred, sample_weight, multioutput = _check_reg_targets(
                                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_regression.py", line 116, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py", line 1105, in check_array
    _assert_all_finite(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py", line 120, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py", line 169, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

  warnings.warn(
[W 2025-06-17 00:03:25,121] Trial 2 failed with parameters: {'cell_size': 128, 'learning_rate': 0.000895167621284122, 'epochs': 18, 'batch_size': 256} because of the following error: The value nan is not acceptable.
[W 2025-06-17 00:03:25,122] Trial 2 failed with value np.float64(nan).
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 104.8785 - root_mean_squared_error: 10.0571
Epoch 2/22
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 66.1337 - root_mean_squared_error: 8.0928

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.7190 - root_mean_squared_error: 8.1272
Epoch 3/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.7525 - root_mean_squared_error: 7.8700
Epoch 4/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 58.1267 - root_mean_squared_error: 7.5580
Epoch 5/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.5360 - root_mean_squared_error: 7.4395
Epoch 6/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.3985 - root_mean_squared_error: 7.2835
Epoch 7/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.2746 - root_mean_squared_error: 7.1960
Epoch 8/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.2855 - root_mean_squared_error: 7.1182
Epoch 9/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.2705 - root_mean_squared_error: 7.0392
Epoch 10/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.6655 - root_mean_squared_error: 6.9894
Epoch 11/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.7027 - root_mean_squared_error: 6.9856
Epoch 12/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.9293 - root_mean_squared_error: 6.9236
Epoch 13/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.0343 - root_mean_squared_error: 6.8531
Epoch 14/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.5862 - root_mean_squared_error: 6.8146
Epoch 15/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.5790 - root_mean_squared_error: 6.7350
Epoch 16/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.5992 - root_mean_squared_error: 6.7315
Epoch 17/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.5688 - root_mean_squared_error: 6.6497
Epoch 18/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.5326 - root_mean_squared_error: 6.6423
Epoch 19/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.9365 - root_mean_squared_error: 6.5934
Epoch 20/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.3970 - root_mean_squared_error: 6.5482
Epoch 21/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.5685 - root_mean_squared_error: 6.4809
Epoch 22/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.7357 - root_mean_squared_error: 6.4904
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/22

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 82.9934 - root_mean_squared_error: 8.9574
Epoch 2/22
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 51.4449 - root_mean_squared_error: 7.1289

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 51.9360 - root_mean_squared_error: 7.1598
Epoch 3/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.1981 - root_mean_squared_error: 6.7290
Epoch 4/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 43.4638 - root_mean_squared_error: 6.5053
Epoch 5/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 41.4630 - root_mean_squared_error: 6.3353
Epoch 6/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.7689 - root_mean_squared_error: 6.1891
Epoch 7/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 38.3417 - root_mean_squared_error: 6.0631
Epoch 8/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 37.5866 - root_mean_squared_error: 5.9919
Epoch 9/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.5467 - root_mean_squared_error: 5.8966
Epoch 10/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 35.3337 - root_mean_squared_error: 5.7868
Epoch 11/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.6938 - root_mean_squared_error: 5.7259
Epoch 12/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 34.0541 - root_mean_squared_error: 5.6653
Epoch 13/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.3126 - root_mean_squared_error: 5.5954
Epoch 14/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.9077 - root_mean_squared_error: 5.5560
Epoch 15/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.7137 - root_mean_squared_error: 5.5347
Epoch 16/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.2258 - root_mean_squared_error: 5.4877
Epoch 17/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.3568 - root_mean_squared_error: 5.4963
Epoch 18/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 31.2698 - root_mean_squared_error: 5.3932
Epoch 19/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.0771 - root_mean_squared_error: 5.3723
Epoch 20/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.7096 - root_mean_squared_error: 5.3348
Epoch 21/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.2397 - root_mean_squared_error: 5.2873
Epoch 22/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.2211 - root_mean_squared_error: 5.2827
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 00:20:24,795] Trial 3 finished with value: 9.874681744342702 and parameters: {'cell_size': 248, 'learning_rate': 0.0007707397455795148, 'epochs': 22, 'batch_size': 128}. Best is trial 1 with value: 9.640525905290367.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 158.8757 - root_mean_squared_error: 12.2376
Epoch 2/16
  19/2238 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 72.7008 - root_mean_squared_error: 8.5048

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 69.2906 - root_mean_squared_error: 8.3046
Epoch 3/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 64.5298 - root_mean_squared_error: 8.0083
Epoch 4/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 63.4021 - root_mean_squared_error: 7.9334
Epoch 5/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60.4802 - root_mean_squared_error: 7.7426
Epoch 6/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 59.0377 - root_mean_squared_error: 7.6437
Epoch 7/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.1144 - root_mean_squared_error: 7.4451
Epoch 8/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 55.7323 - root_mean_squared_error: 7.4146
Epoch 9/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 54.4537 - root_mean_squared_error: 7.3228
Epoch 10/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.0059 - root_mean_squared_error: 7.2178
Epoch 11/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.6018 - root_mean_squared_error: 7.1840
Epoch 12/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 51.5388 - root_mean_squared_error: 7.1036
Epoch 13/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.9764 - root_mean_squared_error: 7.0578
Epoch 14/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.5788 - root_mean_squared_error: 6.9528
Epoch 15/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.3888 - root_mean_squared_error: 6.9335
Epoch 16/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.6370 - root_mean_squared_error: 6.9458
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/16

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 124.5720 - root_mean_squared_error: 10.8485
Epoch 2/16
  22/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.4213 - root_mean_squared_error: 7.4876

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.0314 - root_mean_squared_error: 7.4639
Epoch 3/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.0603 - root_mean_squared_error: 7.0459
Epoch 4/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 46.1760 - root_mean_squared_error: 6.7581
Epoch 5/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 43.6537 - root_mean_squared_error: 6.5626
Epoch 6/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41.8563 - root_mean_squared_error: 6.4183
Epoch 7/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.7848 - root_mean_squared_error: 6.3289
Epoch 8/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.0488 - root_mean_squared_error: 6.2657
Epoch 9/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.2417 - root_mean_squared_error: 6.1961
Epoch 10/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 38.3036 - root_mean_squared_error: 6.1146
Epoch 11/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.9094 - root_mean_squared_error: 6.0773
Epoch 12/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.7150 - root_mean_squared_error: 5.9730
Epoch 13/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.8350 - root_mean_squared_error: 5.8939
Epoch 14/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.0830 - root_mean_squared_error: 5.8245
Epoch 15/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 34.5826 - root_mean_squared_error: 5.7766
Epoch 16/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.0542 - root_mean_squared_error: 5.7258
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

[I 2025-06-17 00:26:42,760] Trial 4 finished with value: 9.620422105543373 and parameters: {'cell_size': 128, 'learning_rate': 0.0007506835203347337, 'epochs': 16, 'batch_size': 256}. Best is trial 4 with value: 9.620422105543373.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 103.5694 - root_mean_squared_error: 9.9896
Epoch 2/24
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 69.5767 - root_mean_squared_error: 8.3019

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.4254 - root_mean_squared_error: 8.1102
Epoch 3/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.3641 - root_mean_squared_error: 7.8429
Epoch 4/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 58.6367 - root_mean_squared_error: 7.5894
Epoch 5/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.8349 - root_mean_squared_error: 7.4556
Epoch 6/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.1230 - root_mean_squared_error: 7.2586
Epoch 7/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.9397 - root_mean_squared_error: 7.1648
Epoch 8/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.3391 - root_mean_squared_error: 7.0420
Epoch 9/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.8713 - root_mean_squared_error: 6.9269
Epoch 10/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.3789 - root_mean_squared_error: 6.8814
Epoch 11/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.7033 - root_mean_squared_error: 6.8229
Epoch 12/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.0425 - root_mean_squared_error: 6.7665
Epoch 13/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.2010 - root_mean_squared_error: 6.6979
Epoch 14/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.0230 - root_mean_squared_error: 6.6790
Epoch 15/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.1703 - root_mean_squared_error: 6.6087
Epoch 16/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.7239 - root_mean_squared_error: 6.5685
Epoch 17/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.7957 - root_mean_squared_error: 6.5681
Epoch 18/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.5911 - root_mean_squared_error: 6.5468
Epoch 19/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.6861 - root_mean_squared_error: 6.4729
Epoch 20/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.0914 - root_mean_squared_error: 6.4994
Epoch 21/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.2691 - root_mean_squared_error: 6.4318
Epoch 22/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.1497 - root_mean_squared_error: 6.4188
Epoch 23/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.7330 - root_mean_squared_error: 6.3827
Epoch 24/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.3553 - root_mean_squared_error: 6.3501
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/24

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 81.4941 - root_mean_squared_error: 8.8807
Epoch 2/24
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.3518 - root_mean_squared_error: 7.1907

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.3924 - root_mean_squared_error: 7.1883
Epoch 3/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.9643 - root_mean_squared_error: 6.7055
Epoch 4/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.1454 - root_mean_squared_error: 6.4736
Epoch 5/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.0270 - root_mean_squared_error: 6.2924
Epoch 6/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.5100 - root_mean_squared_error: 6.1569
Epoch 7/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.6002 - root_mean_squared_error: 6.0719
Epoch 8/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.3842 - root_mean_squared_error: 5.9616
Epoch 9/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.7481 - root_mean_squared_error: 5.8998
Epoch 10/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.3695 - root_mean_squared_error: 5.8598
Epoch 11/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.5999 - root_mean_squared_error: 5.7878
Epoch 12/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.3675 - root_mean_squared_error: 5.7614
Epoch 13/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.5261 - root_mean_squared_error: 5.6830
Epoch 14/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.9823 - root_mean_squared_error: 5.6297
Epoch 15/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 33.5722 - root_mean_squared_error: 5.5891
Epoch 16/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.1607 - root_mean_squared_error: 5.5476
Epoch 17/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.6876 - root_mean_squared_error: 5.5015
Epoch 18/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.0605 - root_mean_squared_error: 5.5297
Epoch 19/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.3961 - root_mean_squared_error: 5.4655
Epoch 20/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.2652 - root_mean_squared_error: 5.4503
Epoch 21/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.5752 - root_mean_squared_error: 5.3836
Epoch 22/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.2045 - root_mean_squared_error: 5.3457
Epoch 23/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.1694 - root_mean_squared_error: 5.3391
Epoch 24/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.7209 - root_mean_squared_error: 5.2952
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 00:45:26,886] Trial 5 finished with value: 9.7433923719468 and parameters: {'cell_size': 248, 'learning_rate': 0.0009059845795442287, 'epochs': 24, 'batch_size': 128}. Best is trial 4 with value: 9.620422105543373.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 140.0939 - root_mean_squared_error: 11.5453
Epoch 2/22
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 79.1266 - root_mean_squared_error: 8.8672

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 70.1791 - root_mean_squared_error: 8.3516
Epoch 3/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 65.4394 - root_mean_squared_error: 8.0593
Epoch 4/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.3123 - root_mean_squared_error: 7.8590
Epoch 5/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 60.1552 - root_mean_squared_error: 7.7145
Epoch 6/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.6611 - root_mean_squared_error: 7.5437
Epoch 7/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.1042 - root_mean_squared_error: 7.4317
Epoch 8/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.1963 - root_mean_squared_error: 7.3626
Epoch 9/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.8706 - root_mean_squared_error: 7.2647
Epoch 10/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.1907 - root_mean_squared_error: 7.2107
Epoch 11/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.0206 - root_mean_squared_error: 7.1230
Epoch 12/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.1862 - root_mean_squared_error: 7.0590
Epoch 13/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.2746 - root_mean_squared_error: 6.9888
Epoch 14/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.0592 - root_mean_squared_error: 6.9685
Epoch 15/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.3368 - root_mean_squared_error: 6.9123
Epoch 16/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.8113 - root_mean_squared_error: 6.8700
Epoch 17/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.3199 - root_mean_squared_error: 6.8301
Epoch 18/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.7003 - root_mean_squared_error: 6.7807
Epoch 19/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.6136 - root_mean_squared_error: 6.7704
Epoch 20/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.8826 - root_mean_squared_error: 6.7126
Epoch 21/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.3163 - root_mean_squared_error: 6.6666
Epoch 22/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.4454 - root_mean_squared_error: 6.7462
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/22

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 104.4495 - root_mean_squared_error: 9.9895
Epoch 2/22
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.5508 - root_mean_squared_error: 7.3495

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 53.8359 - root_mean_squared_error: 7.3116
Epoch 3/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 48.7542 - root_mean_squared_error: 6.9475
Epoch 4/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 45.4243 - root_mean_squared_error: 6.6945
Epoch 5/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 43.0534 - root_mean_squared_error: 6.5060
Epoch 6/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 41.1834 - root_mean_squared_error: 6.3511
Epoch 7/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.9021 - root_mean_squared_error: 6.2416
Epoch 8/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.1943 - root_mean_squared_error: 6.1776
Epoch 9/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 38.6036 - root_mean_squared_error: 6.1226
Epoch 10/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 37.2662 - root_mean_squared_error: 6.0062
Epoch 11/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.7230 - root_mean_squared_error: 5.9549
Epoch 12/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.4118 - root_mean_squared_error: 5.9235
Epoch 13/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 35.4481 - root_mean_squared_error: 5.8366
Epoch 14/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 35.4365 - root_mean_squared_error: 5.8307
Epoch 15/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 34.4216 - root_mean_squared_error: 5.7389
Epoch 16/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 34.1050 - root_mean_squared_error: 5.7077
Epoch 17/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.6987 - root_mean_squared_error: 5.6680
Epoch 18/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.0524 - root_mean_squared_error: 5.6078
Epoch 19/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.3118 - root_mean_squared_error: 5.6274
Epoch 20/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.4498 - root_mean_squared_error: 5.5481
Epoch 21/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.6510 - root_mean_squared_error: 5.4732
Epoch 22/22
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 31.8074 - root_mean_squared_error: 5.4857
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 01:02:22,952] Trial 6 finished with value: 9.556794151289377 and parameters: {'cell_size': 128, 'learning_rate': 0.0006902357024666754, 'epochs': 22, 'batch_size': 128}. Best is trial 6 with value: 9.556794151289377.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 178.1159 - root_mean_squared_error: 12.9332
Epoch 2/20
  21/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 70.8265 - root_mean_squared_error: 8.3946

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 70.2881 - root_mean_squared_error: 8.3649
Epoch 3/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 65.5172 - root_mean_squared_error: 8.0717
Epoch 4/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 62.9472 - root_mean_squared_error: 7.9081
Epoch 5/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60.7369 - root_mean_squared_error: 7.7638
Epoch 6/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 57.9999 - root_mean_squared_error: 7.5827
Epoch 7/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.6151 - root_mean_squared_error: 7.4881
Epoch 8/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 55.3654 - root_mean_squared_error: 7.4017
Epoch 9/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 54.8102 - root_mean_squared_error: 7.3615
Epoch 10/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.4772 - root_mean_squared_error: 7.2679
Epoch 11/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.9298 - root_mean_squared_error: 7.2275
Epoch 12/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.0793 - root_mean_squared_error: 7.1657
Epoch 13/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 51.4258 - root_mean_squared_error: 7.1172
Epoch 14/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 51.0083 - root_mean_squared_error: 7.0850
Epoch 15/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.8761 - root_mean_squared_error: 7.0021
Epoch 16/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.3099 - root_mean_squared_error: 6.9589
Epoch 17/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.5275 - root_mean_squared_error: 6.8997
Epoch 18/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.2482 - root_mean_squared_error: 6.8766
Epoch 19/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.3715 - root_mean_squared_error: 6.8099
Epoch 20/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.1737 - root_mean_squared_error: 6.7926
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 133.7047 - root_mean_squared_error: 11.2503
Epoch 2/20
  21/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 61.3229 - root_mean_squared_error: 7.8111

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58.1281 - root_mean_squared_error: 7.6025
Epoch 3/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.2594 - root_mean_squared_error: 7.0616
Epoch 4/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 46.5311 - root_mean_squared_error: 6.7874
Epoch 5/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 44.4335 - root_mean_squared_error: 6.6257
Epoch 6/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42.3796 - root_mean_squared_error: 6.4641
Epoch 7/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41.4080 - root_mean_squared_error: 6.3844
Epoch 8/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.3323 - root_mean_squared_error: 6.2955
Epoch 9/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.2916 - root_mean_squared_error: 6.2082
Epoch 10/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.3321 - root_mean_squared_error: 6.2081
Epoch 11/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 38.2812 - root_mean_squared_error: 6.1195
Epoch 12/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.4637 - root_mean_squared_error: 6.0491
Epoch 13/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.0847 - root_mean_squared_error: 6.0148
Epoch 14/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.5643 - root_mean_squared_error: 5.9684
Epoch 15/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.2631 - root_mean_squared_error: 5.9400
Epoch 16/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.5906 - root_mean_squared_error: 5.8799
Epoch 17/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.3160 - root_mean_squared_error: 5.8535
Epoch 18/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.1285 - root_mean_squared_error: 5.8346
Epoch 19/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.7115 - root_mean_squared_error: 5.7957
Epoch 20/20
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.4973 - root_mean_squared_error: 5.7741
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

[I 2025-06-17 01:10:09,300] Trial 7 finished with value: 13.088488099136544 and parameters: {'cell_size': 128, 'learning_rate': 0.0005781177881177701, 'epochs': 20, 'batch_size': 256}. Best is trial 6 with value: 9.556794151289377.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 105.9559 - root_mean_squared_error: 10.0986
Epoch 2/15
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 68.0718 - root_mean_squared_error: 8.2141

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.6629 - root_mean_squared_error: 8.1295
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.6787 - root_mean_squared_error: 7.8672
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 60.0452 - root_mean_squared_error: 7.6554
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.3898 - root_mean_squared_error: 7.4523
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.0234 - root_mean_squared_error: 7.2615
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.1358 - root_mean_squared_error: 7.1425
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.7234 - root_mean_squared_error: 7.0185
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.3039 - root_mean_squared_error: 6.9410
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.3151 - root_mean_squared_error: 6.8796
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.9381 - root_mean_squared_error: 6.7819
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.5533 - root_mean_squared_error: 6.7524
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.5502 - root_mean_squared_error: 6.6743
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.4879 - root_mean_squared_error: 6.6648
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.5947 - root_mean_squared_error: 6.5920
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 84.4406 - root_mean_squared_error: 9.0221
Epoch 2/15
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.3459 - root_mean_squared_error: 6.7582

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.8156 - root_mean_squared_error: 7.1533
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.5655 - root_mean_squared_error: 6.6864
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.3965 - root_mean_squared_error: 6.4307
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.0921 - root_mean_squared_error: 6.2364
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.1440 - root_mean_squared_error: 6.1479
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.3902 - root_mean_squared_error: 5.9930
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.4712 - root_mean_squared_error: 5.9062
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.5438 - root_mean_squared_error: 5.8189
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.3002 - root_mean_squared_error: 5.7036
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.9511 - root_mean_squared_error: 5.6658
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.0698 - root_mean_squared_error: 5.5806
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.4777 - root_mean_squared_error: 5.5213
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.8241 - root_mean_squared_error: 5.4568
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.4746 - root_mean_squared_error: 5.4201
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 01:22:05,617] Trial 8 finished with value: 9.32096330806603 and parameters: {'cell_size': 248, 'learning_rate': 0.0007323107723719864, 'epochs': 15, 'batch_size': 128}. Best is trial 8 with value: 9.32096330806603.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 106.8682 - root_mean_squared_error: 10.1307
Epoch 2/24
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 67.0186 - root_mean_squared_error: 8.1467

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 67.1954 - root_mean_squared_error: 8.1614
Epoch 3/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.8329 - root_mean_squared_error: 7.8814
Epoch 4/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.5719 - root_mean_squared_error: 7.6593
Epoch 5/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.7848 - root_mean_squared_error: 7.4620
Epoch 6/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.4367 - root_mean_squared_error: 7.2929
Epoch 7/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.5474 - root_mean_squared_error: 7.1526
Epoch 8/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.6538 - root_mean_squared_error: 7.0110
Epoch 9/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.5063 - root_mean_squared_error: 6.9221
Epoch 10/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.7196 - root_mean_squared_error: 6.8588
Epoch 11/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.3108 - root_mean_squared_error: 6.7504
Epoch 12/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.9481 - root_mean_squared_error: 6.7194
Epoch 13/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.9053 - root_mean_squared_error: 6.6371
Epoch 14/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.3577 - root_mean_squared_error: 6.5915
Epoch 15/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.5806 - root_mean_squared_error: 6.5284
Epoch 16/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.9232 - root_mean_squared_error: 6.4746
Epoch 17/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.4720 - root_mean_squared_error: 6.4365
Epoch 18/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.6074 - root_mean_squared_error: 6.3652
Epoch 19/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.3463 - root_mean_squared_error: 6.3421
Epoch 20/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.9829 - root_mean_squared_error: 6.3117
Epoch 21/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.4561 - root_mean_squared_error: 6.2677
Epoch 22/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.1437 - root_mean_squared_error: 6.2407
Epoch 23/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.7522 - root_mean_squared_error: 6.2072
Epoch 24/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.3442 - root_mean_squared_error: 6.1721
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/24

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 86.0060 - root_mean_squared_error: 9.1051
Epoch 2/24
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.2701 - root_mean_squared_error: 6.9711

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.4300 - root_mean_squared_error: 7.1237
Epoch 3/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.8287 - root_mean_squared_error: 6.5498
Epoch 4/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.0095 - root_mean_squared_error: 6.3159
Epoch 5/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.0271 - root_mean_squared_error: 6.1443
Epoch 6/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.8473 - root_mean_squared_error: 6.0353
Epoch 7/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.9671 - root_mean_squared_error: 5.8674
Epoch 8/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.7852 - root_mean_squared_error: 5.7574
Epoch 9/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.1553 - root_mean_squared_error: 5.6946
Epoch 10/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.4433 - root_mean_squared_error: 5.6246
Epoch 11/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.5408 - root_mean_squared_error: 5.5378
Epoch 12/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.3855 - root_mean_squared_error: 5.5177
Epoch 13/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.3445 - root_mean_squared_error: 5.4173
Epoch 14/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.2920 - root_mean_squared_error: 5.4077
Epoch 15/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.5285 - root_mean_squared_error: 5.3321
Epoch 16/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.2325 - root_mean_squared_error: 5.3008
Epoch 17/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 29.8784 - root_mean_squared_error: 5.2641
Epoch 18/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 29.5271 - root_mean_squared_error: 5.2274
Epoch 19/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 29.2647 - root_mean_squared_error: 5.1988
Epoch 20/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 28.8245 - root_mean_squared_error: 5.1533
Epoch 21/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 28.7837 - root_mean_squared_error: 5.1467
Epoch 22/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 28.6469 - root_mean_squared_error: 5.1299
Epoch 23/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 28.5550 - root_mean_squared_error: 5.1192
Epoch 24/24
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 28.2403 - root_mean_squared_error: 5.0868
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 01:40:51,572] Trial 9 finished with value: 11.658203214021505 and parameters: {'cell_size': 248, 'learning_rate': 0.0006729804171202546, 'epochs': 24, 'batch_size': 128}. Best is trial 8 with value: 9.32096330806603.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 156.5239 - root_mean_squared_error: 12.1591
Epoch 2/16
  22/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 75.7304 - root_mean_squared_error: 8.6741

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 75.6696 - root_mean_squared_error: 8.6788
Epoch 3/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 71.8224 - root_mean_squared_error: 8.4465
Epoch 4/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 64.3390 - root_mean_squared_error: 7.9900
Epoch 5/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 62.2021 - root_mean_squared_error: 7.8511
Epoch 6/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58.9980 - root_mean_squared_error: 7.6400
Epoch 7/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.8661 - root_mean_squared_error: 7.4945
Epoch 8/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 55.3609 - root_mean_squared_error: 7.3888
Epoch 9/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.9550 - root_mean_squared_error: 7.2884
Epoch 10/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.6175 - root_mean_squared_error: 7.1913
Epoch 11/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 51.4688 - root_mean_squared_error: 7.1063
Epoch 12/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.5051 - root_mean_squared_error: 7.0336
Epoch 13/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.2682 - root_mean_squared_error: 7.0122
Epoch 14/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.2166 - root_mean_squared_error: 6.9324
Epoch 15/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.6134 - root_mean_squared_error: 6.8847
Epoch 16/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 47.9404 - root_mean_squared_error: 6.8314
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/16

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 121.9688 - root_mean_squared_error: 10.7545
Epoch 2/16
  21/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58.4072 - root_mean_squared_error: 7.6171

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 54.3585 - root_mean_squared_error: 7.3502
Epoch 3/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 48.1558 - root_mean_squared_error: 6.9092
Epoch 4/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 44.9975 - root_mean_squared_error: 6.6705
Epoch 5/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42.9173 - root_mean_squared_error: 6.5067
Epoch 6/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.9233 - root_mean_squared_error: 6.3461
Epoch 7/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.1524 - root_mean_squared_error: 6.2801
Epoch 8/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39.0147 - root_mean_squared_error: 6.1840
Epoch 9/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 38.0534 - root_mean_squared_error: 6.1009
Epoch 10/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.3646 - root_mean_squared_error: 6.0397
Epoch 11/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.3622 - root_mean_squared_error: 6.0351
Epoch 12/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.2653 - root_mean_squared_error: 5.9395
Epoch 13/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.1312 - root_mean_squared_error: 5.9242
Epoch 14/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.4702 - root_mean_squared_error: 5.8646
Epoch 15/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.5418 - root_mean_squared_error: 5.8670
Epoch 16/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.9214 - root_mean_squared_error: 5.8108
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

[I 2025-06-17 01:47:09,617] Trial 10 finished with value: 9.45058649572283 and parameters: {'cell_size': 128, 'learning_rate': 0.0007394047651753669, 'epochs': 16, 'batch_size': 256}. Best is trial 8 with value: 9.32096330806603.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 101.9718 - root_mean_squared_error: 9.9151
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 68.8593 - root_mean_squared_error: 8.2595

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.6523 - root_mean_squared_error: 8.1230
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 63.1889 - root_mean_squared_error: 7.8955
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.5045 - root_mean_squared_error: 7.6455
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.2099 - root_mean_squared_error: 7.4805
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.8209 - root_mean_squared_error: 7.3058
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.1909 - root_mean_squared_error: 7.1801
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.7903 - root_mean_squared_error: 7.0715
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.8260 - root_mean_squared_error: 6.9935
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.8305 - root_mean_squared_error: 6.9131
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.5204 - root_mean_squared_error: 6.8098
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.6862 - root_mean_squared_error: 6.7412
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.3113 - root_mean_squared_error: 6.7063
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.0085 - root_mean_squared_error: 6.6775
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.0144 - root_mean_squared_error: 6.5960
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.0803 - root_mean_squared_error: 6.5945
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.0060 - root_mean_squared_error: 6.5823
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.3859 - root_mean_squared_error: 6.5295
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 83.3241 - root_mean_squared_error: 8.9746
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.8601 - root_mean_squared_error: 7.6782

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.7227 - root_mean_squared_error: 7.1389
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.3779 - root_mean_squared_error: 6.7301
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.1051 - root_mean_squared_error: 6.4626
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.5243 - root_mean_squared_error: 6.3240
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.1219 - root_mean_squared_error: 6.2003
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.4189 - root_mean_squared_error: 6.1327
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.4490 - root_mean_squared_error: 6.0429
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.5583 - root_mean_squared_error: 5.9606
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.2043 - root_mean_squared_error: 5.9231
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.0436 - root_mean_squared_error: 5.8179
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.8878 - root_mean_squared_error: 5.7994
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.4157 - root_mean_squared_error: 5.7537
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.1046 - root_mean_squared_error: 5.7228
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.7096 - root_mean_squared_error: 5.6846
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.3222 - root_mean_squared_error: 5.6470
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.6945 - root_mean_squared_error: 5.5874
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.5725 - root_mean_squared_error: 5.5731
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step

[I 2025-06-17 02:01:21,094] Trial 11 finished with value: 9.009451780255338 and parameters: {'cell_size': 248, 'learning_rate': 0.000996069243535314, 'epochs': 18, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 100.8680 - root_mean_squared_error: 9.8643
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 67.7439 - root_mean_squared_error: 8.1938

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 67.1695 - root_mean_squared_error: 8.1557
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 64.0760 - root_mean_squared_error: 7.9499
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 60.9915 - root_mean_squared_error: 7.7403
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.5554 - root_mean_squared_error: 7.4999
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.7436 - root_mean_squared_error: 7.3659
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.8416 - root_mean_squared_error: 7.2250
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 52.4536 - root_mean_squared_error: 7.1180
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 51.4530 - root_mean_squared_error: 7.0382
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.3996 - root_mean_squared_error: 6.9546
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.0705 - root_mean_squared_error: 6.9241
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.1284 - root_mean_squared_error: 6.8504
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.5218 - root_mean_squared_error: 6.8018
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.5191 - root_mean_squared_error: 6.7983
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.8833 - root_mean_squared_error: 6.7473
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.4006 - root_mean_squared_error: 6.7089
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.2415 - root_mean_squared_error: 6.6934
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.9436 - root_mean_squared_error: 6.6676
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 84.5404 - root_mean_squared_error: 9.0174
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 50.4893 - root_mean_squared_error: 7.0573

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.8253 - root_mean_squared_error: 7.2180
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.1847 - root_mean_squared_error: 6.8706
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.8560 - root_mean_squared_error: 6.6058
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.7743 - root_mean_squared_error: 6.4313
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.1419 - root_mean_squared_error: 6.3704
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.6022 - root_mean_squared_error: 6.2384
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.4117 - root_mean_squared_error: 6.1328
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.4722 - root_mean_squared_error: 6.0482
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.6316 - root_mean_squared_error: 5.9715
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.8905 - root_mean_squared_error: 5.9021
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.5404 - root_mean_squared_error: 5.8685
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.8677 - root_mean_squared_error: 5.8057
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.5762 - root_mean_squared_error: 5.7754
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.9288 - root_mean_squared_error: 5.7143
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.1645 - root_mean_squared_error: 5.7300
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.5768 - root_mean_squared_error: 5.6756
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.5181 - root_mean_squared_error: 5.6652
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 02:15:40,598] Trial 12 finished with value: 14.677364496991125 and parameters: {'cell_size': 248, 'learning_rate': 0.0009600953511777438, 'epochs': 18, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 110.4095 - root_mean_squared_error: 10.2896
Epoch 2/15
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 76.5745 - root_mean_squared_error: 8.7202

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 69.8498 - root_mean_squared_error: 8.3243
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 63.6795 - root_mean_squared_error: 7.9359
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 58.9965 - root_mean_squared_error: 7.6251
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.7271 - root_mean_squared_error: 7.3280
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.5299 - root_mean_squared_error: 7.1649
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.4903 - root_mean_squared_error: 7.0109
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.6225 - root_mean_squared_error: 6.8672
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.7038 - root_mean_squared_error: 6.7914
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.8343 - root_mean_squared_error: 6.7192
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.8142 - root_mean_squared_error: 6.6358
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.2337 - root_mean_squared_error: 6.5849
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.4034 - root_mean_squared_error: 6.5151
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.7946 - root_mean_squared_error: 6.4620
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.2163 - root_mean_squared_error: 6.4110
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 88.6001 - root_mean_squared_error: 9.2265
Epoch 2/15
  20/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 63.4337 - root_mean_squared_error: 7.9277

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.1264 - root_mean_squared_error: 7.1799
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.5922 - root_mean_squared_error: 6.6977
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.7059 - root_mean_squared_error: 6.4664
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.9374 - root_mean_squared_error: 6.2377
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.9835 - root_mean_squared_error: 6.0694
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.4996 - root_mean_squared_error: 5.9375
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.3672 - root_mean_squared_error: 5.8328
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.8730 - root_mean_squared_error: 5.7826
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.0188 - root_mean_squared_error: 5.7015
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.1878 - root_mean_squared_error: 5.6220
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.5144 - root_mean_squared_error: 5.5568
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.6675 - root_mean_squared_error: 5.4745
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.4251 - root_mean_squared_error: 5.4473
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.2567 - root_mean_squared_error: 5.3350
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 02:27:30,449] Trial 13 finished with value: 9.948617242783518 and parameters: {'cell_size': 248, 'learning_rate': 0.0005360719332303035, 'epochs': 15, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 104.2971 - root_mean_squared_error: 10.0350
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 67.9797 - root_mean_squared_error: 8.2059

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.9511 - root_mean_squared_error: 8.1415
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 63.6419 - root_mean_squared_error: 7.9234
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.7407 - root_mean_squared_error: 7.6603
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 56.9444 - root_mean_squared_error: 7.4612
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.2640 - root_mean_squared_error: 7.3347
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.0051 - root_mean_squared_error: 7.2361
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.7027 - root_mean_squared_error: 7.1356
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.4433 - root_mean_squared_error: 7.0373
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.7551 - root_mean_squared_error: 6.9797
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.8877 - root_mean_squared_error: 6.9094
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.8932 - root_mean_squared_error: 6.8291
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.0288 - root_mean_squared_error: 6.7580
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.7572 - root_mean_squared_error: 6.7308
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.5396 - root_mean_squared_error: 6.7084
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.0471 - root_mean_squared_error: 6.6660
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.3233 - root_mean_squared_error: 6.6059
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.1009 - root_mean_squared_error: 6.5832
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 83.5717 - root_mean_squared_error: 8.9828
Epoch 2/18
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 54.4095 - root_mean_squared_error: 7.3310

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 52.6623 - root_mean_squared_error: 7.2081
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.1450 - root_mean_squared_error: 6.7215
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 43.0516 - root_mean_squared_error: 6.4690
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 41.4283 - root_mean_squared_error: 6.3282
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.4933 - root_mean_squared_error: 6.2407
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.3788 - root_mean_squared_error: 6.1396
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.8104 - root_mean_squared_error: 6.0001
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.8343 - root_mean_squared_error: 5.9077
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.2085 - root_mean_squared_error: 5.8443
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 35.1051 - root_mean_squared_error: 5.7410
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 34.4951 - root_mean_squared_error: 5.6813
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.9340 - root_mean_squared_error: 5.6266
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.8200 - root_mean_squared_error: 5.5218
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.4217 - root_mean_squared_error: 5.4814
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.5130 - root_mean_squared_error: 5.4858
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 31.6344 - root_mean_squared_error: 5.4015
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 31.7661 - root_mean_squared_error: 5.4106
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 02:41:24,440] Trial 14 finished with value: 17.451335902795456 and parameters: {'cell_size': 248, 'learning_rate': 0.0008610979130448681, 'epochs': 18, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 100.7684 - root_mean_squared_error: 9.8737
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.8177 - root_mean_squared_error: 8.1316

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 66.4464 - root_mean_squared_error: 8.1066
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 61.5905 - root_mean_squared_error: 7.7870
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 57.7168 - root_mean_squared_error: 7.5183
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 55.5535 - root_mean_squared_error: 7.3580
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.5039 - root_mean_squared_error: 7.2732
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 55.6838 - root_mean_squared_error: 7.3400
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.7186 - root_mean_squared_error: 7.0578
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 51.1954 - root_mean_squared_error: 7.0137
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 50.9789 - root_mean_squared_error: 6.9897
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.3647 - root_mean_squared_error: 6.8658
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.8407 - root_mean_squared_error: 6.8937
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.2652 - root_mean_squared_error: 6.8444
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 48.5400 - root_mean_squared_error: 6.7852
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 47.6472 - root_mean_squared_error: 6.7144
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 47.6320 - root_mean_squared_error: 6.7081
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.6173 - root_mean_squared_error: 6.6273
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.6144 - root_mean_squared_error: 6.6218
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/18

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - loss: 87.4147 - root_mean_squared_error: 9.1711
Epoch 2/18
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.0126 - root_mean_squared_error: 7.0786

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.1188 - root_mean_squared_error: 7.3133
Epoch 3/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.8373 - root_mean_squared_error: 6.9271
Epoch 4/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.8950 - root_mean_squared_error: 6.8410
Epoch 5/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.4650 - root_mean_squared_error: 7.3609
Epoch 6/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.4291 - root_mean_squared_error: 6.9413
Epoch 7/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.4298 - root_mean_squared_error: 6.7183
Epoch 8/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.8670 - root_mean_squared_error: 6.5911
Epoch 9/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.8429 - root_mean_squared_error: 6.4270
Epoch 10/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.4033 - root_mean_squared_error: 6.3847
Epoch 11/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 41.0301 - root_mean_squared_error: 6.2693
Epoch 12/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.7947 - root_mean_squared_error: 6.2439
Epoch 13/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.0647 - root_mean_squared_error: 6.1802
Epoch 14/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.5185 - root_mean_squared_error: 6.1309
Epoch 15/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.7101 - root_mean_squared_error: 6.0598
Epoch 16/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 39.0441 - root_mean_squared_error: 6.0826
Epoch 17/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.2546 - root_mean_squared_error: 6.0121
Epoch 18/18
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.6952 - root_mean_squared_error: 5.9605
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 02:55:28,873] Trial 15 finished with value: 10.148392380220589 and parameters: {'cell_size': 248, 'learning_rate': 0.0009981582444137911, 'epochs': 18, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - loss: 108.4291 - root_mean_squared_error: 10.2075
Epoch 2/17
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 65.1676 - root_mean_squared_error: 8.0308

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.2627 - root_mean_squared_error: 8.1036
Epoch 3/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.2547 - root_mean_squared_error: 7.8447
Epoch 4/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.4857 - root_mean_squared_error: 7.5238
Epoch 5/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 53.9434 - root_mean_squared_error: 7.2732
Epoch 6/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.9793 - root_mean_squared_error: 7.1258
Epoch 7/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.7811 - root_mean_squared_error: 6.9601
Epoch 8/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.5715 - root_mean_squared_error: 6.8634
Epoch 9/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.6071 - root_mean_squared_error: 6.7846
Epoch 10/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.9096 - root_mean_squared_error: 6.7251
Epoch 11/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.1726 - root_mean_squared_error: 6.6632
Epoch 12/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.4572 - root_mean_squared_error: 6.6032
Epoch 13/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.4903 - root_mean_squared_error: 6.5238
Epoch 14/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.1213 - root_mean_squared_error: 6.4901
Epoch 15/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.9283 - root_mean_squared_error: 6.4701
Epoch 16/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.6301 - root_mean_squared_error: 6.4413
Epoch 17/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 43.0919 - root_mean_squared_error: 6.3944
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/17

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 87.3822 - root_mean_squared_error: 9.1713
Epoch 2/17
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 60.9737 - root_mean_squared_error: 7.7613

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 52.2992 - root_mean_squared_error: 7.1884
Epoch 3/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 45.5572 - root_mean_squared_error: 6.6864
Epoch 4/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 41.3216 - root_mean_squared_error: 6.3454
Epoch 5/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.3885 - root_mean_squared_error: 6.1763
Epoch 6/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.4378 - root_mean_squared_error: 6.0040
Epoch 7/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.8479 - root_mean_squared_error: 5.9432
Epoch 8/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 34.7498 - root_mean_squared_error: 5.7541
Epoch 9/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.2041 - root_mean_squared_error: 5.6968
Epoch 10/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.3345 - root_mean_squared_error: 5.6117
Epoch 11/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.4721 - root_mean_squared_error: 5.5267
Epoch 12/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.5523 - root_mean_squared_error: 5.4360
Epoch 13/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.9774 - root_mean_squared_error: 5.3767
Epoch 14/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.6452 - root_mean_squared_error: 5.3397
Epoch 15/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 30.3460 - root_mean_squared_error: 5.3066
Epoch 16/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 29.9358 - root_mean_squared_error: 5.2626
Epoch 17/17
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 29.7297 - root_mean_squared_error: 5.2390
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 03:08:42,301] Trial 16 finished with value: 9.711831462569346 and parameters: {'cell_size': 248, 'learning_rate': 0.0006063216411964779, 'epochs': 17, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 104.5767 - root_mean_squared_error: 10.0272
Epoch 2/15
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 68.6054 - root_mean_squared_error: 8.2444

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 67.8871 - root_mean_squared_error: 8.1983
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 63.7326 - root_mean_squared_error: 7.9281
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 59.3019 - root_mean_squared_error: 7.6304
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 57.2405 - root_mean_squared_error: 7.4819
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 58.5533 - root_mean_squared_error: 7.5544
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 53.5881 - root_mean_squared_error: 7.2089
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.5585 - root_mean_squared_error: 7.1283
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.9369 - root_mean_squared_error: 7.0045
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 50.0619 - root_mean_squared_error: 6.9339
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 49.3216 - root_mean_squared_error: 6.8729
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 48.5057 - root_mean_squared_error: 6.8062
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 48.1938 - root_mean_squared_error: 6.7770
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 47.7241 - root_mean_squared_error: 6.7365
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.3977 - root_mean_squared_error: 6.7064
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/15

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 83.9268 - root_mean_squared_error: 8.9890
Epoch 2/15
  22/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 54.6449 - root_mean_squared_error: 7.3486

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.3590 - root_mean_squared_error: 7.1175
Epoch 3/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.1386 - root_mean_squared_error: 6.6464
Epoch 4/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 42.4525 - root_mean_squared_error: 6.4236
Epoch 5/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 40.3890 - root_mean_squared_error: 6.2488
Epoch 6/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 38.7279 - root_mean_squared_error: 6.1028
Epoch 7/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.7258 - root_mean_squared_error: 6.0102
Epoch 8/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.8818 - root_mean_squared_error: 5.9289
Epoch 9/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.5776 - root_mean_squared_error: 5.8097
Epoch 10/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.0465 - root_mean_squared_error: 5.7566
Epoch 11/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.4730 - root_mean_squared_error: 5.6997
Epoch 12/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.2534 - root_mean_squared_error: 5.6730
Epoch 13/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.0764 - root_mean_squared_error: 5.5591
Epoch 14/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.9146 - root_mean_squared_error: 5.5402
Epoch 15/15
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.2946 - root_mean_squared_error: 5.4795
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 03:20:21,891] Trial 17 finished with value: 13.690884315809484 and parameters: {'cell_size': 248, 'learning_rate': 0.0008478643579493255, 'epochs': 15, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 104.5620 - root_mean_squared_error: 10.0375
Epoch 2/19
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 71.0683 - root_mean_squared_error: 8.3851

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 66.1539 - root_mean_squared_error: 8.0940
Epoch 3/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 62.5598 - root_mean_squared_error: 7.8568
Epoch 4/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 57.7193 - root_mean_squared_error: 7.5280
Epoch 5/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 55.5859 - root_mean_squared_error: 7.3707
Epoch 6/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 54.1066 - root_mean_squared_error: 7.2564
Epoch 7/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 52.5225 - root_mean_squared_error: 7.1347
Epoch 8/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 51.4311 - root_mean_squared_error: 7.0468
Epoch 9/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.9878 - root_mean_squared_error: 6.9345
Epoch 10/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 49.4999 - root_mean_squared_error: 6.8908
Epoch 11/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 48.2739 - root_mean_squared_error: 6.7943
Epoch 12/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 47.6136 - root_mean_squared_error: 6.7391
Epoch 13/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.9495 - root_mean_squared_error: 6.6819
Epoch 14/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.2455 - root_mean_squared_error: 6.6221
Epoch 15/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 46.1429 - root_mean_squared_error: 6.6082
Epoch 16/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 45.2302 - root_mean_squared_error: 6.5338
Epoch 17/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.5697 - root_mean_squared_error: 6.4779
Epoch 18/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.4764 - root_mean_squared_error: 6.4660
Epoch 19/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 44.1223 - root_mean_squared_error: 6.4338
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step
Epoch 1/19

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - loss: 84.6902 - root_mean_squared_error: 9.0280
Epoch 2/19
  21/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 51.2586 - root_mean_squared_error: 7.1136

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 52.3684 - root_mean_squared_error: 7.1886
Epoch 3/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 46.3193 - root_mean_squared_error: 6.7339
Epoch 4/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 43.0038 - root_mean_squared_error: 6.4649
Epoch 5/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 40.9520 - root_mean_squared_error: 6.2904
Epoch 6/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 39.6137 - root_mean_squared_error: 6.1713
Epoch 7/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 38.4956 - root_mean_squared_error: 6.0709
Epoch 8/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 37.4575 - root_mean_squared_error: 5.9748
Epoch 9/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 36.6611 - root_mean_squared_error: 5.9003
Epoch 10/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 36.2201 - root_mean_squared_error: 5.8559
Epoch 11/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 35.2934 - root_mean_squared_error: 5.7706
Epoch 12/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.7326 - root_mean_squared_error: 5.7154
Epoch 13/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 34.2183 - root_mean_squared_error: 5.6636
Epoch 14/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 33.5003 - root_mean_squared_error: 5.5945
Epoch 15/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 33.7756 - root_mean_squared_error: 5.6139
Epoch 16/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 32.6200 - root_mean_squared_error: 5.5057
Epoch 17/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.3195 - root_mean_squared_error: 5.4734
Epoch 18/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 32.3142 - root_mean_squared_error: 5.4688
Epoch 19/19
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 31.9621 - root_mean_squared_error: 5.4332
4476/4476 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step

[I 2025-06-17 03:35:01,567] Trial 18 finished with value: 16.12462393813022 and parameters: {'cell_size': 248, 'learning_rate': 0.0008281415913360263, 'epochs': 19, 'batch_size': 128}. Best is trial 11 with value: 9.009451780255338.
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 137.2702 - root_mean_squared_error: 11.4305
Epoch 2/16
  22/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 73.1595 - root_mean_squared_error: 8.5290

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 70.5256 - root_mean_squared_error: 8.3732
Epoch 3/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 66.7455 - root_mean_squared_error: 8.1413
Epoch 4/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 63.6579 - root_mean_squared_error: 7.9467
Epoch 5/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 62.6288 - root_mean_squared_error: 7.8781
Epoch 6/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60.1538 - root_mean_squared_error: 7.7148
Epoch 7/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58.9092 - root_mean_squared_error: 7.6288
Epoch 8/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58.4817 - root_mean_squared_error: 7.5952
Epoch 9/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 56.3014 - root_mean_squared_error: 7.4449
Epoch 10/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.9596 - root_mean_squared_error: 7.2813
Epoch 11/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 52.9666 - root_mean_squared_error: 7.2078
Epoch 12/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 51.7716 - root_mean_squared_error: 7.1195
Epoch 13/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 50.4183 - root_mean_squared_error: 7.0189
Epoch 14/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 49.3784 - root_mean_squared_error: 6.9398
Epoch 15/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 48.6489 - root_mean_squared_error: 6.8826
Epoch 16/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.5557 - root_mean_squared_error: 6.7985
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/16

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 105.1843 - root_mean_squared_error: 10.0076
Epoch 2/16
  22/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60.8183 - root_mean_squared_error: 7.7451

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 53.9851 - root_mean_squared_error: 7.3121
Epoch 3/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 47.6223 - root_mean_squared_error: 6.8564
Epoch 4/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 43.6905 - root_mean_squared_error: 6.5557
Epoch 5/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40.7723 - root_mean_squared_error: 6.3224
Epoch 6/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 38.9823 - root_mean_squared_error: 6.1725
Epoch 7/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 37.4218 - root_mean_squared_error: 6.0377
Epoch 8/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.6003 - root_mean_squared_error: 5.9626
Epoch 9/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 35.2438 - root_mean_squared_error: 5.8406
Epoch 10/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.7831 - root_mean_squared_error: 5.7940
Epoch 11/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 34.4020 - root_mean_squared_error: 5.7541
Epoch 12/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 36.7001 - root_mean_squared_error: 5.9401
Epoch 13/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 32.1709 - root_mean_squared_error: 5.5421
Epoch 14/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 31.8245 - root_mean_squared_error: 5.5051
Epoch 15/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 31.1494 - root_mean_squared_error: 5.4377
Epoch 16/16
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 31.0589 - root_mean_squared_error: 5.4241
2238/2238 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step

[I 2025-06-17 03:41:18,187] Trial 19 finished with value: 16.317944318911245 and parameters: {'cell_size': 248, 'learning_rate': 0.0005100726560266714, 'epochs': 16, 'batch_size': 256}. Best is trial 11 with value: 9.009451780255338.

In [29]:
print("Random Search에서의 최고의 하이퍼파라미터 조합 : ", bayesian_study.best_trial)

Random Search에서의 최고의 하이퍼파라미터 조합 :  FrozenTrial(number=11, state=1, values=[9.009451780255338], datetime_start=datetime.datetime(2025, 6, 17, 1, 47, 9, 618014), datetime_complete=datetime.datetime(2025, 6, 17, 2, 1, 21, 94460), params={'cell_size': 248, 'learning_rate': 0.000996069243535314, 'epochs': 18, 'batch_size': 128}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'cell_size': CategoricalDistribution(choices=(128, 248)), 'learning_rate': FloatDistribution(high=0.001, log=True, low=0.0005, step=None), 'epochs': IntDistribution(high=25, log=False, low=15, step=1), 'batch_size': CategoricalDistribution(choices=(128, 256))}, trial_id=11, value=None)

In [30]:
best_params = bayesian_study.best_params
final_gru_model = gru_model(
    cell_size=best_params['cell_size'],
    learning_rate=best_params['learning_rate']
)
history = final_gru_model.fit(
    x_train, t_train,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    callbacks=[early_stopping]
)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 466s 5ms/step - loss: 111.5431 - root_mean_squared_error: 10.4858
Epoch 2/18

/usr/local/lib/python3.11/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 98.0022 - root_mean_squared_error: 9.7845
Epoch 3/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 96.7621 - root_mean_squared_error: 9.7140
Epoch 4/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 96.2472 - root_mean_squared_error: 9.6744
Epoch 5/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 92.9970 - root_mean_squared_error: 9.4994
Epoch 6/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 92.8894 - root_mean_squared_error: 9.4917
Epoch 7/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 93.2169 - root_mean_squared_error: 9.5105
Epoch 8/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 464s 5ms/step - loss: 93.4938 - root_mean_squared_error: 9.5135
Epoch 9/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 465s 5ms/step - loss: 92.1646 - root_mean_squared_error: 9.4400
Epoch 10/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 465s 5ms/step - loss: 91.2180 - root_mean_squared_error: 9.3865
Epoch 11/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 464s 5ms/step - loss: 90.3971 - root_mean_squared_error: 9.3418
Epoch 12/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 463s 5ms/step - loss: 89.9098 - root_mean_squared_error: 9.3116
Epoch 13/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 472s 5ms/step - loss: 89.0798 - root_mean_squared_error: 9.2615
Epoch 14/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 464s 5ms/step - loss: 88.5751 - root_mean_squared_error: 9.2281
Epoch 15/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 464s 5ms/step - loss: 88.5575 - root_mean_squared_error: 9.2250
Epoch 16/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 464s 5ms/step - loss: 87.9750 - root_mean_squared_error: 9.1906
Epoch 17/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 467s 5ms/step - loss: 89.2532 - root_mean_squared_error: 9.2559
Epoch 18/18
89520/89520 ━━━━━━━━━━━━━━━━━━━━ 468s 5ms/step - loss: 88.8348 - root_mean_squared_error: 9.2323

In [31]:
loss, rmse = final_gru_model.evaluate(x_test, t_test, verbose=1)
print('test loss(MSE) :', round(loss, 6))
print('test RMSE :', round(rmse, 2))

153463/153463 ━━━━━━━━━━━━━━━━━━━━ 389s 3ms/step - loss: 103.6564 - root_mean_squared_error: 9.9351
test loss(MSE) : 121.74556
test RMSE : 10.87

In [32]:
final_gru_model.save("model_gru_last.keras")