# Import

In [3]:
import numpy as np
import pandas as pd
import optuna

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import make_scorer, mean_squared_error
from scikeras.wrappers import KerasRegressor
from bayes_opt import BayesianOptimization

import tensorflow as tf
from tensorflow.keras import regularizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.losses import mse
from tensorflow.keras.metrics import RootMeanSquaredError, MeanSquaredError
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import regularizers

# 원본 데이터 전처리

In [5]:
# 3개년 데이터 로드 (인덱스 자동추가 제외)
origin_2021 = pd.read_csv('./train_subway21.csv', index_col=0)
origin_2022 = pd.read_csv('./train_subway22.csv', index_col=0)
origin_2023 = pd.read_csv('./train_subway23.csv', index_col=0)

In [6]:
# 칼럼명 변경
origin_2021 = origin_2021.rename(columns={
    'train_subway21.tm': 'time',
    'train_subway21.line': 'line',
    'train_subway21.station_number': 'station_number',
    'train_subway21.station_name': 'station_name',
    'train_subway21.direction': 'direction',
    'train_subway21.stn': 'AWS_num',
    'train_subway21.ta': 'temp',
    'train_subway21.wd': 'wind_direction',
    'train_subway21.ws': 'wind_speed',
    'train_subway21.rn_day': 'rn_day',
    'train_subway21.rn_hr1': 'rn_hr',
    'train_subway21.hm': 'humidity',
    'train_subway21.si': 'solar',
    'train_subway21.ta_chi': 'feel_temp',
    'train_subway21.congestion': 'congestion'
})

origin_2022 = origin_2022.rename(columns={
    'train_subway22.tm': 'time',
    'train_subway22.line': 'line',
    'train_subway22.station_number': 'station_number',
    'train_subway22.station_name': 'station_name',
    'train_subway22.direction': 'direction',
    'train_subway22.stn': 'AWS_num',
    'train_subway22.ta': 'temp',
    'train_subway22.wd': 'wind_direction',
    'train_subway22.ws': 'wind_speed',
    'train_subway22.rn_day': 'rn_day',
    'train_subway22.rn_hr1': 'rn_hr',
    'train_subway22.hm': 'humidity',
    'train_subway22.si': 'solar',
    'train_subway22.ta_chi': 'feel_temp',
    'train_subway22.congestion': 'congestion'
})

origin_2023 = origin_2023.rename(columns={
    'train_subway23.tm': 'time',
    'train_subway23.line': 'line',
    'train_subway23.station_number': 'station_number',
    'train_subway23.station_name': 'station_name',
    'train_subway23.direction': 'direction',
    'train_subway23.stn': 'AWS_num',
    'train_subway23.ta': 'temp',
    'train_subway23.wd': 'wind_direction',
    'train_subway23.ws': 'wind_speed',
    'train_subway23.rn_day': 'rn_day',
    'train_subway23.rn_hr1': 'rn_hr',
    'train_subway23.hm': 'humidity',
    'train_subway23.si': 'solar',
    'train_subway23.ta_chi': 'feel_temp',
    'train_subway23.congestion': 'congestion'
})

In [7]:
# origin dataframe 통합
origin_all = pd.concat([origin_2021, origin_2022, origin_2023], ignore_index=True)
origin_all

,time,line,station_number,station_name,direction,AWS_num,temp,wind_direction,wind_speed,rn_day,rn_hr,humidity,solar,feel_temp,congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,-99.0,-99.0,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,-99.0,-99.0,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,-99.0,-99.0,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,-99.0,-99.0,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,-99.0,-99.0,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,7.0,0.0,83.1,-99.0,0.0,18
16369320,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,7.0,0.0,84.7,-99.0,-0.6,17
16369321,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,7.0,0.0,85.1,-99.0,-1.1,21
16369322,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,7.0,0.0,85.6,-99.0,-1.3,18
16369323,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,7.0,0.0,85.6,-99.0,-1.9,22

In [8]:
# 결측값 → NaN
sentinels = [-99, -99.9, -999.0]
origin_all = origin_all.replace(sentinels, np.nan)

In [9]:
print(origin_all.isnull().sum())

time                    0
line                    0
station_number          0
station_name            0
direction               0
AWS_num                 0
temp               216468
wind_direction     230786
wind_speed         230786
rn_day             351574
rn_hr              360796
humidity           844594
solar             6064242
feel_temp             352
congestion              0
dtype: int64

In [10]:
df=origin_all.copy()

In [11]:
df = df.sort_values(['AWS_num', 'time']).reset_index(drop=True)

In [12]:
target_cols = ['temp', 'wind_direction', 'wind_speed', 'rn_day', 'rn_hr', 'humidity', 'solar', 'feel_temp']
specific_cols = ['wind_direction', 'rn_day', 'rn_hr']
linear_cols = ['temp', 'wind_speed','humidity', 'solar', 'feel_temp']

# 1단계: 관측소별 ffill,bfill로 보간방식
print('1단계시 결측치 값 변화')
for col in specific_cols:
    df[col] = df.groupby('AWS_num')[col].ffill().bfill()
print(df.isnull().sum())
print('----------------------------------')

# 2단계: 관측소별 선형보간 방식
print('2단계시 결측치 값 변화')
df[linear_cols] = df.groupby('AWS_num')[linear_cols].transform(
    lambda x: x.interpolate(method='linear')
)
print(df.isnull().sum())
print('----------------------------------')

# 3단계: 경계값 처리
print('3단계시 결측치 값 변화')
for col in linear_cols:
    df[col] = df.groupby('AWS_num')[col].ffill().bfill()
print(df.isnull().sum())
print('----------------------------------')

1단계시 결측치 값 변화
time                    0
line                    0
station_number          0
station_name            0
direction               0
AWS_num                 0
temp               216468
wind_direction          0
wind_speed         230786
rn_day                  0
rn_hr                   0
humidity           844594
solar             6064242
feel_temp             352
congestion              0
dtype: int64
----------------------------------
2단계시 결측치 값 변화
time                   0
line                   0
station_number         0
station_name           0
direction              0
AWS_num                0
temp                4634
wind_direction         0
wind_speed          4636
rn_day                 0
rn_hr                  0
humidity          633392
solar               3440
feel_temp              0
congestion             0
dtype: int64
----------------------------------
3단계시 결측치 값 변화
time              0
line              0
station_number    0
station_name      0
direction         0
AWS_num           0
temp              0
wind_direction    0
wind_speed        0
rn_day            0
rn_hr             0
humidity          0
solar             0
feel_temp         0
congestion        0
dtype: int64
----------------------------------

In [13]:
# 상/하행 레이블 정의
direction_map = {'상선': 0, '하선': 1, '내선': 2, '외선':3}

# 체감온도 구간 레이블 정의
bins = [-float('inf'), -10, 5, 20, 28, float('inf')]
labels = ["0", "1", "2", "3", "4"]

# 임시 DataFrame temp_df 정의
temp_df = df.copy()

# direction을 숫자 레이블로 변환
temp_df['direction'] = temp_df['direction'].map(direction_map)

# 체감온도 단계 파생변수 추가
temp_df['feel_stage'] = pd.cut(temp_df['feel_temp'], bins=bins, labels=labels).astype(int)

In [14]:
holidays = [
    # 2021
    '20210101','20210211','20210212','20210213','20210301',
    '20210505','20210519','20210606','20210815','20210920',
    '20210921','20210922','20211003','20211009','20211225',
    # 2022
    '20220101','20220131','20220201','20220202','20220301',
    '20220309','20220505','20220508','20220601','20220606',
    '20220815','20220909','20220910','20220911','20220912',
    '20221003','20221009','20221010','20221225',
    # 2023
    '20230101','20230121','20230122','20230123','20230124',
    '20230301','20230505','20230527','20230529','20230606',
    '20230815','20230928','20230929','20230930','20231002',
    '20231003','20231009','20231225'
]
# 공휴일 리스트를 set으로 변환하여 조회 속도 향상
holidays_set = set(holidays)

# 'time' 컬럼을 datetime 객체로 변환
temp_df['time'] = pd.to_datetime(temp_df['time'], format='%Y%m%d%H')

# 'is_holiday' 컬럼 초기화 (기본값 0: 평일)
temp_df['is_holiday'] = 0

# 주말(토/일) 확인하여 1로 설정
is_weekend = (temp_df['time'].dt.dayofweek >= 5)
temp_df.loc[is_weekend, 'is_holiday'] = 1

# 공휴일 확인하여 1로 설정
is_in_holidays = temp_df['time'].dt.strftime('%Y%m%d').isin(holidays_set)
temp_df.loc[is_in_holidays, 'is_holiday'] = 1

In [15]:
temp_df = temp_df.sort_values(['station_number', 'AWS_num','direction','time']).reset_index(drop=True)
temp_df

,time,line,station_number,station_name,direction,AWS_num,temp,wind_direction,wind_speed,rn_day,rn_hr,humidity,solar,feel_temp,congestion,feel_stage,is_holiday
0,2021-01-01 00:00:00,1,150,서울역,0,419,-9.6,291.1,3.3,0.0,0.0,47.5,0.00,-12.6,0,0,1
1,2021-01-01 01:00:00,1,150,서울역,0,419,-9.7,284.6,2.0,0.0,0.0,47.5,0.00,-9.8,0,1,1
2,2021-01-01 05:00:00,1,150,서울역,0,419,-9.3,124.7,2.4,0.0,0.0,47.5,0.00,-10.3,1,0,1
3,2021-01-01 06:00:00,1,150,서울역,0,419,-9.3,126.2,1.7,0.0,0.0,47.5,0.00,-10.1,2,0,1
4,2021-01-01 07:00:00,1,150,서울역,0,419,-9.1,145.7,1.3,0.0,0.0,47.5,0.00,-9.7,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023-12-31 19:00:00,6,9006,응암S,1,400,1.4,0.0,0.0,13.5,0.5,92.1,0.03,1.3,15,1,1
16369320,2023-12-31 20:00:00,6,9006,응암S,1,400,0.8,308.8,0.5,13.5,0.5,95.3,0.03,0.7,13,1,1
16369321,2023-12-31 21:00:00,6,9006,응암S,1,400,0.4,320.6,0.1,13.5,0.5,96.2,0.03,0.2,14,1,1
16369322,2023-12-31 22:00:00,6,9006,응암S,1,400,0.0,117.6,0.1,13.5,0.5,97.1,0.03,0.0,14,1,1
16369323,2023-12-31 23:00:00,6,9006,응암S,1,400,-0.2,0.4,0.2,13.5,0.5,97.6,0.03,-0.4,12,1,1

In [16]:
# 필요한 칼럼만 추출
selected_cols = [
    'time',
    'station_number',
    'direction',
    'temp',
    'wind_speed',
    'rn_hr',
    'humidity',
    'solar',
    'congestion',
    'feel_stage',
    'is_holiday'
]

# temp_df에서 필요한 컬럼만 train_data DataFrame에 저장
train_data = temp_df[selected_cols].copy()

# station_number, direction, time 순으로 정렬
train_data = train_data.sort_values(
    by=['station_number', 'direction', 'time']
).reset_index(drop=True)

# time 제거
train_data = train_data.iloc[:, 1:]

# 완성
train_data

,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_stage,is_holiday
0,150,0,-9.6,3.3,0.0,47.5,0.00,0,0,1
1,150,0,-9.7,2.0,0.0,47.5,0.00,0,1,1
2,150,0,-9.3,2.4,0.0,47.5,0.00,1,0,1
3,150,0,-9.3,1.7,0.0,47.5,0.00,2,0,1
4,150,0,-9.1,1.3,0.0,47.5,0.00,3,1,1
...,...,...,...,...,...,...,...,...,...,...
16369319,9006,1,1.4,0.0,0.5,92.1,0.03,15,1,1
16369320,9006,1,0.8,0.5,0.5,95.3,0.03,13,1,1
16369321,9006,1,0.4,0.1,0.5,96.2,0.03,14,1,1
16369322,9006,1,0.0,0.1,0.5,97.1,0.03,14,1,1
16369323,9006,1,-0.2,0.2,0.5,97.6,0.03,12,1,1

## 슬라이딩 윈도우

In [18]:
def extract_inputoutput_shift(df, lookback_time=2, predict_time=1):
    # 과거 시점별 피처 생성
    feat_dfs = []
    for t in range(lookback_time):
        tmp = df.shift(t)
        feat_dfs.append(tmp)
    X = pd.concat(feat_dfs, axis=1)

    # 예측 대상(타깃) 생성
    y = df[['congestion']].shift(-predict_time)

    # NaN 제거 및 인덱스 리셋
    valid_idx = X.dropna().index.intersection(y.dropna().index)
    X = X.loc[valid_idx].reset_index(drop=True)
    y = y.loc[valid_idx].reset_index(drop=True)

    print("X, Y 데이터 분류 완료")
    return X, y

In [19]:
x, t = extract_inputoutput_shift(train_data)
x

X, Y 데이터 분류 완료

,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_stage,is_holiday,station_number,direction,temp,wind_speed,rn_hr,humidity,solar,congestion,feel_stage,is_holiday
0,150,0,-9.7,2.0,0.0,47.5,0.00,0,1,1,150.0,0.0,-9.6,3.3,0.0,47.5,0.00,0.0,0.0,1.0
1,150,0,-9.3,2.4,0.0,47.5,0.00,1,0,1,150.0,0.0,-9.7,2.0,0.0,47.5,0.00,0.0,1.0,1.0
2,150,0,-9.3,1.7,0.0,47.5,0.00,2,0,1,150.0,0.0,-9.3,2.4,0.0,47.5,0.00,1.0,0.0,1.0
3,150,0,-9.1,1.3,0.0,47.5,0.00,3,1,1,150.0,0.0,-9.3,1.7,0.0,47.5,0.00,2.0,0.0,1.0
4,150,0,-8.5,0.6,0.0,47.5,0.00,3,1,1,150.0,0.0,-9.1,1.3,0.0,47.5,0.00,3.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369317,9006,1,2.6,0.3,0.5,86.6,0.03,19,1,1,9006.0,1.0,4.6,0.7,0.5,76.2,0.26,18.0,1.0,1.0
16369318,9006,1,1.4,0.0,0.5,92.1,0.03,15,1,1,9006.0,1.0,2.6,0.3,0.5,86.6,0.03,19.0,1.0,1.0
16369319,9006,1,0.8,0.5,0.5,95.3,0.03,13,1,1,9006.0,1.0,1.4,0.0,0.5,92.1,0.03,15.0,1.0,1.0
16369320,9006,1,0.4,0.1,0.5,96.2,0.03,14,1,1,9006.0,1.0,0.8,0.5,0.5,95.3,0.03,13.0,1.0,1.0
16369321,9006,1,0.0,0.1,0.5,97.1,0.03,14,1,1,9006.0,1.0,0.4,0.1,0.5,96.2,0.03,14.0,1.0,1.0

In [20]:
t

          congestion
0                1.0
1                2.0
2                3.0
3                3.0
4                5.0
...              ...
16369317        15.0
16369318        13.0
16369319        14.0
16369320        14.0
16369321        12.0

[16369322 rows x 1 columns]

In [21]:
x_train, x_test, t_train, t_test = train_test_split(x, t, test_size=0.2, shuffle=False)

print('x_train shape :', x_train.shape)
print('t_train shape :', t_train.shape)
print('x_test shape :', x_test.shape)
print('t_test shape :', t_test.shape)

x_train shape : (13095457, 20)
t_train shape : (13095457, 1)
x_test shape : (3273865, 20)
t_test shape : (3273865, 1)

In [22]:
timesteps = 2
feature = 10

x_train = np.array(x_train)
x_train = x_train.reshape(x_train.shape[0], timesteps, feature)

x_test = np.array(x_test)
x_test = x_test.reshape(x_test.shape[0], timesteps, feature)

t_train = np.array(t_train)
t_test = np.array(t_test)

print('reshape 후 x_train shape :', x_train.shape)
print('t_train shape :', t_train.shape)
print('reshape 후 x_test shape :', x_test.shape)
print('t_test shape :', t_test.shape)

reshape 후 x_train shape : (13095457, 2, 10)
t_train shape : (13095457, 1)
reshape 후 x_test shape : (3273865, 2, 10)
t_test shape : (3273865, 1)

In [23]:
def lstm_model(cell_size=128, learning_rate=0.001):
    timesteps = 2
    feature = 10
    model = Sequential(name='congestion_lstm_2')
    model.add(LSTM(cell_size, input_shape=(timesteps, feature), return_sequences=True,
                  kernel_regularizer=regularizers.l2(0.001)))
    model.add(LSTM(cell_size, kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dropout(0.2))
    model.add(Dense(1))
    model.compile(loss='mse', optimizer=Adam(learning_rate=learning_rate), metrics=[RootMeanSquaredError()])
    return model

In [24]:
temp_grue = lstm_model()
temp_grue.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "congestion_lstm_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 2, 128)         │        71,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 128)            │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 202,881 (792.50 KB)

 Trainable params: 202,881 (792.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
early_stopping = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

# 성능 평가 함수
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))
rmse_scorer = make_scorer(rmse, greater_is_better=False)

# 데이터가 너무 많아 약 20%만 추출하여 하이퍼파라미터를 탐색하도록
x_train_subset, _, t_train_subset, _ = train_test_split(
    x_train, t_train, train_size=0.2, shuffle=False , random_state=42
)

def objective(trial):
    cell_size = trial.suggest_categorical('cell_size', [64, 128])
    learning_rate = trial.suggest_float('learning_rate', 5e-4, 1e-3, log=True)
    epochs = trial.suggest_int('epochs', 10, 20)
    batch_size = trial.suggest_categorical('batch_size', [256, 512])

    # scikeras로 래핑
    Congestion_LSTM_MODEL = KerasRegressor(
        model=lstm_model,
        cell_size=cell_size,
        learning_rate=learning_rate,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[early_stopping]
    )
    # cross_val_score에서 cv=2와 데이터 직접 전달
    scores = cross_val_score(Congestion_LSTM_MODEL, x_train_subset, t_train_subset, scoring=rmse_scorer, cv=2)
    return -scores.mean()

In [26]:
bayesian_study = optuna.create_study(direction='minimize')

bayesian_study.optimize(objective, n_trials=20)

[I 2025-06-17 14:05:26,198] A new study created in memory with name: no-name-ba83d571-af6c-4eac-995f-daf8cbc58786

Epoch 1/17

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 604.4943 - root_mean_squared_error: 24.1884
Epoch 2/17
  34/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 203.2561 - root_mean_squared_error: 14.2440

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 189.6892 - root_mean_squared_error: 13.7586
Epoch 3/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 156.9973 - root_mean_squared_error: 12.5128
Epoch 4/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 142.4038 - root_mean_squared_error: 11.9129
Epoch 5/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 135.8146 - root_mean_squared_error: 11.6308
Epoch 6/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 131.7077 - root_mean_squared_error: 11.4504
Epoch 7/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 127.7249 - root_mean_squared_error: 11.2729
Epoch 8/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 124.1553 - root_mean_squared_error: 11.1111
Epoch 9/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 121.6864 - root_mean_squared_error: 10.9971
Epoch 10/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 118.8189 - root_mean_squared_error: 10.8638
Epoch 11/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 116.9613 - root_mean_squared_error: 10.7757
Epoch 12/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 115.4410 - root_mean_squared_error: 10.7028
Epoch 13/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 113.5605 - root_mean_squared_error: 10.6125
Epoch 14/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 111.7753 - root_mean_squared_error: 10.5260
Epoch 15/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 111.0919 - root_mean_squared_error: 10.4916
Epoch 16/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 110.7093 - root_mean_squared_error: 10.4715
Epoch 17/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 109.4216 - root_mean_squared_error: 10.4078
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step
Epoch 1/17

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 249.3743 - root_mean_squared_error: 15.3462
Epoch 2/17
  38/2558 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 76.9712 - root_mean_squared_error: 8.7596

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 75.4500 - root_mean_squared_error: 8.6718
Epoch 3/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 68.0473 - root_mean_squared_error: 8.2315
Epoch 4/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 64.0239 - root_mean_squared_error: 7.9805
Epoch 5/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 61.5721 - root_mean_squared_error: 7.8224
Epoch 6/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 59.6817 - root_mean_squared_error: 7.6976
Epoch 7/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 58.0873 - root_mean_squared_error: 7.5904
Epoch 8/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 57.3207 - root_mean_squared_error: 7.5372
Epoch 9/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 56.5009 - root_mean_squared_error: 7.4802
Epoch 10/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 55.3266 - root_mean_squared_error: 7.3993
Epoch 11/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 54.7271 - root_mean_squared_error: 7.3568
Epoch 12/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 54.1430 - root_mean_squared_error: 7.3151
Epoch 13/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 53.8082 - root_mean_squared_error: 7.2905
Epoch 14/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 53.3569 - root_mean_squared_error: 7.2579
Epoch 15/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.8265 - root_mean_squared_error: 7.2196
Epoch 16/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.3628 - root_mean_squared_error: 7.1857
Epoch 17/17
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.1724 - root_mean_squared_error: 7.1709
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

[I 2025-06-17 14:12:36,291] Trial 0 finished with value: 15.52892655830502 and parameters: {'cell_size': 64, 'learning_rate': 0.0005200028289328, 'epochs': 17, 'batch_size': 512}. Best is trial 0 with value: 15.52892655830502.

Epoch 1/19

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 295.3770 - root_mean_squared_error: 16.7601
Epoch 2/19
  25/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 140.7911 - root_mean_squared_error: 11.8293

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 141.0133 - root_mean_squared_error: 11.8398
Epoch 3/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 131.3929 - root_mean_squared_error: 11.4156
Epoch 4/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 123.6865 - root_mean_squared_error: 11.0618
Epoch 5/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 117.9581 - root_mean_squared_error: 10.7876
Epoch 6/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 112.8709 - root_mean_squared_error: 10.5373
Epoch 7/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 109.9558 - root_mean_squared_error: 10.3874
Epoch 8/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 106.9301 - root_mean_squared_error: 10.2305
Epoch 9/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 104.6099 - root_mean_squared_error: 10.1077
Epoch 10/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 102.8795 - root_mean_squared_error: 10.0136
Epoch 11/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 101.5393 - root_mean_squared_error: 9.9389
Epoch 12/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 99.3923 - root_mean_squared_error: 9.8232
Epoch 13/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 97.8079 - root_mean_squared_error: 9.7351
Epoch 14/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 96.5135 - root_mean_squared_error: 9.6619
Epoch 15/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 95.0666 - root_mean_squared_error: 9.5803
Epoch 16/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 93.9241 - root_mean_squared_error: 9.5145
Epoch 17/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 92.3829 - root_mean_squared_error: 9.4273
Epoch 18/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 91.4140 - root_mean_squared_error: 9.3701
Epoch 19/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 90.8407 - root_mean_squared_error: 9.3338
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step
Epoch 1/19

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - loss: 120.0202 - root_mean_squared_error: 10.6329
Epoch 2/19
  30/5116 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - loss: 64.4209 - root_mean_squared_error: 7.9905

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 63.3442 - root_mean_squared_error: 7.9241
Epoch 3/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 58.6714 - root_mean_squared_error: 7.6124
Epoch 4/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 55.9552 - root_mean_squared_error: 7.4206
Epoch 5/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 54.0566 - root_mean_squared_error: 7.2830
Epoch 6/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 52.7839 - root_mean_squared_error: 7.1869
Epoch 7/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 51.4273 - root_mean_squared_error: 7.0851
Epoch 8/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 50.8524 - root_mean_squared_error: 7.0380
Epoch 9/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 50.0027 - root_mean_squared_error: 6.9717
Epoch 10/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 49.0782 - root_mean_squared_error: 6.8996
Epoch 11/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 48.8729 - root_mean_squared_error: 6.8802
Epoch 12/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 48.3886 - root_mean_squared_error: 6.8403
Epoch 13/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 48.1232 - root_mean_squared_error: 6.8169
Epoch 14/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 47.7033 - root_mean_squared_error: 6.7822
Epoch 15/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 47.4017 - root_mean_squared_error: 6.7570
Epoch 16/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 46.9395 - root_mean_squared_error: 6.7204
Epoch 17/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 46.2183 - root_mean_squared_error: 6.6637
Epoch 18/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 46.2050 - root_mean_squared_error: 6.6602
Epoch 19/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 45.8987 - root_mean_squared_error: 6.6348
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step

[I 2025-06-17 14:32:18,543] Trial 1 finished with value: 13.171561551937005 and parameters: {'cell_size': 128, 'learning_rate': 0.0008402891378159892, 'epochs': 19, 'batch_size': 256}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/15

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 347.3572 - root_mean_squared_error: 18.1626
Epoch 2/15
  21/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 153.7241 - root_mean_squared_error: 12.3736

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 145.7444 - root_mean_squared_error: 12.0452
Epoch 3/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 133.3893 - root_mean_squared_error: 11.5132
Epoch 4/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 126.8965 - root_mean_squared_error: 11.2205
Epoch 5/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 121.7689 - root_mean_squared_error: 10.9822
Epoch 6/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 116.4555 - root_mean_squared_error: 10.7303
Epoch 7/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 112.8274 - root_mean_squared_error: 10.5527
Epoch 8/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 110.4115 - root_mean_squared_error: 10.4304
Epoch 9/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 108.1590 - root_mean_squared_error: 10.3149
Epoch 10/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 105.7978 - root_mean_squared_error: 10.1928
Epoch 11/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 103.9136 - root_mean_squared_error: 10.0933
Epoch 12/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 101.8981 - root_mean_squared_error: 9.9866
Epoch 13/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 10ms/step - loss: 100.6971 - root_mean_squared_error: 9.9206
Epoch 14/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 10ms/step - loss: 98.8460 - root_mean_squared_error: 9.8214
Epoch 15/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 98.1032 - root_mean_squared_error: 9.7783
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step
Epoch 1/15

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 141.0527 - root_mean_squared_error: 11.4909
Epoch 2/15
  15/2558 ━━━━━━━━━━━━━━━━━━━━ 29s 12ms/step - loss: 66.4940 - root_mean_squared_error: 8.1228

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 64.3660 - root_mean_squared_error: 7.9937
Epoch 3/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 26s 10ms/step - loss: 59.3094 - root_mean_squared_error: 7.6623
Epoch 4/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 56.2583 - root_mean_squared_error: 7.4525
Epoch 5/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 54.3886 - root_mean_squared_error: 7.3191
Epoch 6/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 53.2496 - root_mean_squared_error: 7.2345
Epoch 7/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 52.1883 - root_mean_squared_error: 7.1548
Epoch 8/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 27s 11ms/step - loss: 51.4990 - root_mean_squared_error: 7.1010
Epoch 9/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 26s 10ms/step - loss: 51.0675 - root_mean_squared_error: 7.0657
Epoch 10/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 28s 11ms/step - loss: 50.2859 - root_mean_squared_error: 7.0054
Epoch 11/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 49.7669 - root_mean_squared_error: 6.9640
Epoch 12/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 49.3146 - root_mean_squared_error: 6.9272
Epoch 13/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 48.7277 - root_mean_squared_error: 6.8808
Epoch 14/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 48.3315 - root_mean_squared_error: 6.8483
Epoch 15/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 48.1694 - root_mean_squared_error: 6.8328
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step

[I 2025-06-17 14:44:42,572] Trial 2 finished with value: 15.025316448342199 and parameters: {'cell_size': 128, 'learning_rate': 0.0009611283679045015, 'epochs': 15, 'batch_size': 512}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/19

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 38s 7ms/step - loss: 339.0895 - root_mean_squared_error: 17.9517
Epoch 2/19
  22/5116 ━━━━━━━━━━━━━━━━━━━━ 37s 7ms/step - loss: 142.4350 - root_mean_squared_error: 11.9051

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 38s 7ms/step - loss: 142.1696 - root_mean_squared_error: 11.8970
Epoch 3/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 38s 7ms/step - loss: 131.3277 - root_mean_squared_error: 11.4251
Epoch 4/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 37s 7ms/step - loss: 123.5218 - root_mean_squared_error: 11.0714
Epoch 5/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 118.7308 - root_mean_squared_error: 10.8461
Epoch 6/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 115.2764 - root_mean_squared_error: 10.6797
Epoch 7/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 112.1911 - root_mean_squared_error: 10.5283
Epoch 8/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 108.4867 - root_mean_squared_error: 10.3452
Epoch 9/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 106.1075 - root_mean_squared_error: 10.2242
Epoch 10/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 105.1687 - root_mean_squared_error: 10.1727
Epoch 11/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 102.8529 - root_mean_squared_error: 10.0530
Epoch 12/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 100.8812 - root_mean_squared_error: 9.9496
Epoch 13/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 99.2107 - root_mean_squared_error: 9.8604
Epoch 14/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 98.3424 - root_mean_squared_error: 9.8114
Epoch 15/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 96.7090 - root_mean_squared_error: 9.7229
Epoch 16/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 95.8576 - root_mean_squared_error: 9.6742
Epoch 17/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 94.6444 - root_mean_squared_error: 9.6064
Epoch 18/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 93.5134 - root_mean_squared_error: 9.5426
Epoch 19/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 92.6937 - root_mean_squared_error: 9.4950
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/19

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 129.8218 - root_mean_squared_error: 11.0492
Epoch 2/19
  29/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 67.5914 - root_mean_squared_error: 8.1935

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 63.6339 - root_mean_squared_error: 7.9481
Epoch 3/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 59.1975 - root_mean_squared_error: 7.6577
Epoch 4/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 56.6101 - root_mean_squared_error: 7.4801
Epoch 5/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 54.3192 - root_mean_squared_error: 7.3194
Epoch 6/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 52.8927 - root_mean_squared_error: 7.2158
Epoch 7/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 52.0000 - root_mean_squared_error: 7.1490
Epoch 8/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 50.7478 - root_mean_squared_error: 7.0566
Epoch 9/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 49.9172 - root_mean_squared_error: 6.9933
Epoch 10/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 48.8990 - root_mean_squared_error: 6.9163
Epoch 11/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 48.3444 - root_mean_squared_error: 6.8722
Epoch 12/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 47.8471 - root_mean_squared_error: 6.8321
Epoch 13/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 47.2182 - root_mean_squared_error: 6.7822
Epoch 14/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 46.9088 - root_mean_squared_error: 6.7561
Epoch 15/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 46.4264 - root_mean_squared_error: 6.7172
Epoch 16/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 46.0251 - root_mean_squared_error: 6.6844
Epoch 17/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 45.7031 - root_mean_squared_error: 6.6575
Epoch 18/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 45.3229 - root_mean_squared_error: 6.6264
Epoch 19/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 44.9518 - root_mean_squared_error: 6.5959
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 15:04:11,031] Trial 3 finished with value: 14.125298115380353 and parameters: {'cell_size': 128, 'learning_rate': 0.0005088092729951766, 'epochs': 19, 'batch_size': 256}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/16

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 488.4498 - root_mean_squared_error: 21.6187
Epoch 2/16
  36/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 178.3439 - root_mean_squared_error: 13.3401

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 172.1292 - root_mean_squared_error: 13.1050
Epoch 3/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 147.7398 - root_mean_squared_error: 12.1356
Epoch 4/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 139.3943 - root_mean_squared_error: 11.7829
Epoch 5/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 134.0579 - root_mean_squared_error: 11.5507
Epoch 6/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 130.0820 - root_mean_squared_error: 11.3737
Epoch 7/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 127.1916 - root_mean_squared_error: 11.2423
Epoch 8/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 124.1527 - root_mean_squared_error: 11.1030
Epoch 9/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 121.3784 - root_mean_squared_error: 10.9741
Epoch 10/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 119.9364 - root_mean_squared_error: 10.9049
Epoch 11/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 117.8210 - root_mean_squared_error: 10.8043
Epoch 12/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 116.2632 - root_mean_squared_error: 10.7286
Epoch 13/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 115.4652 - root_mean_squared_error: 10.6880
Epoch 14/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 114.2357 - root_mean_squared_error: 10.6272
Epoch 15/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 112.9940 - root_mean_squared_error: 10.5655
Epoch 16/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 112.5323 - root_mean_squared_error: 10.5404
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step
Epoch 1/16

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 197.0015 - root_mean_squared_error: 13.5823
Epoch 2/16
  32/2558 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 70.6490 - root_mean_squared_error: 8.3864

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 69.7069 - root_mean_squared_error: 8.3288
Epoch 3/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 63.6988 - root_mean_squared_error: 7.9546
Epoch 4/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 60.5640 - root_mean_squared_error: 7.7503
Epoch 5/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 58.6704 - root_mean_squared_error: 7.6224
Epoch 6/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 57.4661 - root_mean_squared_error: 7.5388
Epoch 7/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 56.5128 - root_mean_squared_error: 7.4716
Epoch 8/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 55.7382 - root_mean_squared_error: 7.4163
Epoch 9/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 54.9401 - root_mean_squared_error: 7.3596
Epoch 10/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 54.1067 - root_mean_squared_error: 7.3001
Epoch 11/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 53.2662 - root_mean_squared_error: 7.2398
Epoch 12/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.9225 - root_mean_squared_error: 7.2135
Epoch 13/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 52.4661 - root_mean_squared_error: 7.1795
Epoch 14/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 51.8775 - root_mean_squared_error: 7.1363
Epoch 15/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 51.7394 - root_mean_squared_error: 7.1245
Epoch 16/16
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 51.3953 - root_mean_squared_error: 7.0983
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step

[I 2025-06-17 15:10:28,218] Trial 4 finished with value: 14.985311478681368 and parameters: {'cell_size': 64, 'learning_rate': 0.0008978574503507152, 'epochs': 16, 'batch_size': 512}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/13

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 446.0758 - root_mean_squared_error: 20.6256
Epoch 2/13
  56/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 159.9825 - root_mean_squared_error: 12.6328

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 154.9201 - root_mean_squared_error: 12.4294
Epoch 3/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 140.5830 - root_mean_squared_error: 11.8341
Epoch 4/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 133.6491 - root_mean_squared_error: 11.5329
Epoch 5/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 127.9785 - root_mean_squared_error: 11.2802
Epoch 6/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 123.6702 - root_mean_squared_error: 11.0833
Epoch 7/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 120.6710 - root_mean_squared_error: 10.9429
Epoch 8/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 117.9948 - root_mean_squared_error: 10.8158
Epoch 9/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 116.2792 - root_mean_squared_error: 10.7322
Epoch 10/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 114.5108 - root_mean_squared_error: 10.6456
Epoch 11/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 112.5084 - root_mean_squared_error: 10.5474
Epoch 12/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 111.7716 - root_mean_squared_error: 10.5086
Epoch 13/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 110.0305 - root_mean_squared_error: 10.4217
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 4s 856us/step
Epoch 1/13

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 173.0229 - root_mean_squared_error: 12.7327
Epoch 2/13
  57/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 71.9334 - root_mean_squared_error: 8.4607

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 67.8523 - root_mean_squared_error: 8.2175
Epoch 3/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 63.6011 - root_mean_squared_error: 7.9500
Epoch 4/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 60.4293 - root_mean_squared_error: 7.7430
Epoch 5/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 58.8639 - root_mean_squared_error: 7.6361
Epoch 6/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 57.5291 - root_mean_squared_error: 7.5437
Epoch 7/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 56.3612 - root_mean_squared_error: 7.4616
Epoch 8/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 55.4246 - root_mean_squared_error: 7.3946
Epoch 9/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 54.6454 - root_mean_squared_error: 7.3379
Epoch 10/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 54.2479 - root_mean_squared_error: 7.3072
Epoch 11/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 53.3382 - root_mean_squared_error: 7.2415
Epoch 12/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 52.9009 - root_mean_squared_error: 7.2084
Epoch 13/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - loss: 52.3917 - root_mean_squared_error: 7.1705
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 4s 860us/step

[I 2025-06-17 15:16:28,843] Trial 5 finished with value: 14.463898496333144 and parameters: {'cell_size': 64, 'learning_rate': 0.0005788130253324479, 'epochs': 13, 'batch_size': 256}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/13

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 394.0054 - root_mean_squared_error: 19.3590
Epoch 2/13
  22/2558 ━━━━━━━━━━━━━━━━━━━━ 19s 8ms/step - loss: 159.5099 - root_mean_squared_error: 12.6067

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 151.6429 - root_mean_squared_error: 12.2883
Epoch 3/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 135.4603 - root_mean_squared_error: 11.6042
Epoch 4/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 126.3885 - root_mean_squared_error: 11.2009
Epoch 5/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 121.5632 - root_mean_squared_error: 10.9779
Epoch 6/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 117.2293 - root_mean_squared_error: 10.7730
Epoch 7/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 113.1149 - root_mean_squared_error: 10.5748
Epoch 8/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 110.0789 - root_mean_squared_error: 10.4247
Epoch 9/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 107.7575 - root_mean_squared_error: 10.3074
Epoch 10/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 105.5776 - root_mean_squared_error: 10.1958
Epoch 11/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 104.1082 - root_mean_squared_error: 10.1185
Epoch 12/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 102.4065 - root_mean_squared_error: 10.0293
Epoch 13/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 101.0451 - root_mean_squared_error: 9.9565
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step
Epoch 1/13

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 152.5210 - root_mean_squared_error: 11.9596
Epoch 2/13
  12/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 67.9450 - root_mean_squared_error: 8.2181

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 65.6115 - root_mean_squared_error: 8.0736
Epoch 3/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 10ms/step - loss: 60.3544 - root_mean_squared_error: 7.7354
Epoch 4/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 56.6332 - root_mean_squared_error: 7.4851
Epoch 5/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 54.4947 - root_mean_squared_error: 7.3354
Epoch 6/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 53.4880 - root_mean_squared_error: 7.2619
Epoch 7/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 51.9847 - root_mean_squared_error: 7.1537
Epoch 8/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 51.3145 - root_mean_squared_error: 7.1032
Epoch 9/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 50.6666 - root_mean_squared_error: 7.0539
Epoch 10/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 49.9671 - root_mean_squared_error: 7.0006
Epoch 11/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 49.4510 - root_mean_squared_error: 6.9604
Epoch 12/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 49.0169 - root_mean_squared_error: 6.9257
Epoch 13/13
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 48.2825 - root_mean_squared_error: 6.8692
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step

[I 2025-06-17 15:26:18,502] Trial 6 finished with value: 15.175280022071298 and parameters: {'cell_size': 128, 'learning_rate': 0.0006794821524237714, 'epochs': 13, 'batch_size': 512}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 438.0481 - root_mean_squared_error: 20.4285
Epoch 2/20
  55/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 164.0193 - root_mean_squared_error: 12.7924

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 159.3667 - root_mean_squared_error: 12.6071
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 144.0611 - root_mean_squared_error: 11.9794
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 137.4675 - root_mean_squared_error: 11.6955
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 132.4089 - root_mean_squared_error: 11.4717
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 128.2244 - root_mean_squared_error: 11.2826
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 124.0818 - root_mean_squared_error: 11.0924
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 120.4846 - root_mean_squared_error: 10.9241
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 119.1424 - root_mean_squared_error: 10.8578
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 115.9898 - root_mean_squared_error: 10.7072
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 114.8502 - root_mean_squared_error: 10.6494
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 113.1660 - root_mean_squared_error: 10.5659
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 112.1301 - root_mean_squared_error: 10.5126
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 110.8221 - root_mean_squared_error: 10.4464
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 110.1885 - root_mean_squared_error: 10.4122
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 108.9421 - root_mean_squared_error: 10.3484
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 107.8714 - root_mean_squared_error: 10.2929
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 106.6941 - root_mean_squared_error: 10.2319
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 106.3553 - root_mean_squared_error: 10.2112
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 105.2178 - root_mean_squared_error: 10.1515
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 5s 865us/step
Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 169.6310 - root_mean_squared_error: 12.6131
Epoch 2/20
  54/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 69.3909 - root_mean_squared_error: 8.3119

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 68.3463 - root_mean_squared_error: 8.2483
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 63.9294 - root_mean_squared_error: 7.9715
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 61.0060 - root_mean_squared_error: 7.7806
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 59.5751 - root_mean_squared_error: 7.6828
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 58.1374 - root_mean_squared_error: 7.5843
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 56.9234 - root_mean_squared_error: 7.4998
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 56.0251 - root_mean_squared_error: 7.4356
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 55.2744 - root_mean_squared_error: 7.3811
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 54.3343 - root_mean_squared_error: 7.3132
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 54.0874 - root_mean_squared_error: 7.2927
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 53.3404 - root_mean_squared_error: 7.2376
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 52.6190 - root_mean_squared_error: 7.1842
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 52.1128 - root_mean_squared_error: 7.1456
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 51.7676 - root_mean_squared_error: 7.1186
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 51.4277 - root_mean_squared_error: 7.0918
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 50.9728 - root_mean_squared_error: 7.0569
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 50.3781 - root_mean_squared_error: 7.0123
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 50.2210 - root_mean_squared_error: 6.9986
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 49.8935 - root_mean_squared_error: 6.9729
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 5s 881us/step

[I 2025-06-17 15:36:20,755] Trial 7 finished with value: 15.285709328679191 and parameters: {'cell_size': 64, 'learning_rate': 0.0006186328320717856, 'epochs': 20, 'batch_size': 256}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/15

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 418.6177 - root_mean_squared_error: 19.9497
Epoch 2/15
  18/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 155.7320 - root_mean_squared_error: 12.4576

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 155.4612 - root_mean_squared_error: 12.4463
Epoch 3/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 135.6998 - root_mean_squared_error: 11.6198
Epoch 4/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 127.9490 - root_mean_squared_error: 11.2772
Epoch 5/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 121.4363 - root_mean_squared_error: 10.9807
Epoch 6/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 116.9767 - root_mean_squared_error: 10.7719
Epoch 7/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 44s 10ms/step - loss: 113.4630 - root_mean_squared_error: 10.6041
Epoch 8/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 29s 11ms/step - loss: 110.4397 - root_mean_squared_error: 10.4571
Epoch 9/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 108.7664 - root_mean_squared_error: 10.3732
Epoch 10/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 107.1486 - root_mean_squared_error: 10.2915
Epoch 11/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 9ms/step - loss: 105.2309 - root_mean_squared_error: 10.1947
Epoch 12/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 9ms/step - loss: 104.1513 - root_mean_squared_error: 10.1381
Epoch 13/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 102.5155 - root_mean_squared_error: 10.0538
Epoch 14/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 25s 10ms/step - loss: 101.5083 - root_mean_squared_error: 10.0001
Epoch 15/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 24s 10ms/step - loss: 100.0145 - root_mean_squared_error: 9.9220
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step
Epoch 1/15

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 23s 8ms/step - loss: 162.2921 - root_mean_squared_error: 12.3082
Epoch 2/15
  21/2558 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 67.0877 - root_mean_squared_error: 8.1653

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 26s 10ms/step - loss: 66.4491 - root_mean_squared_error: 8.1263
Epoch 3/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 60.5987 - root_mean_squared_error: 7.7532
Epoch 4/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 57.9345 - root_mean_squared_error: 7.5745
Epoch 5/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 55.4731 - root_mean_squared_error: 7.4055
Epoch 6/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 53.9091 - root_mean_squared_error: 7.2951
Epoch 7/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 52.9980 - root_mean_squared_error: 7.2287
Epoch 8/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 51.9433 - root_mean_squared_error: 7.1521
Epoch 9/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 51.0634 - root_mean_squared_error: 7.0874
Epoch 10/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 50.4490 - root_mean_squared_error: 7.0409
Epoch 11/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 49.8132 - root_mean_squared_error: 6.9927
Epoch 12/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 49.3989 - root_mean_squared_error: 6.9602
Epoch 13/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 48.4477 - root_mean_squared_error: 6.8890
Epoch 14/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 8ms/step - loss: 48.3988 - root_mean_squared_error: 6.8829
Epoch 15/15
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 22s 9ms/step - loss: 47.8411 - root_mean_squared_error: 6.8397
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step

[I 2025-06-17 15:48:33,528] Trial 8 finished with value: 15.165843251289498 and parameters: {'cell_size': 128, 'learning_rate': 0.0005609434686638499, 'epochs': 15, 'batch_size': 512}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/18

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 535.1976 - root_mean_squared_error: 22.6756
Epoch 2/18
  36/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 176.8450 - root_mean_squared_error: 13.2841

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 176.5932 - root_mean_squared_error: 13.2736
Epoch 3/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 149.7619 - root_mean_squared_error: 12.2166
Epoch 4/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 139.5151 - root_mean_squared_error: 11.7860
Epoch 5/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 134.2676 - root_mean_squared_error: 11.5577
Epoch 6/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 129.9586 - root_mean_squared_error: 11.3661
Epoch 7/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 125.9539 - root_mean_squared_error: 11.1847
Epoch 8/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 123.1540 - root_mean_squared_error: 11.0546
Epoch 9/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 121.2280 - root_mean_squared_error: 10.9629
Epoch 10/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 118.6009 - root_mean_squared_error: 10.8384
Epoch 11/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 117.0734 - root_mean_squared_error: 10.7639
Epoch 12/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 115.6071 - root_mean_squared_error: 10.6921
Epoch 13/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 114.9456 - root_mean_squared_error: 10.6574
Epoch 14/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 113.4128 - root_mean_squared_error: 10.5823
Epoch 15/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 112.0066 - root_mean_squared_error: 10.5126
Epoch 16/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 111.3410 - root_mean_squared_error: 10.4779
Epoch 17/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 109.6943 - root_mean_squared_error: 10.3960
Epoch 18/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 108.9544 - root_mean_squared_error: 10.3576
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
Epoch 1/18

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 206.2582 - root_mean_squared_error: 13.9289
Epoch 2/18
  34/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 71.9689 - root_mean_squared_error: 8.4662

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 71.0618 - root_mean_squared_error: 8.4114
Epoch 3/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 65.3293 - root_mean_squared_error: 8.0605
Epoch 4/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 62.4460 - root_mean_squared_error: 7.8767
Epoch 5/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 60.4417 - root_mean_squared_error: 7.7453
Epoch 6/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 58.8913 - root_mean_squared_error: 7.6413
Epoch 7/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 57.4362 - root_mean_squared_error: 7.5425
Epoch 8/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 56.7213 - root_mean_squared_error: 7.4922
Epoch 9/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 55.7724 - root_mean_squared_error: 7.4258
Epoch 10/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 55.0817 - root_mean_squared_error: 7.3764
Epoch 11/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 54.5833 - root_mean_squared_error: 7.3399
Epoch 12/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 54.3258 - root_mean_squared_error: 7.3197
Epoch 13/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 53.9715 - root_mean_squared_error: 7.2928
Epoch 14/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 53.2515 - root_mean_squared_error: 7.2406
Epoch 15/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.8811 - root_mean_squared_error: 7.2125
Epoch 16/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.4657 - root_mean_squared_error: 7.1812
Epoch 17/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 52.1436 - root_mean_squared_error: 7.1561
Epoch 18/18
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 51.7651 - root_mean_squared_error: 7.1273
2558/2558 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step

[I 2025-06-17 15:55:49,482] Trial 9 finished with value: 15.033411257731991 and parameters: {'cell_size': 64, 'learning_rate': 0.0007992870476306132, 'epochs': 18, 'batch_size': 512}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/10

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 291.6391 - root_mean_squared_error: 16.6806
Epoch 2/10
  26/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 142.0862 - root_mean_squared_error: 11.8883

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 141.1724 - root_mean_squared_error: 11.8476
Epoch 3/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 130.6398 - root_mean_squared_error: 11.3830
Epoch 4/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 123.7163 - root_mean_squared_error: 11.0643
Epoch 5/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 118.0407 - root_mean_squared_error: 10.7959
Epoch 6/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 114.5432 - root_mean_squared_error: 10.6243
Epoch 7/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 111.2025 - root_mean_squared_error: 10.4579
Epoch 8/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 108.7943 - root_mean_squared_error: 10.3338
Epoch 9/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 106.3170 - root_mean_squared_error: 10.2055
Epoch 10/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 104.2453 - root_mean_squared_error: 10.0958
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/10

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 118.2791 - root_mean_squared_error: 10.5629
Epoch 2/10
  28/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 61.0943 - root_mean_squared_error: 7.7686

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 62.5847 - root_mean_squared_error: 7.8741
Epoch 3/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 58.4150 - root_mean_squared_error: 7.5927
Epoch 4/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 55.6121 - root_mean_squared_error: 7.3968
Epoch 5/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 53.9053 - root_mean_squared_error: 7.2730
Epoch 6/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 52.8747 - root_mean_squared_error: 7.1954
Epoch 7/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.9930 - root_mean_squared_error: 7.1285
Epoch 8/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.2556 - root_mean_squared_error: 7.0714
Epoch 9/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.7773 - root_mean_squared_error: 7.0334
Epoch 10/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 50.0292 - root_mean_squared_error: 6.9758
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step

[I 2025-06-17 16:06:32,826] Trial 10 finished with value: 14.686534903165533 and parameters: {'cell_size': 128, 'learning_rate': 0.0007993007175713108, 'epochs': 10, 'batch_size': 256}. Best is trial 1 with value: 13.171561551937005.

Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 294.5381 - root_mean_squared_error: 16.7352
Epoch 2/20
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 150.5150 - root_mean_squared_error: 12.2370

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 140.6175 - root_mean_squared_error: 11.8239
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 130.2342 - root_mean_squared_error: 11.3663
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 124.0966 - root_mean_squared_error: 11.0833
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 119.6832 - root_mean_squared_error: 10.8724
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 114.4666 - root_mean_squared_error: 10.6199
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 110.9076 - root_mean_squared_error: 10.4420
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 108.3687 - root_mean_squared_error: 10.3111
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 105.4144 - root_mean_squared_error: 10.1583
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 103.4136 - root_mean_squared_error: 10.0504
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 101.9799 - root_mean_squared_error: 9.9708
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 99.2881 - root_mean_squared_error: 9.8272
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 98.0114 - root_mean_squared_error: 9.7542
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 96.7456 - root_mean_squared_error: 9.6818
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 95.5364 - root_mean_squared_error: 9.6125
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 94.0382 - root_mean_squared_error: 9.5277
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 93.0474 - root_mean_squared_error: 9.4691
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 91.4025 - root_mean_squared_error: 9.3765
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 90.4444 - root_mean_squared_error: 9.3200
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 89.7247 - root_mean_squared_error: 9.2760
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step
Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 117.1645 - root_mean_squared_error: 10.5183
Epoch 2/20
  22/5116 ━━━━━━━━━━━━━━━━━━━━ 37s 7ms/step - loss: 63.1685 - root_mean_squared_error: 7.9144

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 62.7047 - root_mean_squared_error: 7.8827
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 58.3594 - root_mean_squared_error: 7.5910
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 55.9315 - root_mean_squared_error: 7.4193
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 54.0625 - root_mean_squared_error: 7.2834
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 52.7082 - root_mean_squared_error: 7.1821
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.7193 - root_mean_squared_error: 7.1054
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.9417 - root_mean_squared_error: 7.0443
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 50.4112 - root_mean_squared_error: 7.0005
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 50.1152 - root_mean_squared_error: 6.9744
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 49.3846 - root_mean_squared_error: 6.9171
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 48.4550 - root_mean_squared_error: 6.8447
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 48.2516 - root_mean_squared_error: 6.8259
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 48.0453 - root_mean_squared_error: 6.8069
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 47.0662 - root_mean_squared_error: 6.7312
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 46.8430 - root_mean_squared_error: 6.7110
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 46.6019 - root_mean_squared_error: 6.6896
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 45.9651 - root_mean_squared_error: 6.6383
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 45.8310 - root_mean_squared_error: 6.6247
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - loss: 45.5125 - root_mean_squared_error: 6.5973
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step

[I 2025-06-17 16:27:24,330] Trial 11 finished with value: 12.75138769324007 and parameters: {'cell_size': 128, 'learning_rate': 0.0007746521536265282, 'epochs': 20, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 301.8394 - root_mean_squared_error: 16.9276
Epoch 2/20
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 139.8204 - root_mean_squared_error: 11.7908

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 139.2605 - root_mean_squared_error: 11.7644
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 127.6730 - root_mean_squared_error: 11.2508
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 120.9452 - root_mean_squared_error: 10.9389
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 115.1407 - root_mean_squared_error: 10.6612
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 111.3479 - root_mean_squared_error: 10.4729
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 107.7389 - root_mean_squared_error: 10.2905
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 104.9103 - root_mean_squared_error: 10.1439
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 102.3919 - root_mean_squared_error: 10.0105
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 100.1429 - root_mean_squared_error: 9.8895
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 98.6895 - root_mean_squared_error: 9.8085
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 97.0199 - root_mean_squared_error: 9.7162
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 96.0564 - root_mean_squared_error: 9.6601
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 94.2944 - root_mean_squared_error: 9.5626
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 93.5272 - root_mean_squared_error: 9.5165
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 92.0430 - root_mean_squared_error: 9.4328
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 91.1134 - root_mean_squared_error: 9.3780
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 89.9984 - root_mean_squared_error: 9.3136
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 89.4002 - root_mean_squared_error: 9.2766
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 88.0519 - root_mean_squared_error: 9.1990
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step
Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 118.1277 - root_mean_squared_error: 10.5599
Epoch 2/20
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 63.6999 - root_mean_squared_error: 7.9462

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 63.2918 - root_mean_squared_error: 7.9198
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 59.3121 - root_mean_squared_error: 7.6544
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 56.4829 - root_mean_squared_error: 7.4590
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 54.9038 - root_mean_squared_error: 7.3447
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 53.5236 - root_mean_squared_error: 7.2428
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 52.0895 - root_mean_squared_error: 7.1368
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 51.2965 - root_mean_squared_error: 7.0752
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 50.6920 - root_mean_squared_error: 7.0267
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 50.3156 - root_mean_squared_error: 6.9947
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 49.5813 - root_mean_squared_error: 6.9382
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 49.3040 - root_mean_squared_error: 6.9140
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 48.9483 - root_mean_squared_error: 6.8842
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 48.3538 - root_mean_squared_error: 6.8378
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 48.1274 - root_mean_squared_error: 6.8178
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 47.8822 - root_mean_squared_error: 6.7967
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 47.1049 - root_mean_squared_error: 6.7366
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 47.2263 - root_mean_squared_error: 6.7426
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 46.8457 - root_mean_squared_error: 6.7119
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 46.3418 - root_mean_squared_error: 6.6720
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 16:48:24,906] Trial 12 finished with value: 13.74007443602116 and parameters: {'cell_size': 128, 'learning_rate': 0.0007830175540183878, 'epochs': 20, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/18

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 6ms/step - loss: 304.8675 - root_mean_squared_error: 17.0125
Epoch 2/18
  25/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 144.3074 - root_mean_squared_error: 11.9841

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 138.8914 - root_mean_squared_error: 11.7544
Epoch 3/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 127.5529 - root_mean_squared_error: 11.2541
Epoch 4/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 120.9282 - root_mean_squared_error: 10.9472
Epoch 5/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 116.5762 - root_mean_squared_error: 10.7378
Epoch 6/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 112.8512 - root_mean_squared_error: 10.5538
Epoch 7/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 110.1920 - root_mean_squared_error: 10.4184
Epoch 8/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 107.1276 - root_mean_squared_error: 10.2621
Epoch 9/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 104.1227 - root_mean_squared_error: 10.1066
Epoch 10/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 102.0115 - root_mean_squared_error: 9.9938
Epoch 11/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 100.2225 - root_mean_squared_error: 9.8961
Epoch 12/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 98.1295 - root_mean_squared_error: 9.7820
Epoch 13/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 95.7115 - root_mean_squared_error: 9.6499
Epoch 14/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 94.8429 - root_mean_squared_error: 9.5979
Epoch 15/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 93.1973 - root_mean_squared_error: 9.5044
Epoch 16/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 91.9612 - root_mean_squared_error: 9.4319
Epoch 17/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 90.2415 - root_mean_squared_error: 9.3338
Epoch 18/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 89.5031 - root_mean_squared_error: 9.2874
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/18

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 120.8800 - root_mean_squared_error: 10.6674
Epoch 2/18
  26/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 64.1373 - root_mean_squared_error: 7.9785

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 62.7324 - root_mean_squared_error: 7.8878
Epoch 3/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 58.3971 - root_mean_squared_error: 7.5976
Epoch 4/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 55.8946 - root_mean_squared_error: 7.4211
Epoch 5/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 54.1230 - root_mean_squared_error: 7.2925
Epoch 6/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 53.1061 - root_mean_squared_error: 7.2146
Epoch 7/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.7445 - root_mean_squared_error: 7.1127
Epoch 8/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.9693 - root_mean_squared_error: 7.0517
Epoch 9/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.7088 - root_mean_squared_error: 7.0276
Epoch 10/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.5979 - root_mean_squared_error: 6.9434
Epoch 11/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.2449 - root_mean_squared_error: 6.9143
Epoch 12/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.2811 - root_mean_squared_error: 6.9133
Epoch 13/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 48.6347 - root_mean_squared_error: 6.8624
Epoch 14/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 47.8232 - root_mean_squared_error: 6.7995
Epoch 15/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 47.7605 - root_mean_squared_error: 6.7919
Epoch 16/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 47.4194 - root_mean_squared_error: 6.7641
Epoch 17/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 46.9848 - root_mean_squared_error: 6.7291
Epoch 18/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 46.7768 - root_mean_squared_error: 6.7109
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 17:08:11,116] Trial 13 finished with value: 13.722669251763257 and parameters: {'cell_size': 128, 'learning_rate': 0.0007138687220255074, 'epochs': 18, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 289.8823 - root_mean_squared_error: 16.6016
Epoch 2/20
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 156.9047 - root_mean_squared_error: 12.4914

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 140.4497 - root_mean_squared_error: 11.8135
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 130.3174 - root_mean_squared_error: 11.3643
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 123.7168 - root_mean_squared_error: 11.0586
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 117.8223 - root_mean_squared_error: 10.7771
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 113.7713 - root_mean_squared_error: 10.5764
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 110.1882 - root_mean_squared_error: 10.3953
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 107.8044 - root_mean_squared_error: 10.2702
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 105.6998 - root_mean_squared_error: 10.1579
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 103.8111 - root_mean_squared_error: 10.0567
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 102.1291 - root_mean_squared_error: 9.9660
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 100.6548 - root_mean_squared_error: 9.8852
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 99.8885 - root_mean_squared_error: 9.8393
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 98.6564 - root_mean_squared_error: 9.7706
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 97.2113 - root_mean_squared_error: 9.6902
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 96.2417 - root_mean_squared_error: 9.6351
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 95.1061 - root_mean_squared_error: 9.5711
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 95.0528 - root_mean_squared_error: 9.5637
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 94.1333 - root_mean_squared_error: 9.5109
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 92.6671 - root_mean_squared_error: 9.4286
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 113.4489 - root_mean_squared_error: 10.3578
Epoch 2/20
  28/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 65.1117 - root_mean_squared_error: 8.0343

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 63.0967 - root_mean_squared_error: 7.9057
Epoch 3/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 58.9859 - root_mean_squared_error: 7.6281
Epoch 4/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 56.0521 - root_mean_squared_error: 7.4212
Epoch 5/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 54.2208 - root_mean_squared_error: 7.2869
Epoch 6/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 53.1700 - root_mean_squared_error: 7.2064
Epoch 7/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.9537 - root_mean_squared_error: 7.1139
Epoch 8/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.6697 - root_mean_squared_error: 7.0875
Epoch 9/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.7296 - root_mean_squared_error: 7.0157
Epoch 10/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.3091 - root_mean_squared_error: 6.9804
Epoch 11/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 49.8404 - root_mean_squared_error: 6.9411
Epoch 12/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 49.6366 - root_mean_squared_error: 6.9215
Epoch 13/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 49.0492 - root_mean_squared_error: 6.8750
Epoch 14/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 48.7269 - root_mean_squared_error: 6.8474
Epoch 15/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 48.1727 - root_mean_squared_error: 6.8034
Epoch 16/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 47.7557 - root_mean_squared_error: 6.7695
Epoch 17/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 47.3873 - root_mean_squared_error: 6.7398
Epoch 18/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 46.9099 - root_mean_squared_error: 6.7022
Epoch 19/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 46.7933 - root_mean_squared_error: 6.6911
Epoch 20/20
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 46.3719 - root_mean_squared_error: 6.6572
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step

[I 2025-06-17 17:29:11,414] Trial 14 finished with value: 13.554139752039596 and parameters: {'cell_size': 128, 'learning_rate': 0.0008820973309000404, 'epochs': 20, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/18

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 310.9155 - root_mean_squared_error: 17.1712
Epoch 2/18
  28/5116 ━━━━━━━━━━━━━━━━━━━━ 29s 6ms/step - loss: 136.3880 - root_mean_squared_error: 11.6490

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 140.0970 - root_mean_squared_error: 11.8054
Epoch 3/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 130.0439 - root_mean_squared_error: 11.3625
Epoch 4/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 123.8392 - root_mean_squared_error: 11.0762
Epoch 5/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 117.9629 - root_mean_squared_error: 10.7968
Epoch 6/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 113.6449 - root_mean_squared_error: 10.5851
Epoch 7/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 109.7020 - root_mean_squared_error: 10.3882
Epoch 8/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 107.3919 - root_mean_squared_error: 10.2684
Epoch 9/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 105.0111 - root_mean_squared_error: 10.1443
Epoch 10/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 103.1802 - root_mean_squared_error: 10.0460
Epoch 11/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 101.4885 - root_mean_squared_error: 9.9540
Epoch 12/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 99.6465 - root_mean_squared_error: 9.8537
Epoch 13/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 98.4874 - root_mean_squared_error: 9.7878
Epoch 14/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 96.7212 - root_mean_squared_error: 9.6907
Epoch 15/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 95.3797 - root_mean_squared_error: 9.6148
Epoch 16/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 94.5503 - root_mean_squared_error: 9.5652
Epoch 17/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 93.0879 - root_mean_squared_error: 9.4825
Epoch 18/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 92.2396 - root_mean_squared_error: 9.4317
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step
Epoch 1/18

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 117.3091 - root_mean_squared_error: 10.5378
Epoch 2/18
  25/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 66.1522 - root_mean_squared_error: 8.1040

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 62.8225 - root_mean_squared_error: 7.8951
Epoch 3/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 59.0078 - root_mean_squared_error: 7.6410
Epoch 4/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 55.8412 - root_mean_squared_error: 7.4221
Epoch 5/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 54.8623 - root_mean_squared_error: 7.3470
Epoch 6/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 53.1244 - root_mean_squared_error: 7.2199
Epoch 7/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 52.2504 - root_mean_squared_error: 7.1518
Epoch 8/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 51.0796 - root_mean_squared_error: 7.0628
Epoch 9/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 50.7276 - root_mean_squared_error: 7.0319
Epoch 10/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 50.0100 - root_mean_squared_error: 6.9747
Epoch 11/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 49.1588 - root_mean_squared_error: 6.9079
Epoch 12/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 48.9520 - root_mean_squared_error: 6.8876
Epoch 13/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 48.5002 - root_mean_squared_error: 6.8500
Epoch 14/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 48.1680 - root_mean_squared_error: 6.8213
Epoch 15/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 47.4275 - root_mean_squared_error: 6.7627
Epoch 16/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 46.8743 - root_mean_squared_error: 6.7183
Epoch 17/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 46.7833 - root_mean_squared_error: 6.7083
Epoch 18/18
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 46.5132 - root_mean_squared_error: 6.6847
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 17:48:31,698] Trial 15 finished with value: 13.722818082135579 and parameters: {'cell_size': 128, 'learning_rate': 0.0007144382848955326, 'epochs': 18, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/19

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 281.6199 - root_mean_squared_error: 16.4035
Epoch 2/19
  21/5116 ━━━━━━━━━━━━━━━━━━━━ 41s 8ms/step - loss: 143.6004 - root_mean_squared_error: 11.9487

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 141.1555 - root_mean_squared_error: 11.8447
Epoch 3/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 129.4156 - root_mean_squared_error: 11.3270
Epoch 4/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 124.3189 - root_mean_squared_error: 11.0899
Epoch 5/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 119.4699 - root_mean_squared_error: 10.8598
Epoch 6/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 115.2335 - root_mean_squared_error: 10.6533
Epoch 7/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 112.3245 - root_mean_squared_error: 10.5070
Epoch 8/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 109.9566 - root_mean_squared_error: 10.3848
Epoch 9/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 107.3551 - root_mean_squared_error: 10.2499
Epoch 10/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 36s 7ms/step - loss: 104.9862 - root_mean_squared_error: 10.1251
Epoch 11/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 103.8108 - root_mean_squared_error: 10.0583
Epoch 12/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 101.7770 - root_mean_squared_error: 9.9485
Epoch 13/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 100.7476 - root_mean_squared_error: 9.8889
Epoch 14/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 99.3254 - root_mean_squared_error: 9.8091
Epoch 15/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 98.1769 - root_mean_squared_error: 9.7437
Epoch 16/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 97.2404 - root_mean_squared_error: 9.6894
Epoch 17/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 96.1732 - root_mean_squared_error: 9.6287
Epoch 18/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 95.3794 - root_mean_squared_error: 9.5820
Epoch 19/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 94.2761 - root_mean_squared_error: 9.5190
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/19

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 115.8610 - root_mean_squared_error: 10.4582
Epoch 2/19
  25/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 67.9959 - root_mean_squared_error: 8.2105

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 63.4673 - root_mean_squared_error: 7.9299
Epoch 3/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 59.8691 - root_mean_squared_error: 7.6882
Epoch 4/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 57.1956 - root_mean_squared_error: 7.4999
Epoch 5/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 55.0098 - root_mean_squared_error: 7.3415
Epoch 6/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 53.7950 - root_mean_squared_error: 7.2497
Epoch 7/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 52.8268 - root_mean_squared_error: 7.1742
Epoch 8/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 51.8979 - root_mean_squared_error: 7.1016
Epoch 9/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 51.4695 - root_mean_squared_error: 7.0647
Epoch 10/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 50.5336 - root_mean_squared_error: 6.9920
Epoch 11/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 50.1146 - root_mean_squared_error: 6.9569
Epoch 12/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 49.4771 - root_mean_squared_error: 6.9064
Epoch 13/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 49.5156 - root_mean_squared_error: 6.9049
Epoch 14/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 48.8669 - root_mean_squared_error: 6.8545
Epoch 15/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 48.5380 - root_mean_squared_error: 6.8274
Epoch 16/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 48.0637 - root_mean_squared_error: 6.7899
Epoch 17/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 47.6725 - root_mean_squared_error: 6.7578
Epoch 18/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 47.4999 - root_mean_squared_error: 6.7421
Epoch 19/19
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 46.9008 - root_mean_squared_error: 6.6954
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 18:10:30,378] Trial 16 finished with value: 14.393054582670583 and parameters: {'cell_size': 128, 'learning_rate': 0.0008673260954701896, 'epochs': 19, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/16

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 280.9729 - root_mean_squared_error: 16.3474
Epoch 2/16
  25/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 147.3550 - root_mean_squared_error: 12.1008

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 140.5747 - root_mean_squared_error: 11.8192
Epoch 3/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 129.6273 - root_mean_squared_error: 11.3341
Epoch 4/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 122.1175 - root_mean_squared_error: 10.9853
Epoch 5/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 116.9272 - root_mean_squared_error: 10.7325
Epoch 6/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 111.8628 - root_mean_squared_error: 10.4812
Epoch 7/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 108.9848 - root_mean_squared_error: 10.3315
Epoch 8/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 106.1572 - root_mean_squared_error: 10.1831
Epoch 9/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 103.1318 - root_mean_squared_error: 10.0238
Epoch 10/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 35s 7ms/step - loss: 101.6946 - root_mean_squared_error: 9.9437
Epoch 11/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 99.1921 - root_mean_squared_error: 9.8096
Epoch 12/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 98.1099 - root_mean_squared_error: 9.7476
Epoch 13/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 96.7281 - root_mean_squared_error: 9.6701
Epoch 14/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 95.1778 - root_mean_squared_error: 9.5835
Epoch 15/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 94.3148 - root_mean_squared_error: 9.5329
Epoch 16/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 93.0976 - root_mean_squared_error: 9.4634
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step
Epoch 1/16

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 112.5339 - root_mean_squared_error: 10.3199
Epoch 2/16
  26/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 60.6156 - root_mean_squared_error: 7.7436

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 62.9451 - root_mean_squared_error: 7.8915
Epoch 3/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 58.7647 - root_mean_squared_error: 7.6066
Epoch 4/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 56.6047 - root_mean_squared_error: 7.4514
Epoch 5/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 54.9093 - root_mean_squared_error: 7.3271
Epoch 6/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 53.8684 - root_mean_squared_error: 7.2472
Epoch 7/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 52.6143 - root_mean_squared_error: 7.1533
Epoch 8/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.9373 - root_mean_squared_error: 7.0991
Epoch 9/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.0760 - root_mean_squared_error: 7.0326
Epoch 10/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.7390 - root_mean_squared_error: 7.0038
Epoch 11/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 49.9119 - root_mean_squared_error: 6.9403
Epoch 12/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 49.7255 - root_mean_squared_error: 6.9226
Epoch 13/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.6756 - root_mean_squared_error: 6.9148
Epoch 14/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 48.9028 - root_mean_squared_error: 6.8552
Epoch 15/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 48.4828 - root_mean_squared_error: 6.8214
Epoch 16/16
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 48.2303 - root_mean_squared_error: 6.8000
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step

[I 2025-06-17 18:28:05,355] Trial 17 finished with value: 15.154157662738054 and parameters: {'cell_size': 128, 'learning_rate': 0.0009874883949536723, 'epochs': 16, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/13

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 296.3760 - root_mean_squared_error: 16.8042
Epoch 2/13
  25/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 133.2531 - root_mean_squared_error: 11.5122

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 139.4291 - root_mean_squared_error: 11.7760
Epoch 3/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 129.7013 - root_mean_squared_error: 11.3453
Epoch 4/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 122.6499 - root_mean_squared_error: 11.0201
Epoch 5/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 117.2858 - root_mean_squared_error: 10.7635
Epoch 6/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 113.2155 - root_mean_squared_error: 10.5630
Epoch 7/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 109.3564 - root_mean_squared_error: 10.3694
Epoch 8/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 106.8640 - root_mean_squared_error: 10.2395
Epoch 9/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 104.7639 - root_mean_squared_error: 10.1277
Epoch 10/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 102.7218 - root_mean_squared_error: 10.0178
Epoch 11/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 34s 7ms/step - loss: 101.1223 - root_mean_squared_error: 9.9287
Epoch 12/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 99.1561 - root_mean_squared_error: 9.8212
Epoch 13/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 7ms/step - loss: 97.6362 - root_mean_squared_error: 9.7358
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/13

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 118.3760 - root_mean_squared_error: 10.5700
Epoch 2/13
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 30s 6ms/step - loss: 64.4668 - root_mean_squared_error: 7.9960

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 63.3915 - root_mean_squared_error: 7.9264
Epoch 3/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 58.9557 - root_mean_squared_error: 7.6302
Epoch 4/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 56.3568 - root_mean_squared_error: 7.4487
Epoch 5/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 54.5622 - root_mean_squared_error: 7.3193
Epoch 6/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 53.4726 - root_mean_squared_error: 7.2371
Epoch 7/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 52.2578 - root_mean_squared_error: 7.1462
Epoch 8/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.0245 - root_mean_squared_error: 7.0529
Epoch 9/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.5220 - root_mean_squared_error: 7.0111
Epoch 10/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.5963 - root_mean_squared_error: 6.9397
Epoch 11/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 48.7382 - root_mean_squared_error: 6.8725
Epoch 12/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 48.2120 - root_mean_squared_error: 6.8295
Epoch 13/13
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 47.6580 - root_mean_squared_error: 6.7844
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 18:42:30,053] Trial 18 finished with value: 15.775160127732885 and parameters: {'cell_size': 128, 'learning_rate': 0.0007652739513842958, 'epochs': 13, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

Epoch 1/10

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 306.8549 - root_mean_squared_error: 17.0728
Epoch 2/10
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 148.0933 - root_mean_squared_error: 12.1353

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 138.8188 - root_mean_squared_error: 11.7495
Epoch 3/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 126.3477 - root_mean_squared_error: 11.1978
Epoch 4/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 120.1886 - root_mean_squared_error: 10.9101
Epoch 5/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 115.1986 - root_mean_squared_error: 10.6699
Epoch 6/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 111.1504 - root_mean_squared_error: 10.4698
Epoch 7/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 108.2566 - root_mean_squared_error: 10.3220
Epoch 8/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 105.8475 - root_mean_squared_error: 10.1960
Epoch 9/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - loss: 103.1033 - root_mean_squared_error: 10.0531
Epoch 10/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 32s 6ms/step - loss: 101.3717 - root_mean_squared_error: 9.9594
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step
Epoch 1/10

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 119.9173 - root_mean_squared_error: 10.6454
Epoch 2/10
  27/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 74.2602 - root_mean_squared_error: 8.5770

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 63.3757 - root_mean_squared_error: 7.9277
Epoch 3/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 58.8993 - root_mean_squared_error: 7.6307
Epoch 4/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 56.0768 - root_mean_squared_error: 7.4335
Epoch 5/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 53.6721 - root_mean_squared_error: 7.2616
Epoch 6/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 52.9953 - root_mean_squared_error: 7.2077
Epoch 7/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 51.7710 - root_mean_squared_error: 7.1162
Epoch 8/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 50.6875 - root_mean_squared_error: 7.0341
Epoch 9/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.7386 - root_mean_squared_error: 6.9612
Epoch 10/10
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 31s 6ms/step - loss: 49.2325 - root_mean_squared_error: 6.9204
5116/5116 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step

[I 2025-06-17 18:53:20,285] Trial 19 finished with value: 14.604387288790493 and parameters: {'cell_size': 128, 'learning_rate': 0.0006758121204295375, 'epochs': 10, 'batch_size': 256}. Best is trial 11 with value: 12.75138769324007.

In [27]:
print("Random Search에서의 최고의 하이퍼파라미터 조합 : ", bayesian_study.best_params)

Random Search에서의 최고의 하이퍼파라미터 조합 :  {'cell_size': 128, 'learning_rate': 0.0007746521536265282, 'epochs': 20, 'batch_size': 256}

In [28]:
best_params = bayesian_study.best_params
final_lstm_model = lstm_model(
    cell_size=best_params['cell_size'],
    learning_rate=best_params['learning_rate']
)

history = final_lstm_model.fit(
    x_train, t_train,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    callbacks=[early_stopping]
)

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 321s 6ms/step - loss: 106.2686 - root_mean_squared_error: 10.2081
Epoch 2/20

/opt/anaconda3/lib/python3.12/site-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,root_mean_squared_error
  current = self.get_monitor_value(logs)

51155/51155 ━━━━━━━━━━━━━━━━━━━━ 301s 6ms/step - loss: 85.5827 - root_mean_squared_error: 9.1661
Epoch 3/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 320s 6ms/step - loss: 80.2262 - root_mean_squared_error: 8.8443
Epoch 4/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 318s 6ms/step - loss: 76.9557 - root_mean_squared_error: 8.6370
Epoch 5/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 316s 6ms/step - loss: 75.2132 - root_mean_squared_error: 8.5240
Epoch 6/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 320s 6ms/step - loss: 73.7317 - root_mean_squared_error: 8.4263
Epoch 7/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 317s 6ms/step - loss: 73.8392 - root_mean_squared_error: 8.4299
Epoch 8/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 304s 6ms/step - loss: 73.1968 - root_mean_squared_error: 8.3876
Epoch 9/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 313s 6ms/step - loss: 72.1967 - root_mean_squared_error: 8.3238
Epoch 10/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 322s 6ms/step - loss: 72.1289 - root_mean_squared_error: 8.3157
Epoch 11/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 335s 7ms/step - loss: 72.1551 - root_mean_squared_error: 8.3144
Epoch 12/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 334s 7ms/step - loss: 71.3339 - root_mean_squared_error: 8.2622
Epoch 13/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 323s 6ms/step - loss: 71.0870 - root_mean_squared_error: 8.2450
Epoch 14/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 317s 6ms/step - loss: 70.7383 - root_mean_squared_error: 8.2209
Epoch 15/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 317s 6ms/step - loss: 69.6614 - root_mean_squared_error: 8.1523
Epoch 16/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 320s 6ms/step - loss: 69.2758 - root_mean_squared_error: 8.1262
Epoch 17/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 317s 6ms/step - loss: 69.2292 - root_mean_squared_error: 8.1185
Epoch 18/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 323s 6ms/step - loss: 68.6245 - root_mean_squared_error: 8.0799
Epoch 19/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 329s 6ms/step - loss: 68.2942 - root_mean_squared_error: 8.0568
Epoch 20/20
51155/51155 ━━━━━━━━━━━━━━━━━━━━ 316s 6ms/step - loss: 67.7238 - root_mean_squared_error: 8.0195

In [29]:
pred = final_lstm_model.predict(x_test)

for i in range(0, 20):
    print('혼잡도 예측 : ', round(pred[i][0], 2), '/정답 :', round(t_test[i][0], 2))

102309/102309 ━━━━━━━━━━━━━━━━━━━━ 59s 571us/step
혼잡도 예측 :  4.66 /정답 : 8.0
혼잡도 예측 :  8.96 /정답 : 9.0
혼잡도 예측 :  9.35 /정답 : 13.0
혼잡도 예측 :  12.87 /정답 : 18.0
혼잡도 예측 :  19.67 /정답 : 13.0
혼잡도 예측 :  9.77 /정답 : 9.0
혼잡도 예측 :  7.06 /정답 : 12.0
혼잡도 예측 :  13.43 /정답 : 5.0
혼잡도 예측 :  2.3 /정답 : 3.0
혼잡도 예측 :  3.62 /정답 : 2.0
혼잡도 예측 :  3.21 /정답 : 0.0
혼잡도 예측 :  2.44 /정답 : 6.0
혼잡도 예측 :  4.21 /정답 : 5.0
혼잡도 예측 :  3.78 /정답 : 7.0
혼잡도 예측 :  8.83 /정답 : 5.0
혼잡도 예측 :  3.3 /정답 : 3.0
혼잡도 예측 :  4.97 /정답 : 4.0
혼잡도 예측 :  1.98 /정답 : 6.0
혼잡도 예측 :  3.99 /정답 : 6.0
혼잡도 예측 :  3.96 /정답 : 6.0

In [30]:
loss, rmse = final_lstm_model.evaluate(x_test, t_test, verbose=1)
print('test loss(MSE) :', round(loss, 6))
print('test RMSE :', round(rmse, 2))

102309/102309 ━━━━━━━━━━━━━━━━━━━━ 63s 619us/step - loss: 144.2846 - root_mean_squared_error: 11.6320
test loss(MSE) : 136.410263
test RMSE : 11.53